# proto-file: src/main/proto/wfa/measurement/config/duchy_rpc_config.proto
# proto-message: DuchyRpcConfig
duchies {
  duchy_id: "aggregator"
  computation_control_service_target: "$(AGGREGATOR_COMPUTATION_CONTROL_SERVER_SERVICE_HOST):$(AGGREGATOR_COMPUTATION_CONTROL_SERVER_SERVICE_PORT)"
  computation_control_service_cert_host: "localhost"
  root_certificate_skid: "\xA2\xA9\x4E\x5E\xFD\x7F\x18\xAC\x66\xE8\x99\xE6\xA9\x21\x57\x1E\xB6\xBB\x29\x97"
}
duchies {
  duchy_id: "worker1"
  computation_control_service_target: "$(WORKER_1_COMPUTATION_CONTROL_SERVER_SERVICE_HOST):$(WORKER_1_COMPUTATION_CONTROL_SERVER_SERVICE_PORT)"
  computation_control_service_cert_host: "localhost"
  root_certificate_skid: "\x21\x1C\x14\xE5\x39\x48\x22\xB9\xBE\x8B\xE7\xB6\x2F\x46\x3F\x03\x4E\x3A\x80\x73"
}
duchies {
  duchy_id: "worker2"
  computation_control_service_target: "$(WORKER_2_COMPUTATION_CONTROL_SERVER_SERVICE_HOST):$(WORKER_2_COMPUTATION_CONTROL_SERVER_SERVICE_PORT)"
  computation_control_service_cert_host: "localhost"
  root_certificate_skid: "\xC9\x81\xE5\xBC\x00\x0D\x2F\x1C\x9C\x4E\xC9\xE2\x07\x8D\x7A\xA5\x54\x7B\x36\x74"
}
