name: "modelProviders/AAAAAAAAAHs/modelSuites/AAAAAAAAAHs/modelLines/AAAAAAAAAHs/modelRollouts/rollout_01"

gradual_rollout_period {
  start_date: {
    year: 2004
    month: 11
    day: 9
  }
  end_date: {
    year: 2017
    month: 7
    day: 14
  }
}

model_release: "modelProviders/AAAAAAAAAHs/modelSuites/AAAAAAAAAHs/modelReleases/rollout_01"

