# proto-file: wfa/measurement/reporting/v2alpha/report.proto
# proto-message: Report.ReportingMetricEntry
key: "measurementConsumers/Dipo47pr5to/reportingSets/abc"
value {
  metric_calculation_specs {
    display_name: "spec_1"
    metric_specs {
      reach {
        privacy_params {
          epsilon: 0.0041
          delta: 1.0E-12
        }
      }
      vid_sampling_interval {
        width: 0.01
      }
    }
  }
}