# proto-file: wfa/measurement/config/access/permissions_config.proto
# proto-message: wfa.measurement.config.access.PermissionsConfig

# dataProviders
permissions {
  key: "reporting.dataProviders.get"
  value {
    protected_resource_types: "reporting.halo-cmm.org/Root"
  }
}

# eventGroupMetadataDescriptors
permissions {
  key: "reporting.eventGroupMetadataDescriptors.get"
  value {
    protected_resource_types: "reporting.halo-cmm.org/Root"
  }
}

# eventGroups
permissions {
  key: "reporting.eventGroups.get"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/EventGroup"
  }
}
permissions {
  key: "reporting.eventGroups.list"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}

# reportingSets
permissions {
  key: "reporting.reportingSets.get"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/ReportingSet"
  }
}
permissions {
  key: "reporting.reportingSets.list"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.reportingSets.createPrimitive"
  value {
    description: "Create a primitive ReportingSet resource"
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.reportingSets.createComposite"
  value {
    description: "Create a composite ReportingSet resource"
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}

# metrics
permissions {
  key: "reporting.metrics.get"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/Metric"
  }
}
permissions {
  key: "reporting.metrics.list"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.metrics.create"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    description: "Create a Metric resource."
  }
}
permissions {
  key: "reporting.metrics.createWithDevModelLine"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    description: "When creating a Metric resource, use a ModelLine of type DEV."
  }
}
permissions {
  key: "reporting.metrics.invalidate"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/Metric"
  }
}

# metricCalculationSpecs
permissions {
  key: "reporting.metricCalculationSpecs.get"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/MetricCalculationSpec"
  }
}
permissions {
  key: "reporting.metricCalculationSpecs.list"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.metricCalculationSpecs.create"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}

# reports
permissions {
  key: "reporting.reports.get"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/Report"
  }
}
permissions {
  key: "reporting.reports.list"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.reports.create"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}

# reportSchedules
permissions {
  key: "reporting.reportSchedules.get"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/ReportSchedule"
  }
}
permissions {
  key: "reporting.reportSchedules.list"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.reportSchedules.create"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.reportSchedules.stop"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/ReportSchedule"
  }
}

# basicReports
permissions {
  key: "reporting.basicReports.create"
  value {
    description: "Create a BasicReport resource"
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.basicReports.createWithDevModelLine"
  value {
    description: "When creating a BasicReport resource, use a ModelLine of type DEV"
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}
permissions {
  key: "reporting.basicReports.get"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
    protected_resource_types: "reporting.halo-cmm.org/BasicReport"
  }
}
permissions {
  key: "reporting.basicReports.list"
  value {
    protected_resource_types: "halo.wfanet.org/MeasurementConsumer"
  }
}

# impressionQualificationFilters
permissions {
  key: "reporting.impressionQualificationFilters.get"
  value {
    protected_resource_types: "reporting.halo-cmm.org/Root"
    protected_resource_types: "reporting.halo-cmm.org/ImpressionQualificationFilter"
  }
}
permissions {
  key: "reporting.impressionQualificationFilters.list"
  value {
    protected_resource_types: "reporting.halo-cmm.org/Root"
  }
}

# modelLines
permissions {
  key: "reporting.modelLines.list"
  value {
    protected_resource_types: "reporting.halo-cmm.org/Root"
  }
}
