// Copyright 2024 The Cross-Media Measurement Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package wfa.measurement.reporting.v2alpha;

import "google/api/field_behavior.proto";
import "google/type/date.proto";
import "google/type/datetime.proto";

option java_package = "org.wfanet.measurement.reporting.v2alpha";
option java_multiple_files = true;
option java_outer_classname = "ReportingIntervalProto";
option go_package = "github.com/world-federation-of-advertisers/cross-media-measurement/reporting/apiv2alpha/reportingpb";

// The time interval over which Metrics are reported.
//
// This is defined as an inclusive start timestamp and exclusive end timestamp.
// In mathematical notation, `[start, end)`. For example, if the effective start
// is `2026-05-01T06:00:00-04:00` and the effective end is
// `2026-06-01T06:00:00-04:00` then the reporting interval is
// `[2026-05-01T06:00:00-04:00, 2026-06-01T06:00:00-04:00)`. This means that an
// event at `2026-06-01T05:59:59-04:00` would be included but not an event at
// `2026-06-01T06:00:00-04:00`.
message ReportingInterval {
  // Input for determining the effective start of the report. Required.
  oneof report_start_time {
    // The date and time of the start of the report, inclusive.
    //
    // The [year][google.type.DateTime.year],
    // [month][google.type.DateTime.month], [day][google.type.DateTime.day],
    // [hours][google.type.DateTime.hours], and
    // [time_offset][google.type.DateTime.time_offset] fields are required.
    //
    // The granularity is in hours. The time component of this field determines
    // the start of the reporting day. See [effective_report_start][].
    google.type.DateTime report_start = 1
        [(google.api.field_behavior) = IMMUTABLE];

    // The date of the start of the report.
    //
    // The [year][google.type.Date.year],
    // [month][google.type.Date.month], and [day][google.type.Date.day]
    // fields are required.
    //
    // Server defaults will be used for the time portion if they have been
    // configured. If not, setting this field is an error. See
    // [effective_report_start][].
    google.type.Date report_start_date = 4
        [(google.api.field_behavior) = IMMUTABLE];
  }

  // The effective start of the report, inclusive.
  //
  // The granularity is in hours.
  //
  // This will be the same as [report_start][] if that field is set. If
  // [report_start_date][] is set instead, this will be the date (`year`,
  // `month`,`day`) from [report_start_date][] and the time (`hours`,
  // `time_offset`) from the configured server defaults. Note that this is not
  // related to the server system clock.
  //
  // The time component of this field defines the start of a reporting day. If
  // [utc_offset][google.type.DateTime.utc_offset] is set, daylight saving time
  // is ignored and the reporting days will be 24 hours based on the time of day
  // specified here. If [time_zone][google.type.DateTime.time_zone] is set, the
  // length of reporting days may vary due to daylight savings; if 5 AM is
  // chosen, the day will start at 5 AM year-round.
  google.type.DateTime effective_report_start = 3
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // The end date of the report.
  //
  // Note that this should be set to the day **after** the desired final
  // reporting day. See below.
  //
  // This is used to determine the (exclusive) effective report end, which is
  // defined as the date from this field and the time from
  // [effective_report_start][]. For example, if [effective_report_start][] is
  // `2026-03-01T06:00:00-05:00`, and [report_end][] is `2026-04-01` then the
  // effective report end is `2026-04-01T06:00:00-05:00`.
  //
  // Note that if [effective_report_start][] had a time zone of
  // `America/New_York` specified instead of a UTC offset of `-05:00` then the
  // effective report end would instead be `2026-04-01T06:00:00-04:00` due to
  // daylight saving time (DST).
  google.type.Date report_end = 2 [(google.api.field_behavior) = REQUIRED];
}
