name: 'Terraform Plan'
description: 'Run Terraform plan'
inputs:
  working_directory:
    description: 'The directory where the Terraform configuration is located.'
    required: true
    default: .
  environment:
    description: 'The terraform workspace to be used'
    required: true
    default: "qa"
  project:
    description: 'The project name to be used'
    required: true
    default: .

runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        terraform plan '-out=${{ inputs.environment }}_tfplan' -var env=${{ inputs.environment }} -var project=${{ inputs.project }}
