name: 'Terraform Plan'
description: 'Run Terraform plan'
inputs:
  working_directory:
    description: 'The directory where the Terraform configuration is located.'
    required: true
    default: .
runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        terraform plan -input=false -no-color
