-- liquibase formatted sql

-- Copyright 2026 The Cross-Media Measurement Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- changeset getina:11 dbms:cloudspanner
-- comment: Create VID labeling pipeline tables: RawImpressionUpload,
-- RawImpressionUploadFile, RawImpressionUploadModelLine,
-- PoolAssignmentJob, RankerJob, RankIndexBlob, and VidLabelingJob.
-- Uses INT64 surrogate PKs with STRING resource IDs for external API access.

-- Set protobuf FileDescriptorSet as a base64 string.
SET PROTO_DESCRIPTORS =
'CoECCjZ3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvZWRwYWdncmVnYXRvci9ibG9iX3R5cGUucHJvdG8SJndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5lZHBhZ2dyZWdhdG9yKlUKCEJsb2JUeXBlEhkKFUJMT0JfVFlQRV9VTlNQRUNJRklFRBAAEhYKEkJMT0JfVFlQRV9EQVlfT05MWRABEhYKEkJMT0JfVFlQRV9TTkFQU0hPVBACQkAKLW9yZy53ZmFuZXQubWVhc3VyZW1lbnQuaW50ZXJuYWwuZWRwYWdncmVnYXRvckINQmxvYlR5cGVQcm90b1ABYgZwcm90bzMK3QIKRndmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9lZHBhZ2dyZWdhdG9yL2ltcHJlc3Npb25fbWV0YWRhdGFfc3RhdGUucHJvdG8SJndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5lZHBhZ2dyZWdhdG9yKpEBChdJbXByZXNzaW9uTWV0YWRhdGFTdGF0ZRIpCiVJTVBSRVNTSU9OX01FVEFEQVRBX1NUQVRFX1VOU1BFQ0lGSUVEEAASJAogSU1QUkVTU0lPTl9NRVRBREFUQV9TVEFURV9BQ1RJVkUQARIlCiFJTVBSRVNTSU9OX01FVEFEQVRBX1NUQVRFX0RFTEVURUQQAkJPCi1vcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLmVkcGFnZ3JlZ2F0b3JCHEltcHJlc3Npb25NZXRhZGF0YVN0YXRlUHJvdG9QAWIGcHJvdG8zCuoCCkJ3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvZWRwYWdncmVnYXRvci9wb29sX2Fzc2lnbm1lbnRfc3RhdGUucHJvdG8SJndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5lZHBhZ2dyZWdhdG9yKqYBChNQb29sQXNzaWdubWVudFN0YXRlEiUKIVBPT0xfQVNTSUdOTUVOVF9TVEFURV9VTlNQRUNJRklFRBAAEiEKHVBPT0xfQVNTSUdOTUVOVF9TVEFURV9DUkVBVEVEEAESIwofUE9PTF9BU1NJR05NRU5UX1NUQVRFX1NVQ0NFRURFRBACEiAKHFBPT0xfQVNTSUdOTUVOVF9TVEFURV9GQUlMRUQQA0JLCi1vcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLmVkcGFnZ3JlZ2F0b3JCGFBvb2xBc3NpZ25tZW50U3RhdGVQcm90b1ABYgZwcm90bzMKrAIKOXdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9lZHBhZ2dyZWdhdG9yL3Jhbmtlcl9zdGF0ZS5wcm90bxImd2ZhLm1lYXN1cmVtZW50LmludGVybmFsLmVkcGFnZ3JlZ2F0b3IqegoLUmFua2VyU3RhdGUSHAoYUkFOS0VSX1NUQVRFX1VOU1BFQ0lGSUVEEAASGAoUUkFOS0VSX1NUQVRFX0NSRUFURUQQARIaChZSQU5LRVJfU1RBVEVfU1VDQ0VFREVEEAISFwoTUkFOS0VSX1NUQVRFX0ZBSUxFRBADQkMKLW9yZy53ZmFuZXQubWVhc3VyZW1lbnQuaW50ZXJuYWwuZWRwYWdncmVnYXRvckIQUmFua2VyU3RhdGVQcm90b1ABYgZwcm90bzMKiwMKR3dmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9lZHBhZ2dyZWdhdG9yL3Jhd19pbXByZXNzaW9uX2JhdGNoX3N0YXRlLnByb3RvEiZ3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwuZWRwYWdncmVnYXRvciq+AQoXUmF3SW1wcmVzc2lvbkJhdGNoU3RhdGUSKgomUkFXX0lNUFJFU1NJT05fQkFUQ0hfU1RBVEVfVU5TUEVDSUZJRUQQABImCiJSQVdfSU1QUkVTU0lPTl9CQVRDSF9TVEFURV9DUkVBVEVEEAESKAokUkFXX0lNUFJFU1NJT05fQkFUQ0hfU1RBVEVfUFJPQ0VTU0VEEAISJQohUkFXX0lNUFJFU1NJT05fQkFUQ0hfU1RBVEVfRkFJTEVEEANCTwotb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5lZHBhZ2dyZWdhdG9yQhxSYXdJbXByZXNzaW9uQmF0Y2hTdGF0ZVByb3RvUAFiBnByb3RvMwr/BApTd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL2VkcGFnZ3JlZ2F0b3IvcmF3X2ltcHJlc3Npb25fdXBsb2FkX21vZGVsX2xpbmVfc3RhdGUucHJvdG8SJndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5lZHBhZ2dyZWdhdG9yKpwDCiFSYXdJbXByZXNzaW9uVXBsb2FkTW9kZWxMaW5lU3RhdGUSNgoyUkFXX0lNUFJFU1NJT05fVVBMT0FEX01PREVMX0xJTkVfU1RBVEVfVU5TUEVDSUZJRUQQABIyCi5SQVdfSU1QUkVTU0lPTl9VUExPQURfTU9ERUxfTElORV9TVEFURV9DUkVBVEVEEAESOQo1UkFXX0lNUFJFU1NJT05fVVBMT0FEX01PREVMX0xJTkVfU1RBVEVfUE9PTF9BU1NJR05JTkcQAhIyCi5SQVdfSU1QUkVTU0lPTl9VUExPQURfTU9ERUxfTElORV9TVEFURV9SQU5LSU5HEAMSMwovUkFXX0lNUFJFU1NJT05fVVBMT0FEX01PREVMX0xJTkVfU1RBVEVfTEFCRUxJTkcQBBI0CjBSQVdfSU1QUkVTU0lPTl9VUExPQURfTU9ERUxfTElORV9TVEFURV9DT01QTEVURUQQBRIxCi1SQVdfSU1QUkVTU0lPTl9VUExPQURfTU9ERUxfTElORV9TVEFURV9GQUlMRUQQBkJZCi1vcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLmVkcGFnZ3JlZ2F0b3JCJlJhd0ltcHJlc3Npb25VcGxvYWRNb2RlbExpbmVTdGF0ZVByb3RvUAFiBnByb3RvMwq6AwpId2ZhL21lYXN1cmVtZW50L2ludGVybmFsL2VkcGFnZ3JlZ2F0b3IvcmF3X2ltcHJlc3Npb25fdXBsb2FkX3N0YXRlLnByb3RvEiZ3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwuZWRwYWdncmVnYXRvcirrAQoYUmF3SW1wcmVzc2lvblVwbG9hZFN0YXRlEisKJ1JBV19JTVBSRVNTSU9OX1VQTE9BRF9TVEFURV9VTlNQRUNJRklFRBAAEicKI1JBV19JTVBSRVNTSU9OX1VQTE9BRF9TVEFURV9DUkVBVEVEEAESJgoiUkFXX0lNUFJFU1NJT05fVVBMT0FEX1NUQVRFX0FDVElWRRACEikKJVJBV19JTVBSRVNTSU9OX1VQTE9BRF9TVEFURV9DT01QTEVURUQQAxImCiJSQVdfSU1QUkVTU0lPTl9VUExPQURfU1RBVEVfRkFJTEVEEARCUAotb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5lZHBhZ2dyZWdhdG9yQh1SYXdJbXByZXNzaW9uVXBsb2FkU3RhdGVQcm90b1ABYgZwcm90bzMKiQQKR3dmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9lZHBhZ2dyZWdhdG9yL3JlcXVpc2l0aW9uX21ldGFkYXRhX3N0YXRlLnByb3RvEiZ3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwuZWRwYWdncmVnYXRvciq7AgoYUmVxdWlzaXRpb25NZXRhZGF0YVN0YXRlEioKJlJFUVVJU0lUSU9OX01FVEFEQVRBX1NUQVRFX1VOU1BFQ0lGSUVEEAASJQohUkVRVUlTSVRJT05fTUVUQURBVEFfU1RBVEVfU1RPUkVEEAESJQohUkVRVUlTSVRJT05fTUVUQURBVEFfU1RBVEVfUVVFVUVEEAISKQolUkVRVUlTSVRJT05fTUVUQURBVEFfU1RBVEVfUFJPQ0VTU0lORxADEigKJFJFUVVJU0lUSU9OX01FVEFEQVRBX1NUQVRFX0ZVTEZJTExFRBAEEiYKIlJFUVVJU0lUSU9OX01FVEFEQVRBX1NUQVRFX1JFRlVTRUQQBRIoCiRSRVFVSVNJVElPTl9NRVRBREFUQV9TVEFURV9XSVRIRFJBV04QBkJQCi1vcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLmVkcGFnZ3JlZ2F0b3JCHVJlcXVpc2l0aW9uTWV0YWRhdGFTdGF0ZVByb3RvUAFiBnByb3RvMwrVAgo/d2ZhL21lYXN1cmVtZW50L2ludGVybmFsL2VkcGFnZ3JlZ2F0b3IvdmlkX2xhYmVsaW5nX3N0YXRlLnByb3RvEiZ3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwuZWRwYWdncmVnYXRvciqXAQoQVmlkTGFiZWxpbmdTdGF0ZRIiCh5WSURfTEFCRUxJTkdfU1RBVEVfVU5TUEVDSUZJRUQQABIeChpWSURfTEFCRUxJTkdfU1RBVEVfQ1JFQVRFRBABEiAKHFZJRF9MQUJFTElOR19TVEFURV9TVUNDRUVERUQQAhIdChlWSURfTEFCRUxJTkdfU1RBVEVfRkFJTEVEEANCSAotb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5lZHBhZ2dyZWdhdG9yQhVWaWRMYWJlbGluZ1N0YXRlUHJvdG9QAWIGcHJvdG8zCotnCiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90bxIPZ29vZ2xlLnByb3RvYnVmIlsKEUZpbGVEZXNjcmlwdG9yU2V0EjgKBGZpbGUYASADKAsyJC5nb29nbGUucHJvdG9idWYuRmlsZURlc2NyaXB0b3JQcm90b1IEZmlsZSoMCIDsyv8BEIHsyv8BIsUFChNGaWxlRGVzY3JpcHRvclByb3RvEhIKBG5hbWUYASABKAlSBG5hbWUSGAoHcGFja2FnZRgCIAEoCVIHcGFja2FnZRIeCgpkZXBlbmRlbmN5GAMgAygJUgpkZXBlbmRlbmN5EisKEXB1YmxpY19kZXBlbmRlbmN5GAogAygFUhBwdWJsaWNEZXBlbmRlbmN5EicKD3dlYWtfZGVwZW5kZW5jeRgLIAMoBVIOd2Vha0RlcGVuZGVuY3kSKwoRb3B0aW9uX2RlcGVuZGVuY3kYDyADKAlSEG9wdGlvbkRlcGVuZGVuY3kSQwoMbWVzc2FnZV90eXBlGAQgAygLMiAuZ29vZ2xlLnByb3RvYnVmLkRlc2NyaXB0b3JQcm90b1ILbWVzc2FnZVR5cGUSQQoJZW51bV90eXBlGAUgAygLMiQuZ29vZ2xlLnByb3RvYnVmLkVudW1EZXNjcmlwdG9yUHJvdG9SCGVudW1UeXBlEkEKB3NlcnZpY2UYBiADKAsyJy5nb29nbGUucHJvdG9idWYuU2VydmljZURlc2NyaXB0b3JQcm90b1IHc2VydmljZRJDCglleHRlbnNpb24YByADKAsyJS5nb29nbGUucHJvdG9idWYuRmllbGREZXNjcmlwdG9yUHJvdG9SCWV4dGVuc2lvbhI2CgdvcHRpb25zGAggASgLMhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zUgdvcHRpb25zEkkKEHNvdXJjZV9jb2RlX2luZm8YCSABKAsyHy5nb29nbGUucHJvdG9idWYuU291cmNlQ29kZUluZm9SDnNvdXJjZUNvZGVJbmZvEhYKBnN5bnRheBgMIAEoCVIGc3ludGF4EjIKB2VkaXRpb24YDiABKA4yGC5nb29nbGUucHJvdG9idWYuRWRpdGlvblIHZWRpdGlvbiL8BgoPRGVzY3JpcHRvclByb3RvEhIKBG5hbWUYASABKAlSBG5hbWUSOwoFZmllbGQYAiADKAsyJS5nb29nbGUucHJvdG9idWYuRmllbGREZXNjcmlwdG9yUHJvdG9SBWZpZWxkEkMKCWV4dGVuc2lvbhgGIAMoCzIlLmdvb2dsZS5wcm90b2J1Zi5GaWVsZERlc2NyaXB0b3JQcm90b1IJZXh0ZW5zaW9uEkEKC25lc3RlZF90eXBlGAMgAygLMiAuZ29vZ2xlLnByb3RvYnVmLkRlc2NyaXB0b3JQcm90b1IKbmVzdGVkVHlwZRJBCgllbnVtX3R5cGUYBCADKAsyJC5nb29nbGUucHJvdG9idWYuRW51bURlc2NyaXB0b3JQcm90b1IIZW51bVR5cGUSWAoPZXh0ZW5zaW9uX3JhbmdlGAUgAygLMi8uZ29vZ2xlLnByb3RvYnVmLkRlc2NyaXB0b3JQcm90by5FeHRlbnNpb25SYW5nZVIOZXh0ZW5zaW9uUmFuZ2USRAoKb25lb2ZfZGVjbBgIIAMoCzIlLmdvb2dsZS5wcm90b2J1Zi5PbmVvZkRlc2NyaXB0b3JQcm90b1IJb25lb2ZEZWNsEjkKB29wdGlvbnMYByABKAsyHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnNSB29wdGlvbnMSVQoOcmVzZXJ2ZWRfcmFuZ2UYCSADKAsyLi5nb29nbGUucHJvdG9idWYuRGVzY3JpcHRvclByb3RvLlJlc2VydmVkUmFuZ2VSDXJlc2VydmVkUmFuZ2USIwoNcmVzZXJ2ZWRfbmFtZRgKIAMoCVIMcmVzZXJ2ZWROYW1lEkEKCnZpc2liaWxpdHkYCyABKA4yIS5nb29nbGUucHJvdG9idWYuU3ltYm9sVmlzaWJpbGl0eVIKdmlzaWJpbGl0eRp6Cg5FeHRlbnNpb25SYW5nZRIUCgVzdGFydBgBIAEoBVIFc3RhcnQSEAoDZW5kGAIgASgFUgNlbmQSQAoHb3B0aW9ucxgDIAEoCzImLmdvb2dsZS5wcm90b2J1Zi5FeHRlbnNpb25SYW5nZU9wdGlvbnNSB29wdGlvbnMaNwoNUmVzZXJ2ZWRSYW5nZRIUCgVzdGFydBgBIAEoBVIFc3RhcnQSEAoDZW5kGAIgASgFUgNlbmQizAQKFUV4dGVuc2lvblJhbmdlT3B0aW9ucxJYChR1bmludGVycHJldGVkX29wdGlvbhjnByADKAsyJC5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvblITdW5pbnRlcnByZXRlZE9wdGlvbhJZCgtkZWNsYXJhdGlvbhgCIAMoCzIyLmdvb2dsZS5wcm90b2J1Zi5FeHRlbnNpb25SYW5nZU9wdGlvbnMuRGVjbGFyYXRpb25CA4gBAlILZGVjbGFyYXRpb24SNwoIZmVhdHVyZXMYMiABKAsyGy5nb29nbGUucHJvdG9idWYuRmVhdHVyZVNldFIIZmVhdHVyZXMSbQoMdmVyaWZpY2F0aW9uGAMgASgOMjguZ29vZ2xlLnByb3RvYnVmLkV4dGVuc2lvblJhbmdlT3B0aW9ucy5WZXJpZmljYXRpb25TdGF0ZToKVU5WRVJJRklFREIDiAECUgx2ZXJpZmljYXRpb24alAEKC0RlY2xhcmF0aW9uEhYKBm51bWJlchgBIAEoBVIGbnVtYmVyEhsKCWZ1bGxfbmFtZRgCIAEoCVIIZnVsbE5hbWUSEgoEdHlwZRgDIAEoCVIEdHlwZRIaCghyZXNlcnZlZBgFIAEoCFIIcmVzZXJ2ZWQSGgoIcmVwZWF0ZWQYBiABKAhSCHJlcGVhdGVkSgQIBBAFIjQKEVZlcmlmaWNhdGlvblN0YXRlEg8KC0RFQ0xBUkFUSU9OEAASDgoKVU5WRVJJRklFRBABKgkI6AcQgICAgAIiwQYKFEZpZWxkRGVzY3JpcHRvclByb3RvEhIKBG5hbWUYASABKAlSBG5hbWUSFgoGbnVtYmVyGAMgASgFUgZudW1iZXISQQoFbGFiZWwYBCABKA4yKy5nb29nbGUucHJvdG9idWYuRmllbGREZXNjcmlwdG9yUHJvdG8uTGFiZWxSBWxhYmVsEj4KBHR5cGUYBSABKA4yKi5nb29nbGUucHJvdG9idWYuRmllbGREZXNjcmlwdG9yUHJvdG8uVHlwZVIEdHlwZRIbCgl0eXBlX25hbWUYBiABKAlSCHR5cGVOYW1lEhoKCGV4dGVuZGVlGAIgASgJUghleHRlbmRlZRIjCg1kZWZhdWx0X3ZhbHVlGAcgASgJUgxkZWZhdWx0VmFsdWUSHwoLb25lb2ZfaW5kZXgYCSABKAVSCm9uZW9mSW5kZXgSGwoJanNvbl9uYW1lGAogASgJUghqc29uTmFtZRI3CgdvcHRpb25zGAggASgLMh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9uc1IHb3B0aW9ucxInCg9wcm90bzNfb3B0aW9uYWwYESABKAhSDnByb3RvM09wdGlvbmFsIrYCCgRUeXBlEg8KC1RZUEVfRE9VQkxFEAESDgoKVFlQRV9GTE9BVBACEg4KClRZUEVfSU5UNjQQAxIPCgtUWVBFX1VJTlQ2NBAEEg4KClRZUEVfSU5UMzIQBRIQCgxUWVBFX0ZJWEVENjQQBhIQCgxUWVBFX0ZJWEVEMzIQBxINCglUWVBFX0JPT0wQCBIPCgtUWVBFX1NUUklORxAJEg4KClRZUEVfR1JPVVAQChIQCgxUWVBFX01FU1NBR0UQCxIOCgpUWVBFX0JZVEVTEAwSDwoLVFlQRV9VSU5UMzIQDRINCglUWVBFX0VOVU0QDhIRCg1UWVBFX1NGSVhFRDMyEA8SEQoNVFlQRV9TRklYRUQ2NBAQEg8KC1RZUEVfU0lOVDMyEBESDwoLVFlQRV9TSU5UNjQQEiJDCgVMYWJlbBISCg5MQUJFTF9PUFRJT05BTBABEhIKDkxBQkVMX1JFUEVBVEVEEAMSEgoOTEFCRUxfUkVRVUlSRUQQAiJjChRPbmVvZkRlc2NyaXB0b3JQcm90bxISCgRuYW1lGAEgASgJUgRuYW1lEjcKB29wdGlvbnMYAiABKAsyHS5nb29nbGUucHJvdG9idWYuT25lb2ZPcHRpb25zUgdvcHRpb25zIqYDChNFbnVtRGVzY3JpcHRvclByb3RvEhIKBG5hbWUYASABKAlSBG5hbWUSPwoFdmFsdWUYAiADKAsyKS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlRGVzY3JpcHRvclByb3RvUgV2YWx1ZRI2CgdvcHRpb25zGAMgASgLMhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRpb25zUgdvcHRpb25zEl0KDnJlc2VydmVkX3JhbmdlGAQgAygLMjYuZ29vZ2xlLnByb3RvYnVmLkVudW1EZXNjcmlwdG9yUHJvdG8uRW51bVJlc2VydmVkUmFuZ2VSDXJlc2VydmVkUmFuZ2USIwoNcmVzZXJ2ZWRfbmFtZRgFIAMoCVIMcmVzZXJ2ZWROYW1lEkEKCnZpc2liaWxpdHkYBiABKA4yIS5nb29nbGUucHJvdG9idWYuU3ltYm9sVmlzaWJpbGl0eVIKdmlzaWJpbGl0eRo7ChFFbnVtUmVzZXJ2ZWRSYW5nZRIUCgVzdGFydBgBIAEoBVIFc3RhcnQSEAoDZW5kGAIgASgFUgNlbmQigwEKGEVudW1WYWx1ZURlc2NyaXB0b3JQcm90bxISCgRuYW1lGAEgASgJUgRuYW1lEhYKBm51bWJlchgCIAEoBVIGbnVtYmVyEjsKB29wdGlvbnMYAyABKAsyIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9uc1IHb3B0aW9ucyK1AQoWU2VydmljZURlc2NyaXB0b3JQcm90bxISCgRuYW1lGAEgASgJUgRuYW1lEj4KBm1ldGhvZBgCIAMoCzImLmdvb2dsZS5wcm90b2J1Zi5NZXRob2REZXNjcmlwdG9yUHJvdG9SBm1ldGhvZBI5CgdvcHRpb25zGAMgASgLMh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zUgdvcHRpb25zSgQIBBAFUgZzdHJlYW0iiQIKFU1ldGhvZERlc2NyaXB0b3JQcm90bxISCgRuYW1lGAEgASgJUgRuYW1lEh0KCmlucHV0X3R5cGUYAiABKAlSCWlucHV0VHlwZRIfCgtvdXRwdXRfdHlwZRgDIAEoCVIKb3V0cHV0VHlwZRI4CgdvcHRpb25zGAQgASgLMh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnNSB29wdGlvbnMSMAoQY2xpZW50X3N0cmVhbWluZxgFIAEoCDoFZmFsc2VSD2NsaWVudFN0cmVhbWluZxIwChBzZXJ2ZXJfc3RyZWFtaW5nGAYgASgIOgVmYWxzZVIPc2VydmVyU3RyZWFtaW5nIq0JCgtGaWxlT3B0aW9ucxIhCgxqYXZhX3BhY2thZ2UYASABKAlSC2phdmFQYWNrYWdlEjAKFGphdmFfb3V0ZXJfY2xhc3NuYW1lGAggASgJUhJqYXZhT3V0ZXJDbGFzc25hbWUSNQoTamF2YV9tdWx0aXBsZV9maWxlcxgKIAEoCDoFZmFsc2VSEWphdmFNdWx0aXBsZUZpbGVzEkQKHWphdmFfZ2VuZXJhdGVfZXF1YWxzX2FuZF9oYXNoGBQgASgIQgIYAVIZamF2YUdlbmVyYXRlRXF1YWxzQW5kSGFzaBI6ChZqYXZhX3N0cmluZ19jaGVja191dGY4GBsgASgIOgVmYWxzZVITamF2YVN0cmluZ0NoZWNrVXRmOBJTCgxvcHRpbWl6ZV9mb3IYCSABKA4yKS5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMuT3B0aW1pemVNb2RlOgVTUEVFRFILb3B0aW1pemVGb3ISHQoKZ29fcGFja2FnZRgLIAEoCVIJZ29QYWNrYWdlEjUKE2NjX2dlbmVyaWNfc2VydmljZXMYECABKAg6BWZhbHNlUhFjY0dlbmVyaWNTZXJ2aWNlcxI5ChVqYXZhX2dlbmVyaWNfc2VydmljZXMYESABKAg6BWZhbHNlUhNqYXZhR2VuZXJpY1NlcnZpY2VzEjUKE3B5X2dlbmVyaWNfc2VydmljZXMYEiABKAg6BWZhbHNlUhFweUdlbmVyaWNTZXJ2aWNlcxIlCgpkZXByZWNhdGVkGBcgASgIOgVmYWxzZVIKZGVwcmVjYXRlZBIuChBjY19lbmFibGVfYXJlbmFzGB8gASgIOgR0cnVlUg5jY0VuYWJsZUFyZW5hcxIqChFvYmpjX2NsYXNzX3ByZWZpeBgkIAEoCVIPb2JqY0NsYXNzUHJlZml4EikKEGNzaGFycF9uYW1lc3BhY2UYJSABKAlSD2NzaGFycE5hbWVzcGFjZRIhCgxzd2lmdF9wcmVmaXgYJyABKAlSC3N3aWZ0UHJlZml4EigKEHBocF9jbGFzc19wcmVmaXgYKCABKAlSDnBocENsYXNzUHJlZml4EiMKDXBocF9uYW1lc3BhY2UYKSABKAlSDHBocE5hbWVzcGFjZRI0ChZwaHBfbWV0YWRhdGFfbmFtZXNwYWNlGCwgASgJUhRwaHBNZXRhZGF0YU5hbWVzcGFjZRIhCgxydWJ5X3BhY2thZ2UYLSABKAlSC3J1YnlQYWNrYWdlEjcKCGZlYXR1cmVzGDIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXRSCGZlYXR1cmVzElgKFHVuaW50ZXJwcmV0ZWRfb3B0aW9uGOcHIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5VbmludGVycHJldGVkT3B0aW9uUhN1bmludGVycHJldGVkT3B0aW9uIjoKDE9wdGltaXplTW9kZRIJCgVTUEVFRBABEg0KCUNPREVfU0laRRACEhAKDExJVEVfUlVOVElNRRADKgkI6AcQgICAgAJKBAgqECtKBAgmECdSFHBocF9nZW5lcmljX3NlcnZpY2VzIvQDCg5NZXNzYWdlT3B0aW9ucxI8ChdtZXNzYWdlX3NldF93aXJlX2Zvcm1hdBgBIAEoCDoFZmFsc2VSFG1lc3NhZ2VTZXRXaXJlRm9ybWF0EkwKH25vX3N0YW5kYXJkX2Rlc2NyaXB0b3JfYWNjZXNzb3IYAiABKAg6BWZhbHNlUhxub1N0YW5kYXJkRGVzY3JpcHRvckFjY2Vzc29yEiUKCmRlcHJlY2F0ZWQYAyABKAg6BWZhbHNlUgpkZXByZWNhdGVkEhsKCW1hcF9lbnRyeRgHIAEoCFIIbWFwRW50cnkSVgomZGVwcmVjYXRlZF9sZWdhY3lfanNvbl9maWVsZF9jb25mbGljdHMYCyABKAhCAhgBUiJkZXByZWNhdGVkTGVnYWN5SnNvbkZpZWxkQ29uZmxpY3RzEjcKCGZlYXR1cmVzGAwgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXRSCGZlYXR1cmVzElgKFHVuaW50ZXJwcmV0ZWRfb3B0aW9uGOcHIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5VbmludGVycHJldGVkT3B0aW9uUhN1bmludGVycHJldGVkT3B0aW9uKgkI6AcQgICAgAJKBAgEEAVKBAgFEAZKBAgGEAdKBAgIEAlKBAgJEAoioQ0KDEZpZWxkT3B0aW9ucxJBCgVjdHlwZRgBIAEoDjIjLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMuQ1R5cGU6BlNUUklOR1IFY3R5cGUSFgoGcGFja2VkGAIgASgIUgZwYWNrZWQSRwoGanN0eXBlGAYgASgOMiQuZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucy5KU1R5cGU6CUpTX05PUk1BTFIGanN0eXBlEhkKBGxhenkYBSABKAg6BWZhbHNlUgRsYXp5Ei4KD3VudmVyaWZpZWRfbGF6eRgPIAEoCDoFZmFsc2VSDnVudmVyaWZpZWRMYXp5EiUKCmRlcHJlY2F0ZWQYAyABKAg6BWZhbHNlUgpkZXByZWNhdGVkEh0KBHdlYWsYCiABKAg6BWZhbHNlQgIYAVIEd2VhaxIoCgxkZWJ1Z19yZWRhY3QYECABKAg6BWZhbHNlUgtkZWJ1Z1JlZGFjdBJLCglyZXRlbnRpb24YESABKA4yLS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zLk9wdGlvblJldGVudGlvblIJcmV0ZW50aW9uEkgKB3RhcmdldHMYEyADKA4yLi5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zLk9wdGlvblRhcmdldFR5cGVSB3RhcmdldHMSVwoQZWRpdGlvbl9kZWZhdWx0cxgUIAMoCzIsLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMuRWRpdGlvbkRlZmF1bHRSD2VkaXRpb25EZWZhdWx0cxI3CghmZWF0dXJlcxgVIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5GZWF0dXJlU2V0UghmZWF0dXJlcxJVCg9mZWF0dXJlX3N1cHBvcnQYFiABKAsyLC5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zLkZlYXR1cmVTdXBwb3J0Ug5mZWF0dXJlU3VwcG9ydBJYChR1bmludGVycHJldGVkX29wdGlvbhjnByADKAsyJC5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvblITdW5pbnRlcnByZXRlZE9wdGlvbhpaCg5FZGl0aW9uRGVmYXVsdBIyCgdlZGl0aW9uGAMgASgOMhguZ29vZ2xlLnByb3RvYnVmLkVkaXRpb25SB2VkaXRpb24SFAoFdmFsdWUYAiABKAlSBXZhbHVlGpYCCg5GZWF0dXJlU3VwcG9ydBJHChJlZGl0aW9uX2ludHJvZHVjZWQYASABKA4yGC5nb29nbGUucHJvdG9idWYuRWRpdGlvblIRZWRpdGlvbkludHJvZHVjZWQSRwoSZWRpdGlvbl9kZXByZWNhdGVkGAIgASgOMhguZ29vZ2xlLnByb3RvYnVmLkVkaXRpb25SEWVkaXRpb25EZXByZWNhdGVkEi8KE2RlcHJlY2F0aW9uX3dhcm5pbmcYAyABKAlSEmRlcHJlY2F0aW9uV2FybmluZxJBCg9lZGl0aW9uX3JlbW92ZWQYBCABKA4yGC5nb29nbGUucHJvdG9idWYuRWRpdGlvblIOZWRpdGlvblJlbW92ZWQiLwoFQ1R5cGUSCgoGU1RSSU5HEAASCAoEQ09SRBABEhAKDFNUUklOR19QSUVDRRACIjUKBkpTVHlwZRINCglKU19OT1JNQUwQABINCglKU19TVFJJTkcQARINCglKU19OVU1CRVIQAiJVCg9PcHRpb25SZXRlbnRpb24SFQoRUkVURU5USU9OX1VOS05PV04QABIVChFSRVRFTlRJT05fUlVOVElNRRABEhQKEFJFVEVOVElPTl9TT1VSQ0UQAiKMAgoQT3B0aW9uVGFyZ2V0VHlwZRIXChNUQVJHRVRfVFlQRV9VTktOT1dOEAASFAoQVEFSR0VUX1RZUEVfRklMRRABEh8KG1RBUkdFVF9UWVBFX0VYVEVOU0lPTl9SQU5HRRACEhcKE1RBUkdFVF9UWVBFX01FU1NBR0UQAxIVChFUQVJHRVRfVFlQRV9GSUVMRBAEEhUKEVRBUkdFVF9UWVBFX09ORU9GEAUSFAoQVEFSR0VUX1RZUEVfRU5VTRAGEhoKFlRBUkdFVF9UWVBFX0VOVU1fRU5UUlkQBxIXChNUQVJHRVRfVFlQRV9TRVJWSUNFEAgSFgoSVEFSR0VUX1RZUEVfTUVUSE9EEAkqCQjoBxCAgICAAkoECAQQBUoECBIQEyKsAQoMT25lb2ZPcHRpb25zEjcKCGZlYXR1cmVzGAEgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXRSCGZlYXR1cmVzElgKFHVuaW50ZXJwcmV0ZWRfb3B0aW9uGOcHIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5VbmludGVycHJldGVkT3B0aW9uUhN1bmludGVycHJldGVkT3B0aW9uKgkI6AcQgICAgAIi0QIKC0VudW1PcHRpb25zEh8KC2FsbG93X2FsaWFzGAIgASgIUgphbGxvd0FsaWFzEiUKCmRlcHJlY2F0ZWQYAyABKAg6BWZhbHNlUgpkZXByZWNhdGVkElYKJmRlcHJlY2F0ZWRfbGVnYWN5X2pzb25fZmllbGRfY29uZmxpY3RzGAYgASgIQgIYAVIiZGVwcmVjYXRlZExlZ2FjeUpzb25GaWVsZENvbmZsaWN0cxI3CghmZWF0dXJlcxgHIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5GZWF0dXJlU2V0UghmZWF0dXJlcxJYChR1bmludGVycHJldGVkX29wdGlvbhjnByADKAsyJC5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvblITdW5pbnRlcnByZXRlZE9wdGlvbioJCOgHEICAgIACSgQIBRAGItgCChBFbnVtVmFsdWVPcHRpb25zEiUKCmRlcHJlY2F0ZWQYASABKAg6BWZhbHNlUgpkZXByZWNhdGVkEjcKCGZlYXR1cmVzGAIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXRSCGZlYXR1cmVzEigKDGRlYnVnX3JlZGFjdBgDIAEoCDoFZmFsc2VSC2RlYnVnUmVkYWN0ElUKD2ZlYXR1cmVfc3VwcG9ydBgEIAEoCzIsLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMuRmVhdHVyZVN1cHBvcnRSDmZlYXR1cmVTdXBwb3J0ElgKFHVuaW50ZXJwcmV0ZWRfb3B0aW9uGOcHIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5VbmludGVycHJldGVkT3B0aW9uUhN1bmludGVycHJldGVkT3B0aW9uKgkI6AcQgICAgAIi1QEKDlNlcnZpY2VPcHRpb25zEjcKCGZlYXR1cmVzGCIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXRSCGZlYXR1cmVzEiUKCmRlcHJlY2F0ZWQYISABKAg6BWZhbHNlUgpkZXByZWNhdGVkElgKFHVuaW50ZXJwcmV0ZWRfb3B0aW9uGOcHIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5VbmludGVycHJldGVkT3B0aW9uUhN1bmludGVycHJldGVkT3B0aW9uKgkI6AcQgICAgAIimQMKDU1ldGhvZE9wdGlvbnMSJQoKZGVwcmVjYXRlZBghIAEoCDoFZmFsc2VSCmRlcHJlY2F0ZWQScQoRaWRlbXBvdGVuY3lfbGV2ZWwYIiABKA4yLy5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucy5JZGVtcG90ZW5jeUxldmVsOhNJREVNUE9URU5DWV9VTktOT1dOUhBpZGVtcG90ZW5jeUxldmVsEjcKCGZlYXR1cmVzGCMgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXRSCGZlYXR1cmVzElgKFHVuaW50ZXJwcmV0ZWRfb3B0aW9uGOcHIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5VbmludGVycHJldGVkT3B0aW9uUhN1bmludGVycHJldGVkT3B0aW9uIlAKEElkZW1wb3RlbmN5TGV2ZWwSFwoTSURFTVBPVEVOQ1lfVU5LTk9XThAAEhMKD05PX1NJREVfRUZGRUNUUxABEg4KCklERU1QT1RFTlQQAioJCOgHEICAgIACIpoDChNVbmludGVycHJldGVkT3B0aW9uEkEKBG5hbWUYAiADKAsyLS5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvbi5OYW1lUGFydFIEbmFtZRIpChBpZGVudGlmaWVyX3ZhbHVlGAMgASgJUg9pZGVudGlmaWVyVmFsdWUSLAoScG9zaXRpdmVfaW50X3ZhbHVlGAQgASgEUhBwb3NpdGl2ZUludFZhbHVlEiwKEm5lZ2F0aXZlX2ludF92YWx1ZRgFIAEoA1IQbmVnYXRpdmVJbnRWYWx1ZRIhCgxkb3VibGVfdmFsdWUYBiABKAFSC2RvdWJsZVZhbHVlEiEKDHN0cmluZ192YWx1ZRgHIAEoDFILc3RyaW5nVmFsdWUSJwoPYWdncmVnYXRlX3ZhbHVlGAggASgJUg5hZ2dyZWdhdGVWYWx1ZRpKCghOYW1lUGFydBIbCgluYW1lX3BhcnQYASACKAlSCG5hbWVQYXJ0EiEKDGlzX2V4dGVuc2lvbhgCIAIoCFILaXNFeHRlbnNpb24ijg8KCkZlYXR1cmVTZXQSkQEKDmZpZWxkX3ByZXNlbmNlGAEgASgOMikuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXQuRmllbGRQcmVzZW5jZUI/iAEBmAEEmAEBogENEghFWFBMSUNJVBiEB6IBDRIISU1QTElDSVQY5weiAQ0SCEVYUExJQ0lUGOgHsgEDCOgHUg1maWVsZFByZXNlbmNlEmwKCWVudW1fdHlwZRgCIAEoDjIkLmdvb2dsZS5wcm90b2J1Zi5GZWF0dXJlU2V0LkVudW1UeXBlQimIAQGYAQaYAQGiAQsSBkNMT1NFRBiEB6IBCRIET1BFThjnB7IBAwjoB1IIZW51bVR5cGUSmAEKF3JlcGVhdGVkX2ZpZWxkX2VuY29kaW5nGAMgASgOMjEuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXQuUmVwZWF0ZWRGaWVsZEVuY29kaW5nQi2IAQGYAQSYAQGiAQ0SCEVYUEFOREVEGIQHogELEgZQQUNLRUQY5weyAQMI6AdSFXJlcGVhdGVkRmllbGRFbmNvZGluZxJ+Cg91dGY4X3ZhbGlkYXRpb24YBCABKA4yKi5nb29nbGUucHJvdG9idWYuRmVhdHVyZVNldC5VdGY4VmFsaWRhdGlvbkIpiAEBmAEEmAEBogEJEgROT05FGIQHogELEgZWRVJJRlkY5weyAQMI6AdSDnV0ZjhWYWxpZGF0aW9uEn4KEG1lc3NhZ2VfZW5jb2RpbmcYBSABKA4yKy5nb29nbGUucHJvdG9idWYuRmVhdHVyZVNldC5NZXNzYWdlRW5jb2RpbmdCJogBAZgBBJgBAaIBFBIPTEVOR1RIX1BSRUZJWEVEGIQHsgEDCOgHUg9tZXNzYWdlRW5jb2RpbmcSggEKC2pzb25fZm9ybWF0GAYgASgOMiYuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXQuSnNvbkZvcm1hdEI5iAEBmAEDmAEGmAEBogEXEhJMRUdBQ1lfQkVTVF9FRkZPUlQYhAeiAQoSBUFMTE9XGOcHsgEDCOgHUgpqc29uRm9ybWF0EqsBChRlbmZvcmNlX25hbWluZ19zdHlsZRgHIAEoDjIuLmdvb2dsZS5wcm90b2J1Zi5GZWF0dXJlU2V0LkVuZm9yY2VOYW1pbmdTdHlsZUJJiAECmAEBmAECmAEDmAEEmAEFmAEGmAEHmAEImAEJogEREgxTVFlMRV9MRUdBQ1kYhAeiAQ4SCVNUWUxFMjAyNBjpB7IBAwjpB1ISZW5mb3JjZU5hbWluZ1N0eWxlErkBChlkZWZhdWx0X3N5bWJvbF92aXNpYmlsaXR5GAggASgOMkUuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXQuVmlzaWJpbGl0eUZlYXR1cmUuRGVmYXVsdFN5bWJvbFZpc2liaWxpdHlCNogBApgBAaIBDxIKRVhQT1JUX0FMTBiEB6IBFRIQRVhQT1JUX1RPUF9MRVZFTBjpB7IBAwjpB1IXZGVmYXVsdFN5bWJvbFZpc2liaWxpdHkaoQEKEVZpc2liaWxpdHlGZWF0dXJlIoEBChdEZWZhdWx0U3ltYm9sVmlzaWJpbGl0eRIlCiFERUZBVUxUX1NZTUJPTF9WSVNJQklMSVRZX1VOS05PV04QABIOCgpFWFBPUlRfQUxMEAESFAoQRVhQT1JUX1RPUF9MRVZFTBACEg0KCUxPQ0FMX0FMTBADEgoKBlNUUklDVBAESggIARCAgICAAiJcCg1GaWVsZFByZXNlbmNlEhoKFkZJRUxEX1BSRVNFTkNFX1VOS05PV04QABIMCghFWFBMSUNJVBABEgwKCElNUExJQ0lUEAISEwoPTEVHQUNZX1JFUVVJUkVEEAMiNwoIRW51bVR5cGUSFQoRRU5VTV9UWVBFX1VOS05PV04QABIICgRPUEVOEAESCgoGQ0xPU0VEEAIiVgoVUmVwZWF0ZWRGaWVsZEVuY29kaW5nEiMKH1JFUEVBVEVEX0ZJRUxEX0VOQ09ESU5HX1VOS05PV04QABIKCgZQQUNLRUQQARIMCghFWFBBTkRFRBACIkkKDlV0ZjhWYWxpZGF0aW9uEhsKF1VURjhfVkFMSURBVElPTl9VTktOT1dOEAASCgoGVkVSSUZZEAISCAoETk9ORRADIgQIARABIlMKD01lc3NhZ2VFbmNvZGluZxIcChhNRVNTQUdFX0VOQ09ESU5HX1VOS05PV04QABITCg9MRU5HVEhfUFJFRklYRUQQARINCglERUxJTUlURUQQAiJICgpKc29uRm9ybWF0EhcKE0pTT05fRk9STUFUX1VOS05PV04QABIJCgVBTExPVxABEhYKEkxFR0FDWV9CRVNUX0VGRk9SVBACIlcKEkVuZm9yY2VOYW1pbmdTdHlsZRIgChxFTkZPUkNFX05BTUlOR19TVFlMRV9VTktOT1dOEAASDQoJU1RZTEUyMDI0EAESEAoMU1RZTEVfTEVHQUNZEAIqBgjoBxCLTioGCItOEJBOKgYIkE4QkU5KBgjnBxDoByLvAwoSRmVhdHVyZVNldERlZmF1bHRzElgKCGRlZmF1bHRzGAEgAygLMjwuZ29vZ2xlLnByb3RvYnVmLkZlYXR1cmVTZXREZWZhdWx0cy5GZWF0dXJlU2V0RWRpdGlvbkRlZmF1bHRSCGRlZmF1bHRzEkEKD21pbmltdW1fZWRpdGlvbhgEIAEoDjIYLmdvb2dsZS5wcm90b2J1Zi5FZGl0aW9uUg5taW5pbXVtRWRpdGlvbhJBCg9tYXhpbXVtX2VkaXRpb24YBSABKA4yGC5nb29nbGUucHJvdG9idWYuRWRpdGlvblIObWF4aW11bUVkaXRpb24a+AEKGEZlYXR1cmVTZXRFZGl0aW9uRGVmYXVsdBIyCgdlZGl0aW9uGAMgASgOMhguZ29vZ2xlLnByb3RvYnVmLkVkaXRpb25SB2VkaXRpb24STgoUb3ZlcnJpZGFibGVfZmVhdHVyZXMYBCABKAsyGy5nb29nbGUucHJvdG9idWYuRmVhdHVyZVNldFITb3ZlcnJpZGFibGVGZWF0dXJlcxJCCg5maXhlZF9mZWF0dXJlcxgFIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5GZWF0dXJlU2V0Ug1maXhlZEZlYXR1cmVzSgQIARACSgQIAhADUghmZWF0dXJlcyK1AgoOU291cmNlQ29kZUluZm8SRAoIbG9jYXRpb24YASADKAsyKC5nb29nbGUucHJvdG9idWYuU291cmNlQ29kZUluZm8uTG9jYXRpb25SCGxvY2F0aW9uGs4BCghMb2NhdGlvbhIWCgRwYXRoGAEgAygFQgIQAVIEcGF0aBIWCgRzcGFuGAIgAygFQgIQAVIEc3BhbhIpChBsZWFkaW5nX2NvbW1lbnRzGAMgASgJUg9sZWFkaW5nQ29tbWVudHMSKwoRdHJhaWxpbmdfY29tbWVudHMYBCABKAlSEHRyYWlsaW5nQ29tbWVudHMSOgoZbGVhZGluZ19kZXRhY2hlZF9jb21tZW50cxgGIAMoCVIXbGVhZGluZ0RldGFjaGVkQ29tbWVudHMqDAiA7Mr/ARCB7Mr/ASLQAgoRR2VuZXJhdGVkQ29kZUluZm8STQoKYW5ub3RhdGlvbhgBIAMoCzItLmdvb2dsZS5wcm90b2J1Zi5HZW5lcmF0ZWRDb2RlSW5mby5Bbm5vdGF0aW9uUgphbm5vdGF0aW9uGusBCgpBbm5vdGF0aW9uEhYKBHBhdGgYASADKAVCAhABUgRwYXRoEh8KC3NvdXJjZV9maWxlGAIgASgJUgpzb3VyY2VGaWxlEhQKBWJlZ2luGAMgASgFUgViZWdpbhIQCgNlbmQYBCABKAVSA2VuZBJSCghzZW1hbnRpYxgFIAEoDjI2Lmdvb2dsZS5wcm90b2J1Zi5HZW5lcmF0ZWRDb2RlSW5mby5Bbm5vdGF0aW9uLlNlbWFudGljUghzZW1hbnRpYyIoCghTZW1hbnRpYxIICgROT05FEAASBwoDU0VUEAESCQoFQUxJQVMQAiqnAgoHRWRpdGlvbhITCg9FRElUSU9OX1VOS05PV04QABITCg5FRElUSU9OX0xFR0FDWRCEBxITCg5FRElUSU9OX1BST1RPMhDmBxITCg5FRElUSU9OX1BST1RPMxDnBxIRCgxFRElUSU9OXzIwMjMQ6AcSEQoMRURJVElPTl8yMDI0EOkHEhcKE0VESVRJT05fMV9URVNUX09OTFkQARIXChNFRElUSU9OXzJfVEVTVF9PTkxZEAISHQoXRURJVElPTl85OTk5N19URVNUX09OTFkQnY0GEh0KF0VESVRJT05fOTk5OThfVEVTVF9PTkxZEJ6NBhIdChdFRElUSU9OXzk5OTk5X1RFU1RfT05MWRCfjQYSEwoLRURJVElPTl9NQVgQ/////wcqVQoQU3ltYm9sVmlzaWJpbGl0eRIUChBWSVNJQklMSVRZX1VOU0VUEAASFAoQVklTSUJJTElUWV9MT0NBTBABEhUKEVZJU0lCSUxJVFlfRVhQT1JUEAJCfgoTY29tLmdvb2dsZS5wcm90b2J1ZkIQRGVzY3JpcHRvclByb3Rvc0gBWi1nb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9kZXNjcmlwdG9ycGL4AQGiAgNHUEKqAhpHb29nbGUuUHJvdG9idWYuUmVmbGVjdGlvbgroAwofZ29vZ2xlL2FwaS9maWVsZF9iZWhhdmlvci5wcm90bxIKZ29vZ2xlLmFwaRogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0b3IucHJvdG8qtgEKDUZpZWxkQmVoYXZpb3ISHgoaRklFTERfQkVIQVZJT1JfVU5TUEVDSUZJRUQQABIMCghPUFRJT05BTBABEgwKCFJFUVVJUkVEEAISDwoLT1VUUFVUX09OTFkQAxIOCgpJTlBVVF9PTkxZEAQSDQoJSU1NVVRBQkxFEAUSEgoOVU5PUkRFUkVEX0xJU1QQBhIVChFOT05fRU1QVFlfREVGQVVMVBAHEg4KCklERU5USUZJRVIQCDpkCg5maWVsZF9iZWhhdmlvchIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYnAggAygOMhkuZ29vZ2xlLmFwaS5GaWVsZEJlaGF2aW9yQgIQAFINZmllbGRCZWhhdmlvckJwCg5jb20uZ29vZ2xlLmFwaUISRmllbGRCZWhhdmlvclByb3RvUAFaQWdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYXBpL2Fubm90YXRpb25zO2Fubm90YXRpb25zogIER0FQSWIGcHJvdG8zCoAECjl3ZmEvbWVhc3VyZW1lbnQvZWRwYWdncmVnYXRvci92MWFscGhhL2VuY3J5cHRlZF9kZWsucHJvdG8SLXdmYS5tZWFzdXJlbWVudC5zZWN1cmVjb21wdXRhdGlvbi5pbXByZXNzaW9ucxofZ29vZ2xlL2FwaS9maWVsZF9iZWhhdmlvci5wcm90byKlAgoMRW5jcnlwdGVkRGVrEhwKB2tla191cmkYASABKAlCA+BBAlIGa2VrVXJpEhkKCHR5cGVfdXJsGAIgASgJUgd0eXBlVXJsEnMKD3Byb3RvYnVmX2Zvcm1hdBgDIAEoDjJKLndmYS5tZWFzdXJlbWVudC5zZWN1cmVjb21wdXRhdGlvbi5pbXByZXNzaW9ucy5FbmNyeXB0ZWREZWsuUHJvdG9idWZGb3JtYXRSDnByb3RvYnVmRm9ybWF0Eh4KCmNpcGhlcnRleHQYBCABKAxSCmNpcGhlcnRleHQiRwoOUHJvdG9idWZGb3JtYXQSHwobUFJPVE9CVUZfRk9STUFUX1VOU1BFQ0lGSUVEEAASCgoGQklOQVJZEAESCAoESlNPThACQkMKLG9yZy53ZmFuZXQubWVhc3VyZW1lbnQuZWRwYWdncmVnYXRvci52MWFscGhhQhFFbmNyeXB0ZWREZWtQcm90b1ABYgZwcm90bzM=';

START BATCH DDL;

ALTER PROTO BUNDLE INSERT (
  `wfa.measurement.internal.edpaggregator.RawImpressionUploadState`,
  `wfa.measurement.internal.edpaggregator.RawImpressionUploadModelLineState`,
  `wfa.measurement.internal.edpaggregator.PoolAssignmentState`,
  `wfa.measurement.internal.edpaggregator.RankerState`,
  `wfa.measurement.internal.edpaggregator.VidLabelingState`,
  `wfa.measurement.internal.edpaggregator.BlobType`,
  `wfa.measurement.securecomputation.impressions.EncryptedDek`
);

-- =============================================================================
-- RawImpressionUpload — top-level parent.
-- One row per EDP impression-upload event (the EDP completes uploading raw
-- impressions and writes a "done" blob, which triggers the
-- VidLabelingDispatcher). All downstream pipeline state cascades from here.
-- =============================================================================
CREATE TABLE RawImpressionUpload (
  DataProviderResourceId STRING(63) NOT NULL,
  RawImpressionUploadId INT64 NOT NULL,
  RawImpressionUploadResourceId STRING(63) NOT NULL,
  CreateRequestId STRING(36),
  DoneBlobUri STRING(MAX) NOT NULL,
  State `wfa.measurement.internal.edpaggregator.RawImpressionUploadState` NOT NULL,
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  UpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY (DataProviderResourceId, RawImpressionUploadId);

CREATE UNIQUE INDEX RawImpressionUploadByResourceId
  ON RawImpressionUpload(DataProviderResourceId, RawImpressionUploadResourceId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadByCreateRequestId
  ON RawImpressionUpload(DataProviderResourceId, CreateRequestId);

CREATE UNIQUE INDEX RawImpressionUploadByDoneBlobUri
  ON RawImpressionUpload(DataProviderResourceId, DoneBlobUri);

CREATE INDEX RawImpressionUploadByCreateTime
  ON RawImpressionUpload(DataProviderResourceId, CreateTime, RawImpressionUploadId);

CREATE INDEX RawImpressionUploadByState
  ON RawImpressionUpload(DataProviderResourceId, State, CreateTime, RawImpressionUploadId);

-- =============================================================================
-- RawImpressionUploadFile — the raw impression files belonging to an upload.
-- =============================================================================
CREATE TABLE RawImpressionUploadFile (
  DataProviderResourceId STRING(63) NOT NULL,
  RawImpressionUploadId INT64 NOT NULL,
  FileId INT64 NOT NULL,
  FileResourceId STRING(63) NOT NULL,
  CreateRequestId STRING(36),
  BlobUri STRING(MAX) NOT NULL,
  SizeBytes INT64 NOT NULL,
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  UpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  DeleteTime TIMESTAMP OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY (DataProviderResourceId, RawImpressionUploadId, FileId),
  INTERLEAVE IN PARENT RawImpressionUpload ON DELETE CASCADE;

CREATE UNIQUE INDEX RawImpressionUploadFileByResourceId
  ON RawImpressionUploadFile(DataProviderResourceId, FileResourceId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadFileByCreateRequestId
  ON RawImpressionUploadFile(
    DataProviderResourceId,
    RawImpressionUploadId,
    CreateRequestId
  );

CREATE UNIQUE INDEX RawImpressionUploadFileByBlobUri
  ON RawImpressionUploadFile(DataProviderResourceId, BlobUri);

-- =============================================================================
-- RawImpressionUploadModelLine — per-model-line pipeline state for an upload.
-- One row per (upload, model line), pre-created by the dispatcher once it
-- resolves which model lines apply to this upload.
-- =============================================================================
CREATE TABLE RawImpressionUploadModelLine (
  DataProviderResourceId STRING(63) NOT NULL,
  RawImpressionUploadId INT64 NOT NULL,
  RawImpressionUploadModelLineId INT64 NOT NULL,
  RawImpressionUploadModelLineResourceId STRING(63) NOT NULL,
  CmmsModelLine STRING(MAX) NOT NULL,
  CreateRequestId STRING(36),
  State `wfa.measurement.internal.edpaggregator.RawImpressionUploadModelLineState` NOT NULL,
  ErrorMessage STRING(MAX),
  PoolOffsets ARRAY<INT64>,
  MaxEventDate DATE,
  EncryptedMergedDek `wfa.measurement.securecomputation.impressions.EncryptedDek`,
  MarkPoolAssigningRequestId STRING(36),
  MarkRankingRequestId STRING(36),
  MarkLabelingRequestId STRING(36),
  MarkCompletedRequestId STRING(36),
  MarkFailedRequestId STRING(36),
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  UpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY (DataProviderResourceId, RawImpressionUploadId, RawImpressionUploadModelLineId),
  INTERLEAVE IN PARENT RawImpressionUpload ON DELETE CASCADE;

CREATE UNIQUE INDEX RawImpressionUploadModelLineByResourceId
  ON RawImpressionUploadModelLine(DataProviderResourceId, RawImpressionUploadModelLineResourceId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadModelLineByCreateRequestId
  ON RawImpressionUploadModelLine(DataProviderResourceId, RawImpressionUploadId, CreateRequestId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadModelLineByMarkPoolAssigningRequestId
  ON RawImpressionUploadModelLine(DataProviderResourceId, RawImpressionUploadId, MarkPoolAssigningRequestId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadModelLineByMarkRankingRequestId
  ON RawImpressionUploadModelLine(DataProviderResourceId, RawImpressionUploadId, MarkRankingRequestId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadModelLineByMarkLabelingRequestId
  ON RawImpressionUploadModelLine(DataProviderResourceId, RawImpressionUploadId, MarkLabelingRequestId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadModelLineByMarkCompletedRequestId
  ON RawImpressionUploadModelLine(DataProviderResourceId, RawImpressionUploadId, MarkCompletedRequestId);

CREATE UNIQUE NULL_FILTERED INDEX RawImpressionUploadModelLineByMarkFailedRequestId
  ON RawImpressionUploadModelLine(DataProviderResourceId, RawImpressionUploadId, MarkFailedRequestId);

CREATE INDEX RawImpressionUploadModelLineByState
  ON RawImpressionUploadModelLine(DataProviderResourceId, State, CreateTime, RawImpressionUploadModelLineId);

-- =============================================================================
-- PoolAssignmentJob — Phase-0 gate.
-- One row per (upload, model line, shard); pre-created by the dispatcher
-- in POOL_ASSIGNMENT_STATE_CREATED state. The "last shard out" of a (upload,
-- model line) flips RawImpressionUploadModelLine state from
-- POOL_ASSIGNING to RANKING and triggers Phase 1.
-- =============================================================================
CREATE TABLE PoolAssignmentJob (
  DataProviderResourceId STRING(63) NOT NULL,
  RawImpressionUploadId INT64 NOT NULL,
  PoolAssignmentJobId INT64 NOT NULL,
  PoolAssignmentJobResourceId STRING(63) NOT NULL,
  CmmsModelLine STRING(MAX) NOT NULL,
  ShardIndex INT64 NOT NULL,
  State `wfa.measurement.internal.edpaggregator.PoolAssignmentState` NOT NULL,
  EncryptedDek `wfa.measurement.securecomputation.impressions.EncryptedDek`,
  ErrorMessage STRING(MAX),
  CreateRequestId STRING(36),
  MarkSucceededRequestId STRING(36),
  MarkFailedRequestId STRING(36),
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  UpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY (DataProviderResourceId, RawImpressionUploadId, PoolAssignmentJobId),
  INTERLEAVE IN PARENT RawImpressionUpload ON DELETE CASCADE;

CREATE UNIQUE INDEX PoolAssignmentJobByResourceId
  ON PoolAssignmentJob(DataProviderResourceId, PoolAssignmentJobResourceId);

CREATE UNIQUE NULL_FILTERED INDEX PoolAssignmentJobByCreateRequestId
  ON PoolAssignmentJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    CreateRequestId
  );

CREATE UNIQUE NULL_FILTERED INDEX PoolAssignmentJobByMarkSucceededRequestId
  ON PoolAssignmentJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    MarkSucceededRequestId
  );

CREATE UNIQUE NULL_FILTERED INDEX PoolAssignmentJobByMarkFailedRequestId
  ON PoolAssignmentJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    MarkFailedRequestId
  );

CREATE INDEX PoolAssignmentJobByState
  ON PoolAssignmentJob(DataProviderResourceId, State, CreateTime, PoolAssignmentJobId);

CREATE UNIQUE INDEX PoolAssignmentJobByModelLineShard
  ON PoolAssignmentJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    CmmsModelLine,
    ShardIndex
  ) STORING (State);

-- =============================================================================
-- RankerJob — Phase-1 gate.
-- One row per (upload, model line, ranker job); pre-created by the Phase-0
-- last-out trigger in RANKER_CREATED state. The "last ranker job out" of a
-- (upload, model line) flips RawImpressionUploadModelLine state from
-- RANKING to LABELING and triggers Phase 2.
-- =============================================================================
CREATE TABLE RankerJob (
  DataProviderResourceId STRING(63) NOT NULL,
  RawImpressionUploadId INT64 NOT NULL,
  RankerJobId INT64 NOT NULL,
  RankerJobResourceId STRING(63) NOT NULL,
  CmmsModelLine STRING(MAX) NOT NULL,
  PoolOffsets ARRAY<INT64> NOT NULL,
  State `wfa.measurement.internal.edpaggregator.RankerState` NOT NULL,
  ErrorMessage STRING(MAX),
  CreateRequestId STRING(36),
  MarkSucceededRequestId STRING(36),
  MarkFailedRequestId STRING(36),
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  UpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY (DataProviderResourceId, RawImpressionUploadId, RankerJobId),
  INTERLEAVE IN PARENT RawImpressionUpload ON DELETE CASCADE;

CREATE UNIQUE INDEX RankerJobByResourceId
  ON RankerJob(DataProviderResourceId, RankerJobResourceId);

CREATE UNIQUE NULL_FILTERED INDEX RankerJobByCreateRequestId
  ON RankerJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    CreateRequestId
  );

CREATE UNIQUE NULL_FILTERED INDEX RankerJobByMarkSucceededRequestId
  ON RankerJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    MarkSucceededRequestId
  );

CREATE UNIQUE NULL_FILTERED INDEX RankerJobByMarkFailedRequestId
  ON RankerJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    MarkFailedRequestId
  );

CREATE INDEX RankerJobByState
  ON RankerJob(DataProviderResourceId, State, CreateTime, RankerJobId);

CREATE INDEX RankerJobByModelLine
  ON RankerJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    CmmsModelLine
  ) STORING (State);

-- =============================================================================
-- RankIndexBlob — pointer to the rank-index blobs in GCS, with their DEKs.
-- Two rows per (upload, model line, subpool): one DAY_ONLY and one SNAPSHOT.
-- Snapshots are replaced each upload; day-only blobs persist until aged out
-- by the retention policy.
-- =============================================================================
CREATE TABLE RankIndexBlob (
  DataProviderResourceId STRING(63) NOT NULL,
  RawImpressionUploadId INT64 NOT NULL,
  RankIndexBlobId INT64 NOT NULL,
  RankIndexBlobResourceId STRING(63) NOT NULL,
  CreateRequestId STRING(36),
  CmmsModelLine STRING(MAX) NOT NULL,
  BlobType `wfa.measurement.internal.edpaggregator.BlobType` NOT NULL,
  PoolOffset INT64 NOT NULL,
  BlobUri STRING(MAX) NOT NULL,
  EncryptedDek `wfa.measurement.securecomputation.impressions.EncryptedDek` NOT NULL,
  MaxEventDate DATE NOT NULL,
  -- SHA-256 hash of the blob's plaintext; validated by readers per design doc
  -- (Lifecycle Management § Corrupted cumulative blob).
  BlobChecksum BYTES(32) NOT NULL,
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  UpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  DeleteTime TIMESTAMP OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY (DataProviderResourceId, RawImpressionUploadId, RankIndexBlobId),
  INTERLEAVE IN PARENT RawImpressionUpload ON DELETE CASCADE;

CREATE UNIQUE INDEX RankIndexBlobByResourceId
  ON RankIndexBlob(DataProviderResourceId, RankIndexBlobResourceId);

CREATE UNIQUE NULL_FILTERED INDEX RankIndexBlobByCreateRequestId
  ON RankIndexBlob(
    DataProviderResourceId,
    RawImpressionUploadId,
    CreateRequestId
  );

CREATE UNIQUE INDEX RankIndexBlobByNaturalKey
  ON RankIndexBlob(
    DataProviderResourceId,
    RawImpressionUploadId,
    CmmsModelLine,
    BlobType,
    PoolOffset
  );

CREATE INDEX RankIndexBlobByMaxEventDate
  ON RankIndexBlob(DataProviderResourceId, CmmsModelLine, BlobType, MaxEventDate);

CREATE INDEX RankIndexBlobByUploadAndType
  ON RankIndexBlob(DataProviderResourceId, CmmsModelLine, BlobType, RawImpressionUploadId);

CREATE UNIQUE INDEX RankIndexBlobByBlobUri
  ON RankIndexBlob(DataProviderResourceId, BlobUri);


-- =============================================================================
-- VidLabelingJob — Phase-2 gate.
-- One row per (upload, file batch). Each job labels a batch of files
-- (RawImpressionUploadFiles) for one or more model lines (CmmsModelLines):
--   - When the model lines do NOT require memoization, a single job can batch
--     multiple files AND multiple model lines together (CmmsModelLines holds
--     the set).
--   - When a model line DOES require memoization, the job covers exactly one
--     model line (CmmsModelLines has a single entry) but still multiple files.
-- Pre-created by the Phase-1 last-RankerJob-out when transitioning
-- RawImpressionUploadModelLine from RANKING to LABELING.
-- A model line transitions LABELING -> COMPLETED once every VidLabelingJob
-- whose CmmsModelLines contains it has succeeded; the job that completes the
-- last such model line triggers DataAvailabilitySync.
-- =============================================================================
CREATE TABLE VidLabelingJob (
  DataProviderResourceId STRING(63) NOT NULL,
  RawImpressionUploadId INT64 NOT NULL,
  VidLabelingJobId INT64 NOT NULL,
  VidLabelingJobResourceId STRING(63) NOT NULL,
  CmmsModelLines ARRAY<STRING(MAX)> NOT NULL,
  RawImpressionUploadFiles ARRAY<STRING(MAX)> NOT NULL,
  State `wfa.measurement.internal.edpaggregator.VidLabelingState` NOT NULL,
  ErrorMessage STRING(MAX),
  CreateRequestId STRING(36),
  MarkSucceededRequestId STRING(36),
  MarkFailedRequestId STRING(36),
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  UpdateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY (DataProviderResourceId, RawImpressionUploadId, VidLabelingJobId),
  INTERLEAVE IN PARENT RawImpressionUpload ON DELETE CASCADE;

CREATE UNIQUE INDEX VidLabelingJobByResourceId
  ON VidLabelingJob(DataProviderResourceId, VidLabelingJobResourceId);

CREATE UNIQUE NULL_FILTERED INDEX VidLabelingJobByCreateRequestId
  ON VidLabelingJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    CreateRequestId
  );

CREATE UNIQUE NULL_FILTERED INDEX VidLabelingJobByMarkSucceededRequestId
  ON VidLabelingJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    MarkSucceededRequestId
  );

CREATE UNIQUE NULL_FILTERED INDEX VidLabelingJobByMarkFailedRequestId
  ON VidLabelingJob(
    DataProviderResourceId,
    RawImpressionUploadId,
    MarkFailedRequestId
  );

CREATE INDEX VidLabelingJobByState
  ON VidLabelingJob(DataProviderResourceId, State, CreateTime, VidLabelingJobId);

RUN BATCH;
