# proto-file: wfa/measurement/reporting/v2alpha/reporting_set.proto
# proto-message: ReportingSet

# name: "measurementConsumers/VCTqwV_vFXw/reportingSets/G7OUlGMoAe8"

display_name: "incremental_reach_for_A_age_18+_reporting_set"

# For age 18-34, 35-54, 55+
filter: "event_template.age==18_34 || event_template.age==35_54 || event_template.age==55+"

type {
  composite_reporting_set {
    expression {
      operation: "DIFFERENCE"
      lhs: "measurementConsumers/VCTqwV_vFXw/reportingSets/union_all-ID"
      rhs: "measurementConsumers/VCTqwV_vFXw/reportingSets/union_all_but_A-ID"
    }
  }
}