# proto-file: wfa/measurement/reporting/v2alpha/reporting_set.proto
# proto-message: ReportingSet

# name: "measurementConsumers/VCTqwV_vFXw/reportingSets/union_all_but_A-ID"

display_name: "union_all_but_A"

type {
  primitive_reporting_set {
    # Pub B
    event_groups: "measurementConsumers/VCTqwV_vFXw/dataProviders/HlFzHaAQ5pA/eventGroups/Gc-TZIA98BY"
    # Pub C
    event_groups: "measurementConsumers/VCTqwV_vFXw/dataProviders/JugGwqAQ5wQ/eventGroups/RKIFv4A95-Q"
  }
}