-- liquibase formatted sql

-- Copyright 2026 The Cross-Media Measurement Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- changeset jojijacob:33
-- comment: Create ClientAccounts lookup table for EventGroupSync MC ID lookup.

START BATCH DDL;

-- ClientAccounts maps a DataProvider's client account reference ID to a MeasurementConsumer.
--
-- This is a standalone lookup table (not interleaved) that enables the EDP
-- Aggregator's EventGroupSync to resolve MeasurementConsumer IDs from client account
-- references provided by DataProviders.
--
-- The canonical resource name uses MeasurementConsumer as the parent:
--   measurementConsumers/{mc}/clientAccounts/{client_account}
--
-- But the resource is also accessible via DataProvider parent for lookups:
--   dataProviders/{dp}/clientAccounts/{client_account}
CREATE TABLE ClientAccounts (
  -- Internal FK to MeasurementConsumers table.
  -- Part of primary key to reflect canonical parent, even though not interleaved.
  MeasurementConsumerId INT64 NOT NULL,

  ClientAccountId INT64 NOT NULL,

  -- Generated by the system, exposed in APIs.
  -- Unique per DataProvider and per MeasurementConsumer, not globally unique.
  ExternalClientAccountId INT64 NOT NULL,

  -- Internal FK to DataProviders table.
  DataProviderId INT64 NOT NULL,

  -- Reference ID for the account in the DataProvider's ecosystem.
  -- Provided by the operator, used for lookups by EventGroupSync.
  ClientAccountReferenceId STRING(36) NOT NULL,

  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),

  FOREIGN KEY (MeasurementConsumerId) REFERENCES MeasurementConsumers(MeasurementConsumerId),
  FOREIGN KEY (DataProviderId) REFERENCES DataProviders(DataProviderId),
) PRIMARY KEY (MeasurementConsumerId, ClientAccountId);

-- For public API lookups by external ID within a MeasurementConsumer.
CREATE UNIQUE INDEX ClientAccountsByMeasurementConsumerAndExternalId
  ON ClientAccounts(MeasurementConsumerId, ExternalClientAccountId);

-- For public API lookups by external ID within a DataProvider.
CREATE UNIQUE INDEX ClientAccountsByDataProviderAndExternalId
  ON ClientAccounts(DataProviderId, ExternalClientAccountId);

-- For EventGroupSync lookups: given a DataProvider and reference ID, find the ClientAccount.
-- This is the primary lookup pattern for resolving client_account -> MeasurementConsumer.
CREATE UNIQUE INDEX ClientAccountsByDataProviderAndReferenceId
  ON ClientAccounts(DataProviderId, ClientAccountReferenceId);

RUN BATCH;
