-- liquibase formatted sql

-- Copyright 2025 The Cross-Media Measurement Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- changeset sanjayvas:27 dbms:cloudspanner
-- comment: Create sharded index on Requisitions by UpdateTime.

START BATCH DDL;

ALTER TABLE Requisitions
ADD COLUMN RequisitionIdentity INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE);

ALTER TABLE Requisitions
ADD COLUMN RequisitionIndexShardId INT64 NOT NULL AS (ABS(MOD(RequisitionIdentity, 128))) STORED;

CREATE INDEX RequisitionsByUpdateTime ON Requisitions(RequisitionIndexShardId, UpdateTime, RequisitionIdentity);

RUN BATCH;
