-- liquibase formatted sql

-- Copyright 2026 The Cross-Media Measurement Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- changeset jojijacob:create-ad-accounts-table dbms:cloudspanner
-- comment: Create AdAccounts lookup table for EventGroupSync MC ID lookup.

START BATCH DDL;

-- AdAccounts maps a DataProvider's ad account reference ID to a MeasurementConsumer.
--
-- This is a standalone lookup table (not interleaved) that enables the EDP
-- Aggregator's EventGroupSync to resolve MeasurementConsumer IDs from ad account
-- references provided by DataProviders.
--
-- The canonical resource name uses MeasurementConsumer as the parent:
--   measurementConsumers/{mc}/adAccounts/{ad_account}
--
-- But the resource is also accessible via DataProvider parent for lookups:
--   dataProviders/{dp}/adAccounts/{ad_account}
CREATE TABLE AdAccounts (
  AdAccountId INT64 NOT NULL,

  -- Generated by the system, exposed in APIs.
  ExternalAdAccountId INT64 NOT NULL,

  -- Internal FK to MeasurementConsumers table.
  MeasurementConsumerId INT64 NOT NULL,

  -- Internal FK to DataProviders table.
  DataProviderId INT64 NOT NULL,

  -- Reference ID for the account in the DataProvider's ecosystem.
  -- Provided by the operator, used for lookups by EventGroupSync.
  AdAccountReferenceId STRING(MAX) NOT NULL,

  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),

  FOREIGN KEY (MeasurementConsumerId) REFERENCES MeasurementConsumers(MeasurementConsumerId),
  FOREIGN KEY (DataProviderId) REFERENCES DataProviders(DataProviderId),
) PRIMARY KEY (AdAccountId);

-- For public API lookups by external ID.
CREATE UNIQUE INDEX AdAccountsByExternalId
  ON AdAccounts(ExternalAdAccountId);

-- For EventGroupSync lookups: given a DataProvider and reference ID, find the AdAccount.
-- This is the primary lookup pattern for resolving ad_account -> MeasurementConsumer.
CREATE UNIQUE INDEX AdAccountsByDataProviderAndReferenceId
  ON AdAccounts(DataProviderId, AdAccountReferenceId);

-- For listing all AdAccounts for a MeasurementConsumer.
CREATE INDEX AdAccountsByMeasurementConsumerId
  ON AdAccounts(MeasurementConsumerId);

-- For listing all AdAccounts for a DataProvider.
CREATE INDEX AdAccountsByDataProviderId
  ON AdAccounts(DataProviderId);

RUN BATCH;
