# proto-file: src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto
# proto-message: ExchangeWorkflow

################################################################################
# This is an example protocol for a Panel Match exchange.                      #
#                                                                              #
# * For details on each field, see the ExchangeWorkflow message definition.    #
# * Each step is run on hardware controlled by the `party` given in each step. #
################################################################################

# EDP provides a pepper used in generating AES keys.
steps {
  step_id: "generate-hkdf-pepper"
  party: DATA_PROVIDER

  input_step {}

  shared_output_labels { key: "input" value: "hkdf-pepper" }
}

# EDP provides a pepper used in hashing encrypted identifiers.
steps {
  step_id: "generate-identifier-hash-pepper"
  party: DATA_PROVIDER

  input_step {}

  shared_output_labels { key: "input" value: "identifier-hash-pepper" }
}

# MP provides private key as input.
steps {
  step_id: "mp-input-commutative-deterministic-key"
  party: MODEL_PROVIDER

  input_step {}

  private_output_labels {
    key: "input"
    value: "mp-commutative-deterministic-key"
  }
}

# MP provides unencrypted joinkeys as input.
steps {
  step_id: "mp-input-raw-joinkeys"
  party: MODEL_PROVIDER

  input_step {}

  private_output_labels { key: "input" value: "raw-joinkeys" }
}

# EDP provides private key as input.
steps {
  step_id: "edp-input-commutative-deterministic-key"
  party: DATA_PROVIDER

  input_step {}

  private_output_labels {
    key: "input"
    value: "edp-commutative-deterministic-key"
  }
}

# EDP provides symmetrically encrypted event data as input.
steps {
  step_id: "edp-input-encrypted-event-data"
  party: DATA_PROVIDER

  input_step {}

  shared_output_labels { key: "input" value: "encrypted-event-data" }
}

# EDP provides the previous protocol execution's blinded joinkeys as input.
#
# These are used to validate that the new single-blinded joinkeys derived in
# this protocol don't deviate too much.
steps {
  step_id: "edp-input-previous-single-blinded-joinkeys"
  party: DATA_PROVIDER

  input_step {}

  private_output_labels {
    key: "input"
    value: "previous-single-blinded-joinkeys"
  }
}

# MP wraps their panelist identifiers in a layer of deterministic commutative
# encryption.
steps {
  step_id: "single-blind"
  party: MODEL_PROVIDER

  encrypt_step {}

  private_input_labels { key: "data" value: "raw-joinkeys" }
  private_input_labels {
    key: "crypto-key"
    value: "mp-commutative-deterministic-key"
  }

  private_output_labels { key: "output" value: "single-blinded-joinkeys" }

  shared_output_labels { key: "output" value: "single-blinded-joinkeys" }
}

# EDP validates that the single-encrypted panelist identifiers are sufficiently
# similar to the previous execution's single-encrypted panelist identifiers.
steps {
  step_id: "validate-single-blinded-joinkeys"
  party: DATA_PROVIDER

  # Ensure there are are between 1000 and 10,000 panelists and 99% of them
  # appeared in the previous protocol.
  intersect_and_validate_step {
    max_size: 10000
    minimum_overlap: 0.99
  }

  private_input_labels {
    key: "previous-data"
    value: "previous-single-blinded-joinkeys"
  }

  shared_input_labels { key: "current-data" value: "single-blinded-joinkeys" }

  # Outputs "current-data" as a local copy for long-term auditing storage.
  private_output_labels {
    key: "output"
    value: "single-blinded-joinkeys-edp-copy"
  }
}

# EDP wraps the single-encrypted panelist identifiers in another layer of
# commutative deterministic encryption.
steps {
  step_id: "double-blind"
  party: DATA_PROVIDER

  reencrypt_step {}

  private_input_labels { key: "data" value: "single-blinded-joinkeys-edp-copy" }
  private_input_labels {
    key: "crypto-key"
    value: "edp-commutative-deterministic-key"
  }

  private_output_labels { key: "output" value: "double-blinded-joinkeys" }

  shared_output_labels { key: "output" value: "double-blinded-joinkeys" }
}

# MP removes their layer of commutative, deterministic encryption.
steps {
  step_id: "prepare-lookup-keys"
  party: MODEL_PROVIDER

  decrypt_step {}

  private_input_labels {
    key: "crypto-key"
    value: "mp-commutative-deterministic-key"
  }

  shared_input_labels { key: "data" value: "double-blinded-joinkeys" }

  private_output_labels { key: "output" value: "lookup-keys" }
}

# MP encrypts their queries.
steps {
  step_id: "prepare-event-lookup-queries"
  party: MODEL_PROVIDER

  build_private_membership_queries_step {
    serialized_parameters: "..."
  }

  private_input_labels { key: "identifiers" value: "raw-joinkeys" }
  private_input_labels { key: "identifiers" value: "lookup-keys" }

  private_output_labels { key: "serialized-rlwe-private-key" value: "serialized-rlwe-private-key" }
  private_output_labels { key: "query-decryption-keys" value: "query-decryption-keys" }

  shared_output_labels { key: "encrypted-queries" value: "encrypted-queries" }
  shared_output_labels { key: "serialized-rlwe-public-key" value: "serialized-rlwe-public-key" }
}

# EDP executes private membership queries
steps {
  step_id: "execute-private-membership-queries"
  party: DATA_PROVIDER

  execute_private_membership_queries_step {
    serialized_parameters: "..."
  }

  private_input_labels { key: "event-data" value: "event-data" }

  shared_input_labels { key: "encrypted-queries" value: "encrypted-queries" }
  shared_input_labels { key: "serialized-rlwe-public-key" value: "serialized-rlwe-public-key" }

  shared_output_labels { key: "encrypted-results" value: "encrypted-results" }
}

# MP decrypts the results
steps {
  step_id: "decrypt-private-membership-results"
  party: MODEL_PROVIDER

  decrypt_private_membership_query_results_step {
    serialized_parameters: "..."
  }

  private_input_labels { key: "query-decryption-keys" value: "query-decryption-keys" }
  private_input_labels { key: "serialized-rlwe-private-key" value: "serialized-rlwe-private-key" }

  shared_input_labels { key: "encrypted-results" value: "encrypted-results" }
  shared_input_labels { key: "serialized-rlwe-public-key" value: "serialized-rlwe-public-key" }

  private_output_labels { key: "results" value: "results" }
}
