# proto-file: src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto
# proto-message: ExchangeWorkflow

################################################################################
# This is an example protocol for a Panel Match exchange.                      #
#                                                                              #
# * For details on each field, see the ExchangeWorkflow message definition.    #
# * Each step is run on hardware controlled by the `party` given in each step. #
################################################################################

# EDP provides a previously generated pepper used in generating AES keys.
steps {
  step_id: "input-hkdf-pepper"
  party: DATA_PROVIDER

  input_step {}

  output_labels { key: "input" value: "edp-hkdf-pepper" }
}

# EDP exports its hkdf pepper.
steps {
  step_id: "export-hkdf-pepper"
  party: DATA_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "hkdf-pepper" value: "edp-hkdf-pepper" }
  output_labels { key: "hkdf-pepper" value: "hkdf-pepper" }
}

# MP imports EDP's hkdf pepper.
steps {
  step_id: "import-hkdf-pepper"
  party: MODEL_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "hkdf-pepper" value: "hkdf-pepper" }
  output_labels { key: "hkdf-pepper" value: "mp-hkdf-pepper" }
}

# EDP provides a previously generated identifier hash pepper used in hashing encrypted identifiers.
steps {
  step_id: "input-identifier-hash-pepper"
  party: DATA_PROVIDER

  input_step {}

  output_labels { key: "input" value: "edp-identifier-hash-pepper" }
}

# EDP exports its identifier hash pepper.
steps {
  step_id: "export-identifier-hash-pepper"
  party: DATA_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "identifier-hash-pepper" value: "edp-identifier-hash-pepper" }
  output_labels { key: "identifier-hash-pepper" value: "identifier-hash-pepper" }
}

# MP imports EDP's identifier hash pepper.
steps {
  step_id: "import-identifier-hash-pepper"
  party: MODEL_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "identifier-hash-pepper" value: "identifier-hash-pepper" }
  output_labels { key: "identifier-hash-pepper" value: "mp-identifier-hash-pepper" }
}

# MP generates private commutative deterministic key.
steps {
  step_id: "generate-commutative-deterministic-key"
  party: MODEL_PROVIDER

  generate_commutative_deterministic_key_step {}

  output_labels { key: "input" value: "mp-commutative-deterministic-key" }
}

# MP provides unencrypted join keys
steps {
  step_id: "input-plaintext-join-keys"
  party: MODEL_PROVIDER

  input_step {}

  output_labels { key: "input" value: "mp-plaintext-join-keys" }
}

# EDP provides previously generated private key as input.
steps {
  step_id: "input-commutative-deterministic-key"
  party: DATA_PROVIDER

  input_step {}

  output_labels { key: "input" value: "edp-commutative-deterministic-key" }
}

# EDP provides the previous protocol execution's single blinded joinkeys as input.
#
# These are used to validate that the new single-blinded joinkeys derived in
# this protocol don't deviate too much.
steps {
  step_id: "input-previous-single-blinded-join-keys"
  party: DATA_PROVIDER

  copy_from_previous_exchange_step {}

  input_labels { key: "input" value: "edp-single-blinded-join-keys-audit-trail" }
  output_labels { key: "output" value: "edp-previous-single-blinded-join-keys" }
}

# MP wraps their hashed join keys in a layer of deterministic commutative
# encryption.
steps {
  step_id: "single-blind"
  party: MODEL_PROVIDER

  encrypt_step {}

  input_labels { key: "data" value: "mp-plaintext-join-keys" }
  input_labels { key: "crypto-key" value: "mp-commutative-deterministic-key" }

  output_labels { key: "output" value: "mp-single-blinded-join-keys" }
}

steps {
  step_id: "export-single-blinded-join-keys"
  party: MODEL_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "single-blinded-join-keys" value: "mp-single-blinded-join-keys" }
  output_labels { key: "single-blinded-join-keys" value: "single-blinded-join-keys" }
}

steps {
  step_id: "import-single-blinded-join-keys"
  party: DATA_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "single-blinded-join-keys" value: "single-blinded-join-keys" }
  output_labels { key: "single-blinded-join-keys" value: "edp-single-blinded-join-keys" }
}

# EDP validates that the single-encrypted join keys are sufficiently
# similar to the previous execution's single-encrypted join keys.
steps {
  step_id: "validate-single-blinded-join-keys"
  party: DATA_PROVIDER

  # Ensure there are are between 1000 and 10,000 panelists and 99% of them
  # appeared in the previous protocol.
  intersect_and_validate_step {
    max_size: 10000
    maximum_new_items_allowed: 100
  }

  input_labels { key: "previous-data" value: "edp-previous-single-blinded-join-keys" }
  input_labels { key: "current-data" value: "edp-single-blinded-join-keys" }

  # Outputs "current-data" as a local copy for long-term auditing storage.
  output_labels { key: "output" value: "edp-single-blinded-joinkeys-audit-trail" }
}

# EDP wraps the single-encrypted join keys in another layer of
# commutative deterministic encryption.
steps {
  step_id: "double-blind"
  party: DATA_PROVIDER

  reencrypt_step {}

  input_labels { key: "data" value: "edp-single-blinded-joinkeys-copy" }
  input_labels { key: "crypto-key" value: "edp-commutative-deterministic-key" }

  output_labels { key: "output" value: "edp-double-blinded-join-keys" }
}

steps {
  step_id: "export-double-blinded-join-keys"
  party: DATA_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "double-blinded-join-keys" value: "edp-double-blinded-join-keys" }
  output_labels { key: "double-blinded-join-keys" value: "double-blinded-join-keys" }
}

steps {
  step_id: "import-double-blinded-join-keys"
  party: MODEL_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "double-blinded-join-keys" value: "double-blinded-join-keys" }
  output_labels { key: "double-blinded-join-keys" value: "mp-double-blinded-join-keys" }
}

# MP removes their layer of commutative, deterministic encryption.
steps {
  step_id: "remove-blinding"
  party: MODEL_PROVIDER

  decrypt_step {}

  input_labels { key: "crypto-key" value: "mp-commutative-deterministic-key" }
  input_labels { key: "data" value: "mp-double-blinded-join-keys" }

  output_labels { key: "output" value: "mp-decrypted-join-keys" }
}

# MP generates lookup keys from EDP's identifier hash pepper and decrypted join keys.
steps {
  step_id: "generate-lookup-keys-step"
  party: MODEL_PROVIDER

  generate_join_keys_step {}

  input_labels { key: "decrypted-join-keys" value: "mp-decrypted-join-keys" }
  input_labels { key: "pepper" value: "mp-identifier-hash-pepper" }

  output_labels { key: "join-keys" value: "mp-lookup-keys" }
}

# MP generates rlwe private and public keys.
steps {
  step_id: "generate-serialized-rlwe-keys"
  party: MODEL_PROVIDER

  generate_serialized_rlwe_keys_step {
    serialized_parameters: "..."
  }

  output_labels { key: "serialized-rlwe-private-key" value: "mp-serialized-rlwe-private-key" }
  output_labels { key: "serialized-rlwe-public-key" value: "mp-serialized-rlwe-public-key" }
}

# MP encrypts their queries.
steps {
  step_id: "prepare-event-lookup-queries"
  party: MODEL_PROVIDER

  build_private_membership_queries_step {
    serialized_parameters: "..."
  }

  input_labels { key: "lookup-keys" value: "mp-lookup-keys" }
  input_labels { key: "plaintext-join-keys" value: "mp-plaintext-join-keys" }
  input_labels { key: "serialized-rlwe-private-key" value: "mp-serialized-rlwe-private-key" }
  input_labels { key: "serialized-rlwe-public-key" value: "mp-serialized-rlwe-public-key" }

  output_labels { key: "query-to-join-keys-map" value: "mp-query-to-join-keys-map" }
  output_labels { key: "encrypted-queries" value: "mp-encrypted-queries" }
}

# MP exports its rlwe public key
steps {
  step_id: "export-serialized-rlwe-public-key"
  party: MODEL_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "serialized-rlwe-public-key" value: "mp-serialized-rlwe-public-key" }
  output_labels { key: "serialized-rlwe-public-key" value: "serialized-rlwe-public-key" }
}

# EDP imports MP's rlwe public key.
steps {
  step_id: "import-serialized-rlwe-public-key"
  party: DATA_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "serialized-rlwe-public-key" value: "serialized-rlwe-public-key" }
  output_labels { key: "serialized-rlwe-public-key" value: "edp-serialized-rlwe-public-key" }
}

# MP exports their encrypted queries.
steps {
  step_id: "export-encrypted-queries"
  party: MODEL_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "encrypted-queries" value: "mp-encrypted-queries" }
  output_labels { key: "encrypted-queries" value: "encrypted-queries" }
}

# EDP imports MP's encrypted queries.
steps {
  step_id: "import-encrypted-queries"
  party: DATA_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "encrypted-queries" value: "encrypted-queries" }
  output_labels { key: "encrypted-queries" value: "edp-encrypted-queries" }
}

# EDP provides symmetrically encrypted compressed event data as input.
steps {
  step_id: "input-encrypted-event-data"
  party: DATA_PROVIDER

  input_step {}

  output_labels { key: "input" value: "edp-encrypted-event-data" }
}

# EDP provides dictionary for compressed event data as input.
steps {
  step_id: "input-event-data-dictionary"
  party: DATA_PROVIDER

  input_step {}

  output_labels { key: "input" value: "edp-event-data-dictionary" }
}

# EDP exports its event data dictionary.
steps {
  step_id: "export-event-data-dictionary"
  party: DATA_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "event-data-dictionary" value: "edp-event-data-dictionary" }
  output_labels { key: "event-data-dictionary" value: "event-data-dictionary" }
}

# MP imports EDP's event data dictionary.
steps {
  step_id: "import-event-data-dictionary"
  party: MODEL_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "event-data-dictionary" value: "event-data-dictionary" }
  output_labels { key: "event-data-dictionary" value: "mp-event-data-dictionary" }
}

# EDP executes encrypted queries
steps {
  step_id: "execute-encrypted-queries"
  party: DATA_PROVIDER

  execute_private_membership_queries_step {
    serialized_parameters: "..."
  }

  input_labels { key: "encrypted-event-data" value: "edp-encrypted-event-data" }
  input_labels { key: "encrypted-queries" value: "edp-encrypted-queries" }
  input_labels { key: "serialized-rlwe-public-key" value: "edp-serialized-rlwe-public-key" }

  output_labels { key: "encrypted-results" value: "edp-encrypted-query-results" }
}

# EDP exports its encrypted query results.
steps {
  step_id: "export-encrypted-query-results"
  party: DATA_PROVIDER

  copy_to_shared_storage_step {}

  input_labels { key: "encrypted-results" value: "edp-encrypted-query-results" }
  output_labels { key: "encrypted-results" value: "encrypted-query-results" }
}

# MP imports EDP's encrypted query results.
steps {
  step_id: "import-encrypted-query-results"
  party: MODEL_PROVIDER

  copy_from_shared_storage_step {}

  input_labels { key: "encrypted-results" value: "encrypted-query-results" }
  output_labels { key: "encrypted-results" value: "mp-encrypted-query-results" }
}

# MP decrypts the encrypted query results.
steps {
  step_id: "decrypt-encrypted-query-results"
  party: MODEL_PROVIDER

  decrypt_private_membership_query_results_step {
    serialized_parameters: "..."
  }

  input_labels { key: "serialized-rlwe-private-key" value: "mp-serialized-rlwe-private-key" }
  input_labels { key: "serialized-rlwe-public-key" value: "mp-serialized-rlwe-public-key" }
  input_labels { key: "event-data-dictionary" value: "mp-event-data-dictionary" }
  input_labels { key: "query-to-join-keys-map" value: "mp-query-to-join-keys-map" }
  input_labels { key: "encrypted-results" value: "mp-encrypted-query-results" }
  input_labels { key: "pepper" value: "mp-hkdf-pepper" }

  output_labels { key: "results" value: "results" }
}
