# proto-file: wfa/measurement/config/securecomputation/data_watcher_config.proto
# proto-message: wfa.measurement.config.securecomputation.DataWatcherConfig
watched_paths {
  identifier: "event-groups"
  source_path_regex: "gs://secure-computation-storage-dev-bucket/edp7/event-groups/(.*)"
  http_endpoint_sink {
    endpoint_uri: "https://us-central1-halo-cmm-dev.cloudfunctions.net/event-group-sync"
    app_params {
      fields {
        key: "dataProvider"
        value { string_value: "dataProviders/DRoeq5_-yYI" }
      }
      fields {
        key: "eventGroupsBlobUri"
        value { string_value: "gs://secure-computation-storage-dev-bucket/edp7/event-groups" }
      }
      fields {
        key: "eventGroupMapBlobUri"
        value { string_value: "gs://secure-computation-storage-dev-bucket/edp7/event-groups-map" }
      }
      fields {
        key: "cmmsConnection"
        value {
          struct_value {
            fields {
              key: "certFilePath"
              value { string_value: "/secrets/cert/edp7_tls.pem" }
            }
            fields {
              key: "privateKeyFilePath"
              value { string_value: "/secrets/key/edp7_tls.key" }
            }
            fields {
              key: "certCollectionFilePath"
              value { string_value: "/secrets/ca/kingdom_root.pem" }
            }
          }
        }
      }
      fields {
        key: "eventGroupStorage"
        value {
          struct_value {
            fields {
              key: "gcs"
              value {
                struct_value {
                  fields {
                    key: "projectId"
                    value { string_value: "halo-cmm-dev" }
                  }
                  fields {
                    key: "bucketName"
                    value { string_value: "secure-computation-storage" }
                  }
                }
              }
            }
          }
        }
      }
      fields {
        key: "eventGroupMapStorage"
        value {
          struct_value {
            fields {
              key: "gcs"
              value {
                struct_value {
                  fields {
                    key: "projectId"
                    value { string_value: "halo-cmm-dev" }
                  }
                  fields {
                    key: "bucketName"
                    value { string_value: "secure-computation-storage" }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
#watched_paths {
#  identifier: "results-fulfiller"
#  source_path_regex: "gs://test-bucket/webhook-sink-path-to-watch/(.*)"
#  control_plane_queue_sink {
#    queue: "requisition-fulfiller-queue"
#    app_params {
#      [type.googleapis.com/org.wfanet.measurement.edpaggregator.v1alpha.ResultsFulfillerParams] {
#        data_provider: "dataProviders/DRoeq5_-yYI"
#        storage {
#          labeled_impressions_blob_uri_prefix: "gs://secure-computation-storage-dev-bucket/edp7/labeled-impressions"
#          gcs_project_id: "halo-cmm-dev"
#        }
#        consent {
#          result_cs_cert_der_resource_path: "main/k8s/testing/secretfiles/edp7_cs_cert.der"
#          result_cs_private_key_der_resource_path: "main/k8s/testing/secretfiles/edp7_cs_private.der"
#          private_encryption_key_resource_path: "main/k8s/testing/secretfiles/edp7_enc_private.tink"
#          edp_certificate_name: "dataProviders/DRoeq5_-yYI/certificates/Elub4J_-ybw"
#        }
#        cmms_connection {
#          client_cert_resource_path: "main/k8s/testing/secretfiles/edp7_tls.pem"
#          client_private_key_resource_path: "main/k8s/testing/secretfiles/edp7_tls.key"
#        }
#      }
#    }
#  }
#}