load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "DashboardViewIsolationLocalTest",
    srcs = ["DashboardViewIsolationLocalTest.kt"],
    data = [
        "//src/main/terraform/gcloud/cmms/sql:mc_details.sql",
        "//src/main/terraform/gcloud/cmms/sql:report_detail.sql",
        "//src/main/terraform/gcloud/cmms/sql:requisition_overview.sql",
        "//src/main/terraform/gcloud/cmms/sql:unlinked_accounts.sql",
    ],
    deps = [
        "@wfa_common_jvm//imports/java/com/google/common/truth",
        "@wfa_common_jvm//imports/java/org/junit",
    ],
)

kt_jvm_test(
    name = "DashboardIsolationChecksTest",
    srcs = ["DashboardIsolationChecksTest.kt"],
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/edpaggregator/deploy/gcloud/dashboard:dashboard_isolation_checks",
        "@wfa_common_jvm//imports/java/com/google/common/truth",
        "@wfa_common_jvm//imports/java/org/junit",
    ],
)
