# proto-file: wfa/measurement/config/edpaggregator/requisition_fetcher_config.proto
# proto-message: wfa.measurement.config.edpaggregator.RequisitionFetcherConfig
configs {
  data_provider: "dataProviders/T5RryPMNong"
  requisition_storage {
    gcs {
      project_id: "halo-cmm-dev"
      bucket_name: "secure-computation-storage-dev-bucket"
    }
  }
  storage_path_prefix: "edp7/requisitions"
  cmms_connection {
    cert_file_path: "/secrets/cert/edp7_tls.pem"
    private_key_file_path: "/secrets/key/edp7_tls.key"
    cert_collection_file_path: "/secrets/ca/kingdom_root.pem"
  }
}
