# proto-file: wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto
# proto-message: SyntheticPopulationSpec

# A synthetic population used for performance testing.
# 360 Million individuals evenly distributed across 3 age buckets, 2 genders, and 2 social grades.
# Enum Values
# Age:
#  1: 18-34
#  2: 35-54
#  3: 55+
# Gender:
#  1: MALE
#  2: FEMALE
# Social Grade:
#  1: A, B, C1
#  2: C2, D, E

vid_range {
  start: 1
  end_exclusive: 1200000 # Age 18-64 with known social grade.
}
event_message_type_url: "type.googleapis.com/wfa.measurement.api.v2alpha.event_templates.testing.TestEvent"
population_fields: "person.gender"
population_fields: "person.age_group"
population_fields: "person.social_grade_group"
non_population_fields: "video_ad.viewed_fraction"
sub_populations {
  vid_sub_range {
    start: 1
    end_exclusive: 100000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 1
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 100000
    end_exclusive: 200000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 2
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 200000
    end_exclusive: 300000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 1
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 300000
    end_exclusive: 400000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 2
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 400000
    end_exclusive: 500000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 3
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 1
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 500000
    end_exclusive: 600000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 3
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 2
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 600000
    end_exclusive: 700000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 1
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 700000
    end_exclusive: 800000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 1
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 2
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 800000
    end_exclusive: 900000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 1
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 900000
    end_exclusive: 1000000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 2
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 1000000
    end_exclusive: 1100000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 3
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 1
    }
  }
}
sub_populations {
  vid_sub_range {
    start: 1100000
    end_exclusive: 1200000
  }
  population_fields_values {
    key: "person.age_group"
    value {
      enum_value: 3
    }
  }
  population_fields_values {
    key: "person.gender"
    value {
      enum_value: 2
    }
  }
  population_fields_values {
    key: "person.social_grade_group"
    value {
      enum_value: 2
    }
  }
}