# proto-file: wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto
# proto-message: SyntheticEventGroupSpec

# Spec for use with synthetic_population_spec_large.textproto.

date_specs {
  date_range {
    start {
      year: 2025
      month: 1
      day: 1
    }
    end_exclusive {
      year: 2025
      month: 2
      day: 1
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 1
        end_exclusive: 100000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.1
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 100000
        end_exclusive: 200000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.1
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 200000
        end_exclusive: 300000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.1
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 300000
        end_exclusive: 400000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.2
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 400000
        end_exclusive: 500000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.2
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 500000
        end_exclusive: 600000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.2
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 600000
        end_exclusive: 700000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.3
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 700000
        end_exclusive: 800000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.3
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 800000
        end_exclusive: 900000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.3
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 900000
        end_exclusive: 1000000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.4
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 1000000
        end_exclusive: 1100000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.4
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 1100000
        end_exclusive: 1200000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.4
        }
      }
    }
  }
}