# proto-file: wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto
# proto-message: SyntheticEventGroupSpec

# Spec for use with synthetic_population_spec_large.textproto.

date_specs {
  date_range {
    start {
      year: 2025
      month: 1
      day: 1
    }
    end_exclusive {
      year: 2025
      month: 1
      day: 30
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 1
        end_exclusive: 30000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.1
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 30000
        end_exclusive: 60000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.2
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 60000
        end_exclusive: 90000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.3
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 90000
        end_exclusive: 120000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.4
        }
      }
    }
  }
}