package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

HIGH_OVERLAP_SPECS = [
    "high_overlap_impression_test_data_config.textproto",
    "high_overlap_population_spec.textproto",
    "high_overlap_seg_all4_1.textproto",
    "high_overlap_seg_all4_2.textproto",
    "high_overlap_seg_all4_3.textproto",
    "high_overlap_seg_e7_meta.textproto",
    "high_overlap_seg_e7_meta_retail.textproto",
    "high_overlap_seg_e7_meta_video.textproto",
    "high_overlap_seg_e7_retail.textproto",
    "high_overlap_seg_e7_video_1.textproto",
    "high_overlap_seg_e7_video_2.textproto",
    "high_overlap_seg_e7_video_retail.textproto",
    "high_overlap_seg_e7only.textproto",
    "high_overlap_seg_meta_retail.textproto",
    "high_overlap_seg_meta_video_1.textproto",
    "high_overlap_seg_meta_video_2.textproto",
    "high_overlap_seg_meta_video_3.textproto",
    "high_overlap_seg_meta_video_retail.textproto",
    "high_overlap_seg_metaonly_1.textproto",
    "high_overlap_seg_metaonly_2.textproto",
    "high_overlap_seg_metaonly_3.textproto",
    "high_overlap_seg_noise.textproto",
    "high_overlap_seg_retailonly.textproto",
    "high_overlap_seg_video_retail_1.textproto",
    "high_overlap_seg_video_retail_2.textproto",
    "high_overlap_seg_videoonly_1.textproto",
    "high_overlap_seg_videoonly_2.textproto",
    "high_overlap_seg_videoonly_3.textproto",
]

genrule(
    name = "gen_high_overlap_specs",
    outs = HIGH_OVERLAP_SPECS,
    cmd = "$(execpath //src/main/kotlin/org/wfanet/measurement/loadtest/edpaggregator/tools:GenerateHighOverlapSpecs) $(RULEDIR)",
    tools = ["//src/main/kotlin/org/wfanet/measurement/loadtest/edpaggregator/tools:GenerateHighOverlapSpecs"],
)

filegroup(
    name = "specs",
    srcs = glob(["*.textproto"]) + [":gen_high_overlap_specs"],
)
