# proto-file: wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto
# proto-message: SyntheticEventGroupSpec

# Stress-test spec for reproducing SWIOTLB buffer exhaustion on Confidential VMs.
#
# Designed for use with small_population_spec.textproto (100K VIDs).
# VID ranges aligned to sub-population boundaries.
# Covers 36 days (Mar 1 - Apr 5 2026) to match the Chevrolet production window.

date_specs {
  date_range {
    start {
      year: 2026
      month: 3
      day: 1
    }
    end_exclusive {
      year: 2026
      month: 4
      day: 6
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 1
        end_exclusive: 10000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.25
        }
      }
    }
  }
  frequency_specs {
    frequency: 5
    vid_range_specs {
      vid_range {
        start: 10000
        end_exclusive: 20000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.5
        }
      }
    }
  }
  frequency_specs {
    frequency: 2
    vid_range_specs {
      vid_range {
        start: 20000
        end_exclusive: 30000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.1
        }
      }
    }
  }
  frequency_specs {
    frequency: 4
    vid_range_specs {
      vid_range {
        start: 30000
        end_exclusive: 40000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.75
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 40000
        end_exclusive: 50000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.3
        }
      }
    }
  }
  frequency_specs {
    frequency: 5
    vid_range_specs {
      vid_range {
        start: 50000
        end_exclusive: 60000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.6
        }
      }
    }
  }
  frequency_specs {
    frequency: 2
    vid_range_specs {
      vid_range {
        start: 60000
        end_exclusive: 70000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.15
        }
      }
    }
  }
  frequency_specs {
    frequency: 4
    vid_range_specs {
      vid_range {
        start: 70000
        end_exclusive: 80000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.8
        }
      }
    }
  }
  frequency_specs {
    frequency: 3
    vid_range_specs {
      vid_range {
        start: 80000
        end_exclusive: 85000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.2
        }
      }
    }
  }
  frequency_specs {
    frequency: 2
    vid_range_specs {
      vid_range {
        start: 85000
        end_exclusive: 90000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.4
        }
      }
    }
  }
  frequency_specs {
    frequency: 4
    vid_range_specs {
      vid_range {
        start: 90000
        end_exclusive: 95000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.55
        }
      }
    }
  }
  frequency_specs {
    frequency: 5
    vid_range_specs {
      vid_range {
        start: 95000
        end_exclusive: 100000
      }
      non_population_field_values {
        key: "video_ad.viewed_fraction"
        value {
          double_value: 0.7
        }
      }
    }
  }
}
