# Copyright 2023 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Configure metrics
description: |
  Configures Google Managed Prometheus metrics in a GKE cluster.
  
  Requirements:
  * `BAZEL_BIN` environment variable is set
  * `kubectl` points to cluster

runs:
  using: composite
  steps:
  - name: Install cert-manager
    shell: bash
    run: |
      kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.2/cert-manager.yaml
      kubectl rollout status deployment cert-manager-webhook --namespace=cert-manager --timeout=5m

  - name: Install OpenTelemetry operator
    shell: bash
    run: |
      kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.77.0/opentelemetry-operator.yaml
      kubectl rollout status deployment opentelemetry-operator-controller-manager --namespace=opentelemetry-operator-system --timeout=5m

  - name: Generate configurations
    shell: bash
    run: >
      bazelisk build
      //src/main/k8s/dev:open_telemetry_gke
      //src/main/k8s/dev:prometheus_gke

  - name: Apply configurations
    shell: bash
    run: |
      kubectl apply -f "$BAZEL_BIN/src/main/k8s/dev/open_telemetry_gke.yaml"
      kubectl apply -f "$BAZEL_BIN/src/main/k8s/dev/prometheus_gke.yaml"
