# proto-file: wfa/measurement/config/securecomputation/queues_config.proto
# proto-message: wfa.measurement.config.securecomputation.QueuesConfig

queueInfos {
  queue_resource_id: "results-fulfiller-queue"
  app_params_type_url: "type.googleapis.com/wfa.measurement.securecomputation.controlplane.v1alpha.WorkItem.WorkItemParams"
}
