measurement_consumer: "measurementConsumers/1"
event_group_universe {
  event_group_entries {
    key: "measurementConsumers/1/dataProviders/1/eventGroups/1"
    value: ""
  }
  event_group_entries {
    key: "measurementConsumers/1/dataProviders/2/eventGroups/3"
    value: "partner=abc"
  }
}
time_intervals {
  time_intervals {
    start_time: "2017-01-15T01:30:15.01Z"
    end_time: "2019-01-19T09:48:35.57Z"
  }
}