# EDP generates a certificate.
steps {
  step_id: "generate-edp-certificate"
  party: DATA_PROVIDER
  output_labels {
    key: "certificate-resource-name"
    value: "edp-certificate-resource-name"
  }
  generate_certificate_step {}
}

# MP generates a certificate.
steps {
  step_id: "generate-mp-certificate"
  party: MODEL_PROVIDER
  output_labels {
    key: "certificate-resource-name"
    value: "mp-certificate-resource-name"
  }
  generate_certificate_step {}
}

# EDP provides a previously generated pepper used in generating AES keys.
steps {
  step_id: "input-hkdf-pepper"
  party: DATA_PROVIDER
  input_step {}
  output_labels { key: "input" value: "edp-hkdf-pepper" }
}

# EDP exports its hkdf pepper.
steps {
  step_id: "export-hkdf-pepper"
  party: DATA_PROVIDER
  copy_to_shared_storage_step {
    copy_options {
      label_type: BLOB
    }
  }
  input_labels { key: "hkdf-pepper" value: "edp-hkdf-pepper" }
  output_labels { key: "hkdf-pepper" value: "hkdf-pepper" }
}

# MP imports EDP's hkdf pepper.
steps {
  step_id: "import-hkdf-pepper"
  party: MODEL_PROVIDER
  copy_from_shared_storage_step {
    copy_options {
      label_type: BLOB
    }
  }
  input_labels { key: "hkdf-pepper" value: "hkdf-pepper" }
  output_labels { key: "hkdf-pepper" value: "mp-hkdf-pepper" }
}

exchange_identifiers {
  data_provider: "dataProviders/"
  model_provider: "modelProviders/"
  shared_storage_owner: DATA_PROVIDER
  storage: GOOGLE_CLOUD_STORAGE
}

first_exchange_date {
  year: 2022
  month: 3
  day: 7
}

repetition_schedule {
  cron_expression: "@daily"
}