# proto-file: src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto
# proto-message: HmssProtocolConfigConfig
protocol_config {
  noise_mechanism: DISCRETE_GAUSSIAN
  reach_and_frequency_ring_modulus: 127
  reach_ring_modulus: 127
}

required_external_duchy_ids: "worker1"
required_external_duchy_ids: "worker2"
required_external_duchy_ids: "aggregator"