# proto-file: src/main/proto/wfa/measurement/config/duchy_public_key_config.proto
# proto-message: DuchyPublicKeyConfig
entries {
  key: "combined-public-key-1"
  value {
    combined_public_key_version: 1
    elliptic_curve_id: 415
    el_gamal_generator: "\x03\x6B\x17\xD1\xF2\xE1\x2C\x42\x47\xF8\xBC\xE6\xE5\x63\xA4\x40\xF2\x77\x03\x7D\x81\x2D\xEB\x33\xA0\xF4\xA1\x39\x45\xD8\x98\xC2\x96"
    el_gamal_elements {
      key: "duchy-a"
      value: "\x02\xD1\x43\x2C\xA0\x07\xA6\xC6\xD7\x39\xFC\xE2\xD2\x1F\xEB\x56\xD9\xA2\xC3\x5C\xF9\x68\x26\x5F\x90\x93\xC4\xB6\x91\xE1\x13\x86\xB3"
    }
    el_gamal_elements {
      key: "duchy-b"
      value: "\x03\x9E\xF3\x70\xFF\x4D\x21\x62\x25\x40\x17\x81\xD8\x8A\x03\xF5\xA6\x70\xA5\x04\x0E\x63\x33\x49\x2C\xB4\xE0\xCD\x99\x1A\xBB\xD5\xA3"
    }
    el_gamal_elements {
      key: "duchy-c"
      value: "\x02\xD0\xF2\x5A\xB4\x45\xFC\x9C\x29\xE7\xE2\x50\x9A\xDC\x93\x30\x84\x30\xF4\x32\x52\x2F\xFA\x93\xC2\xAE\x73\x7C\xEB\x48\x0B\x66\xD7"
    }
    combined_el_gamal_element: "\x02\x50\x5D\x7B\x3A\xC4\xC3\xC3\x87\xC7\x41\x32\xAB\x67\x7A\x34\x21\xE8\x83\xB9\x0D\x4C\x83\xDC\x76\x6E\x40\x0F\xE6\x7A\xCC\x1F\x04"
  }
}
