-- liquibase formatted sql

-- Copyright 2025 The Cross-Media Measurement Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- changeset tristanvuong2021:1 dbms:cloudspanner
-- comment: Create the initial basic report tables

-- Set protobuf FileDescriptorSet as a base64 string. This gets applied to the next DDL batch.
SET PROTO_DESCRIPTORS = 'CqsDCkB4ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2V2ZW50X3RlbXBsYXRlX2ZpZWxkLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyIoUCChJFdmVudFRlbXBsYXRlRmllbGQSEgoEcGF0aBgBIAEoCVIEcGF0aBJaCgV2YWx1ZRgCIAEoCzJELndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuRXZlbnRUZW1wbGF0ZUZpZWxkLkZpZWxkVmFsdWVSBXZhbHVlGn8KCkZpZWxkVmFsdWUSIwoMc3RyaW5nX3ZhbHVlGAEgASgJSABSC3N0cmluZ1ZhbHVlEh8KCmVudW1fdmFsdWUYAiABKAlIAFIJZW51bVZhbHVlEh8KCmJvb2xfdmFsdWUYAyABKAhIAFIJYm9vbFZhbHVlQgoKCHNlbGVjdG9yQjAKLG9yZy53ZmFuZXQubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyUAFiBnByb3RvMwq9Ago4d2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF9maWx0ZXIucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIaQHdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvZXZlbnRfdGVtcGxhdGVfZmllbGQucHJvdG8iXgoLRXZlbnRGaWx0ZXISTwoFdGVybXMYASADKAsyOS53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLkV2ZW50VGVtcGxhdGVGaWVsZFIFdGVybXNCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCqAEClB3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2ltcHJlc3Npb25fcXVhbGlmaWNhdGlvbl9maWx0ZXJfc3BlYy5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mho4d2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF9maWx0ZXIucHJvdG8isAIKIUltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyU3BlYxJxCgptZWRpYV90eXBlGAEgASgOMlIud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5JbXByZXNzaW9uUXVhbGlmaWNhdGlvbkZpbHRlclNwZWMuTWVkaWFUeXBlUgltZWRpYVR5cGUSTAoHZmlsdGVycxgCIAMoCzIyLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuRXZlbnRGaWx0ZXJSB2ZpbHRlcnMiSgoJTWVkaWFUeXBlEhoKFk1FRElBX1RZUEVfVU5TUEVDSUZJRUQQABIJCgVWSURFTxABEgsKB0RJU1BMQVkQAhIJCgVPVEhFUhADQjAKLG9yZy53ZmFuZXQubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyUAFiBnByb3RvMwqABApVd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9yZXBvcnRpbmdfaW1wcmVzc2lvbl9xdWFsaWZpY2F0aW9uX2ZpbHRlci5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhpQd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9pbXByZXNzaW9uX3F1YWxpZmljYXRpb25fZmlsdGVyX3NwZWMucHJvdG8i8wEKJlJlcG9ydGluZ0ltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyElwKK2V4dGVybmFsX2ltcHJlc3Npb25fcXVhbGlmaWNhdGlvbl9maWx0ZXJfaWQYASABKAlSJ2V4dGVybmFsSW1wcmVzc2lvblF1YWxpZmljYXRpb25GaWx0ZXJJZBJrCgxmaWx0ZXJfc3BlY3MYAiADKAsySC53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLkltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyU3BlY1ILZmlsdGVyU3BlY3NCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCtABChZnb29nbGUvdHlwZS9kYXRlLnByb3RvEgtnb29nbGUudHlwZSJCCgREYXRlEhIKBHllYXIYASABKAVSBHllYXISFAoFbW9udGgYAiABKAVSBW1vbnRoEhAKA2RheRgDIAEoBVIDZGF5Ql0KD2NvbS5nb29nbGUudHlwZUIJRGF0ZVByb3RvUAFaNGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9kYXRlO2RhdGX4AQGiAgNHVFBiBnByb3RvMwr7AQoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9uLnByb3RvEg9nb29nbGUucHJvdG9idWYiOgoIRHVyYXRpb24SGAoHc2Vjb25kcxgBIAEoA1IHc2Vjb25kcxIUCgVuYW5vcxgCIAEoBVIFbmFub3NCgwEKE2NvbS5nb29nbGUucHJvdG9idWZCDUR1cmF0aW9uUHJvdG9QAVoxZ29vZ2xlLmdvbGFuZy5vcmcvcHJvdG9idWYvdHlwZXMva25vd24vZHVyYXRpb25wYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCpwEChpnb29nbGUvdHlwZS9kYXRldGltZS5wcm90bxILZ29vZ2xlLnR5cGUaHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90byKnAgoIRGF0ZVRpbWUSEgoEeWVhchgBIAEoBVIEeWVhchIUCgVtb250aBgCIAEoBVIFbW9udGgSEAoDZGF5GAMgASgFUgNkYXkSFAoFaG91cnMYBCABKAVSBWhvdXJzEhgKB21pbnV0ZXMYBSABKAVSB21pbnV0ZXMSGAoHc2Vjb25kcxgGIAEoBVIHc2Vjb25kcxIUCgVuYW5vcxgHIAEoBVIFbmFub3MSOgoKdXRjX29mZnNldBgIIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkgAUgl1dGNPZmZzZXQSNAoJdGltZV96b25lGAkgASgLMhUuZ29vZ2xlLnR5cGUuVGltZVpvbmVIAFIIdGltZVpvbmVCDQoLdGltZV9vZmZzZXQiNAoIVGltZVpvbmUSDgoCaWQYASABKAlSAmlkEhgKB3ZlcnNpb24YAiABKAlSB3ZlcnNpb25CaQoPY29tLmdvb2dsZS50eXBlQg1EYXRlVGltZVByb3RvUAFaPGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9kYXRldGltZTtkYXRldGltZfgBAaICA0dUUGIGcHJvdG8zCtYCCj53ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbnRlcnZhbC5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhoWZ29vZ2xlL3R5cGUvZGF0ZS5wcm90bxoaZ29vZ2xlL3R5cGUvZGF0ZXRpbWUucHJvdG8ifwoRUmVwb3J0aW5nSW50ZXJ2YWwSOAoMcmVwb3J0X3N0YXJ0GAEgASgLMhUuZ29vZ2xlLnR5cGUuRGF0ZVRpbWVSC3JlcG9ydFN0YXJ0EjAKCnJlcG9ydF9lbmQYAiABKAsyES5nb29nbGUudHlwZS5EYXRlUglyZXBvcnRFbmRCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCuoECkB3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2Jhc2ljX3JlcG9ydF9kZXRhaWxzLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyGlV3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbXByZXNzaW9uX3F1YWxpZmljYXRpb25fZmlsdGVyLnByb3RvGj53ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbnRlcnZhbC5wcm90byKtAgoSQmFzaWNSZXBvcnREZXRhaWxzEhQKBXRpdGxlGAEgASgJUgV0aXRsZRKXAQogaW1wcmVzc2lvbl9xdWFsaWZpY2F0aW9uX2ZpbHRlcnMYAiADKAsyTS53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlcG9ydGluZ0ltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyUh5pbXByZXNzaW9uUXVhbGlmaWNhdGlvbkZpbHRlcnMSZwoScmVwb3J0aW5nX2ludGVydmFsGAMgASgLMjgud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5SZXBvcnRpbmdJbnRlcnZhbFIRcmVwb3J0aW5nSW50ZXJ2YWxCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCqQCChtnb29nbGUvdHlwZS9kYXlvZndlZWsucHJvdG8SC2dvb2dsZS50eXBlKoQBCglEYXlPZldlZWsSGwoXREFZX09GX1dFRUtfVU5TUEVDSUZJRUQQABIKCgZNT05EQVkQARILCgdUVUVTREFZEAISDQoJV0VETkVTREFZEAMSDAoIVEhVUlNEQVkQBBIKCgZGUklEQVkQBRIMCghTQVRVUkRBWRAGEgoKBlNVTkRBWRAHQmkKD2NvbS5nb29nbGUudHlwZUIORGF5T2ZXZWVrUHJvdG9QAVo+Z29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy90eXBlL2RheW9md2VlaztkYXlvZndlZWuiAgNHVFBiBnByb3RvMwquAgpBd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9tZXRyaWNfZnJlcXVlbmN5X3NwZWMucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIaG2dvb2dsZS90eXBlL2RheW9md2Vlay5wcm90byJrChNNZXRyaWNGcmVxdWVuY3lTcGVjEjAKBndlZWtseRgBIAEoDjIWLmdvb2dsZS50eXBlLkRheU9mV2Vla0gAUgZ3ZWVrbHkSFgoFdG90YWwYAiABKAhIAFIFdG90YWxCCgoIc2VsZWN0b3JCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCrcECjp3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3dpbmRvd2luZ19zcGVjLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyGkF3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL21ldHJpY19mcmVxdWVuY3lfc3BlYy5wcm90byLUAgoNV2luZG93aW5nU3BlYxJlChBtZXRyaWNfZnJlcXVlbmN5GAEgASgLMjoud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5NZXRyaWNGcmVxdWVuY3lTcGVjUg9tZXRyaWNGcmVxdWVuY3kSewoUYWNjdW11bGF0aW9uX29wdGlvbnMYAiABKA4ySC53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLldpbmRvd2luZ1NwZWMuQWNjdW11bGF0aW9uT3B0aW9uc1ITYWNjdW11bGF0aW9uT3B0aW9ucyJfChNBY2N1bXVsYXRpb25PcHRpb25zEiQKIEFDQ1VNVUxBVElPTl9PUFRJT05TX1VOU1BFQ0lGSUVEEAASDgoKQ1VNVUxBVElWRRABEhIKDk5PTl9DVU1VTEFUSVZFEAJCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCv8BCh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvEg9nb29nbGUucHJvdG9idWYiOwoJVGltZXN0YW1wEhgKB3NlY29uZHMYASABKANSB3NlY29uZHMSFAoFbmFub3MYAiABKAVSBW5hbm9zQoUBChNjb20uZ29vZ2xlLnByb3RvYnVmQg5UaW1lc3RhbXBQcm90b1ABWjJnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9rbm93bi90aW1lc3RhbXBwYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCrsCChpnb29nbGUvdHlwZS9pbnRlcnZhbC5wcm90bxILZ29vZ2xlLnR5cGUaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8ifAoISW50ZXJ2YWwSOQoKc3RhcnRfdGltZRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBSCXN0YXJ0VGltZRI1CghlbmRfdGltZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBSB2VuZFRpbWVCaQoPY29tLmdvb2dsZS50eXBlQg1JbnRlcnZhbFByb3RvUAFaPGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9pbnRlcnZhbDtpbnRlcnZhbPgBAaICA0dUUGIGcHJvdG8zCrQbCjB3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3BhZ2UucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIaGmdvb2dsZS90eXBlL2ludGVydmFsLnByb3RvGjh3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2V2ZW50X2ZpbHRlci5wcm90bxpAd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF90ZW1wbGF0ZV9maWVsZC5wcm90bxpVd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9yZXBvcnRpbmdfaW1wcmVzc2lvbl9xdWFsaWZpY2F0aW9uX2ZpbHRlci5wcm90bxo6d2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi93aW5kb3dpbmdfc3BlYy5wcm90byLzFwoEUGFnZRIUCgV0aXRsZRgBIAEoCVIFdGl0bGUSTAoHcmVzdWx0cxgCIAMoCzIyLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUGFnZS5SZXN1bHRSB3Jlc3VsdHMa3QoKDk1ldHJpY01ldGFkYXRhEoUBChZyZXBvcnRpbmdfdW5pdF9zdW1tYXJ5GAEgASgLMk8ud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5QYWdlLk1ldHJpY01ldGFkYXRhLlJlcG9ydGluZ1VuaXRTdW1tYXJ5UhRyZXBvcnRpbmdVbml0U3VtbWFyeRI6Cg10aW1lX2ludGVydmFsGAIgASgLMhUuZ29vZ2xlLnR5cGUuSW50ZXJ2YWxSDHRpbWVJbnRlcnZhbBJbCg53aW5kb3dpbmdfc3BlYxgDIAEoCzI0LndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuV2luZG93aW5nU3BlY1INd2luZG93aW5nU3BlYxKFAQoWZGltZW5zaW9uX3NwZW';

START BATCH DDL;

-- Create the initial proto bundle with all types defined in the FileDescriptorSet.
CREATE PROTO BUNDLE (
  `wfa.measurement.internal.reporting.v2.BasicReportResultDetails`,
  `wfa.measurement.internal.reporting.v2.Page`,
  `wfa.measurement.internal.reporting.v2.Page.Result`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricMetadata`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricMetadata.ReportingUnitComponentSummary`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricMetadata.ReportingUnitComponentSummary.EventGroupSummary`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricMetadata.ReportingUnitSummary`,
  `google.type.Interval`,
  `wfa.measurement.internal.reporting.v2.WindowingSpec`,
  `wfa.measurement.internal.reporting.v2.WindowingSpec.AccumulationOptions`,
  `wfa.measurement.internal.reporting.v2.MetricFrequencySpec`,
  `google.type.DayOfWeek`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricMetadata.DimensionSpecSummary`,
  `wfa.measurement.internal.reporting.v2.EventFilter`,
  `wfa.measurement.internal.reporting.v2.EventTemplateField`,
  `wfa.measurement.internal.reporting.v2.EventTemplateField.FieldValue`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricSet`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricSet.BasicMetricSet`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricSet.ReportingUnitMetricSet`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricSet.ComponentMetricSet`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricSet.DataProviderComponentMetricSetMapEntry`,
  `wfa.measurement.internal.reporting.v2.Page.Result.MetricSet.DataProviderComponentIntersectionMetricSet`,
  `wfa.measurement.internal.reporting.v2.BasicReportDetails`,
  `wfa.measurement.internal.reporting.v2.ImpressionQualificationFilterSpec`,
  `wfa.measurement.internal.reporting.v2.ImpressionQualificationFilterSpec.MediaType`,
  `wfa.measurement.internal.reporting.v2.ReportingInterval`,
  `google.type.DateTime`,
  `google.type.Date`,
);

CREATE TABLE ReportingSets (
  ReportingSetId INT64 NOT NULL,
  CmmsMeasurementConsumerId STRING(MAX) NOT NULL,
  ExternalReportingSetId STRING(MAX) NOT NULL

  DisplayName STRING(MAX)
) PRIMARY KEY ReportingSetId);

CREATE TABLE BasicReports (
  BasicReportId INT64 NOT NULL,
  CmmsMeasurementConsumerId STRING(MAX) NOT NULL,
  ExternalBasicReportId STRING(MAX) NOT NULL,
  RequestId STRING(MAX),
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  BasicReportDetails `wfa.measurement.internal.reporting.v2.BasicReportDetails`
    NOT NULL,
  CampaignGroupId STRING(MAX) NOT NULL,
  BasicReportResultDetails `wfa.measurement.internal.reporting.v2.BasicReportResultDetails`

  CONSTRAINT FK_BasicReportsReportingSets FOREIGN KEY CampaignGroupId REFERENCES ReportingSets(ReportingSetId)
) PRIMARY KEY (BasicReportId);

CREATE UNIQUE INDEX BasicReportsByExternalBasicReportId
  ON BasicReports(CmmsMeasurementConsumerId, ExternalBasicReportId);

CREATE INDEX BasicReportsByCreateTime
  ON BasicReports(CmmsMeasurementConsumerId, CreateTime, ExternalBasicReportId);

RUN BATCH;
