-- liquibase formatted sql

-- Copyright 2025 The Cross-Media Measurement Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- changeset tristanvuong2021:1 dbms:cloudspanner
-- comment: Create the initial basic report tables

-- Set protobuf FileDescriptorSet as a base64 string. This gets applied to the next DDL batch.
SET PROTO_DESCRIPTORS = 'CtABChZnb31nbGUvdHlwZS9kYXRlLnByb3RvEgtnb29nbGUudHlwZSJCCgREYXRlEhIKBHllYXIYASABKAVSBHllYXISFAoFbW9udGgYAiABKAVSBW1vbnRoEhAKA2RheRgDIAEoBVIDZGF5Ql0KD2NvbS5nb29nbGUudHlwZUIJRGF0ZVByb3RvUAFaNGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9kYXRlO2RhdGX4AQGiAgNHVFBiBnByb3RvMwr7AQoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9uLnByb3RvEg9nb29nbGUucHJvdG9idWYiOgoIRHVyYXRpb24SGAoHc2Vjb25kcxgBIAEoA1IHc2Vjb25kcxIUCgVuYW5vcxgCIAEoBVIFbmFub3NCgwEKE2NvbS5nb29nbGUucHJvdG9idWZCDUR1cmF0aW9uUHJvdG9QAVoxZ29vZ2xlLmdvbGFuZy5vcmcvcHJvdG9idWYvdHlwZXMva25vd24vZHVyYXRpb25wYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCpwEChpnb29nbGUvdHlwZS9kYXRldGltZS5wcm90bxILZ29vZ2xlLnR5cGUaHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90byKnAgoIRGF0ZVRpbWUSEgoEeWVhchgBIAEoBVIEeWVhchIUCgVtb250aBgCIAEoBVIFbW9udGgSEAoDZGF5GAMgASgFUgNkYXkSFAoFaG91cnMYBCABKAVSBWhvdXJzEhgKB21pbnV0ZXMYBSABKAVSB21pbnV0ZXMSGAoHc2Vjb25kcxgGIAEoBVIHc2Vjb25kcxIUCgVuYW5vcxgHIAEoBVIFbmFub3MSOgoKdXRjX29mZnNldBgIIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkgAUgl1dGNPZmZzZXQSNAoJdGltZV96b25lGAkgASgLMhUuZ29vZ2xlLnR5cGUuVGltZVpvbmVIAFIIdGltZVpvbmVCDQoLdGltZV9vZmZzZXQiNAoIVGltZVpvbmUSDgoCaWQYASABKAlSAmlkEhgKB3ZlcnNpb24YAiABKAlSB3ZlcnNpb25CaQoPY29tLmdvb2dsZS50eXBlQg1EYXRlVGltZVByb3RvUAFaPGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9kYXRldGltZTtkYXRldGltZfgBAaICA0dUUGIGcHJvdG8zCtYCCj53ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbnRlcnZhbC5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhoWZ29vZ2xlL3R5cGUvZGF0ZS5wcm90bxoaZ29vZ2xlL3R5cGUvZGF0ZXRpbWUucHJvdG8ifwoRUmVwb3J0aW5nSW50ZXJ2YWwSOAoMcmVwb3J0X3N0YXJ0GAEgASgLMhUuZ29vZ2xlLnR5cGUuRGF0ZVRpbWVSC3JlcG9ydFN0YXJ0EjAKCnJlcG9ydF9lbmQYAiABKAsyES5nb29nbGUudHlwZS5EYXRlUglyZXBvcnRFbmRCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCvkCCkB3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2Jhc2ljX3JlcG9ydF9kZXRhaWxzLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyGj53ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbnRlcnZhbC5wcm90byKTAQoSQmFzaWNSZXBvcnREZXRhaWxzEhQKBXRpdGxlGAEgASgJUgV0aXRsZRJnChJyZXBvcnRpbmdfaW50ZXJ2YWwYAiABKAsyOC53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlcG9ydGluZ0ludGVydmFsUhFyZXBvcnRpbmdJbnRlcnZhbEIwCixvcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MlABYgZwcm90bzMKqwMKQHdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvZXZlbnRfdGVtcGxhdGVfZmllbGQucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIihQIKEkV2ZW50VGVtcGxhdGVGaWVsZBISCgRwYXRoGAEgASgJUgRwYXRoEloKBXZhbHVlGAIgASgLMkQud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5FdmVudFRlbXBsYXRlRmllbGQuRmllbGRWYWx1ZVIFdmFsdWUafwoKRmllbGRWYWx1ZRIjCgxzdHJpbmdfdmFsdWUYASABKAlIAFILc3RyaW5nVmFsdWUSHwoKZW51bV92YWx1ZRgCIAEoCUgAUgllbnVtVmFsdWUSHwoKYm9vbF92YWx1ZRgDIAEoCEgAUglib29sVmFsdWVCCgoIc2VsZWN0b3JCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCr0CCjh3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2V2ZW50X2ZpbHRlci5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhpAd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF90ZW1wbGF0ZV9maWVsZC5wcm90byJeCgtFdmVudEZpbHRlchJPCgV0ZXJtcxgBIAMoCzI5LndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuRXZlbnRUZW1wbGF0ZUZpZWxkUgV0ZXJtc0IwCixvcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MlABYgZwcm90bzMKoAQKUHdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvaW1wcmVzc2lvbl9xdWFsaWZpY2F0aW9uX2ZpbHRlcl9zcGVjLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyGjh3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2V2ZW50X2ZpbHRlci5wcm90byKwAgohSW1wcmVzc2lvblF1YWxpZmljYXRpb25GaWx0ZXJTcGVjEnEKCm1lZGlhX3R5cGUYASABKA4yUi53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLkltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyU3BlYy5NZWRpYVR5cGVSCW1lZGlhVHlwZRJMCgdmaWx0ZXJzGAIgAygLMjIud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5FdmVudEZpbHRlclIHZmlsdGVycyJKCglNZWRpYVR5cGUSGgoWTUVESUFfVFlQRV9VTlNQRUNJRklFRBAAEgkKBVZJREVPEAESCwoHRElTUExBWRACEgkKBU9USEVSEANCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCqMDCld3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2N1c3RvbV9pbXByZXNzaW9uX3F1YWxpZmljYXRpb25fZmlsdGVyX3NwZWMucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIaUHdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvaW1wcmVzc2lvbl9xdWFsaWZpY2F0aW9uX2ZpbHRlcl9zcGVjLnByb3RvIpQBCidDdXN0b21JbXByZXNzaW9uUXVhbGlmaWNhdGlvbkZpbHRlclNwZWMSaQoLZmlsdGVyX3NwZWMYASADKAsySC53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLkltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyU3BlY1IKZmlsdGVyU3BlY0IwCixvcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MlABYgZwcm90bzMKpAIKG2dvb2dsZS90eXBlL2RheW9md2Vlay5wcm90bxILZ29vZ2xlLnR5cGUqhAEKCURheU9mV2VlaxIbChdEQVlfT0ZfV0VFS19VTlNQRUNJRklFRBAAEgoKBk1PTkRBWRABEgsKB1RVRVNEQVkQAhINCglXRURORVNEQVkQAxIMCghUSFVSU0RBWRAEEgoKBkZSSURBWRAFEgwKCFNBVFVSREFZEAYSCgoGU1VOREFZEAdCaQoPY29tLmdvb2dsZS50eXBlQg5EYXlPZldlZWtQcm90b1ABWj5nb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL3R5cGUvZGF5b2Z3ZWVrO2RheW9md2Vla6ICA0dUUGIGcHJvdG8zCq4CCkF3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL21ldHJpY19mcmVxdWVuY3lfc3BlYy5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhobZ29vZ2xlL3R5cGUvZGF5b2Z3ZWVrLnByb3RvImsKE01ldHJpY0ZyZXF1ZW5jeVNwZWMSMAoGd2Vla2x5GAEgASgOMhYuZ29vZ2xlLnR5cGUuRGF5T2ZXZWVrSABSBndlZWtseRIWCgV0b3RhbBgCIAEoCEgAUgV0b3RhbEIKCghzZWxlY3RvckIwCixvcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MlABYgZwcm90bzMK/wEKH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8SD2dvb2dsZS5wcm90b2J1ZiI7CglUaW1lc3RhbXASGAoHc2Vjb25kcxgBIAEoA1IHc2Vjb25kcxIUCgVuYW5vcxgCIAEoBVIFbmFub3NChQEKE2NvbS5nb29nbGUucHJvdG9idWZCDlRpbWVzdGFtcFByb3RvUAFaMmdvb2dsZS5nb2xhbmcub3JnL3Byb3RvYnVmL3R5cGVzL2tub3duL3RpbWVzdGFtcHBi+AEBogIDR1BCqgIeR29vZ2xlLlByb3RvYnVmLldlbGxLbm93blR5cGVzYgZwcm90bzMKuwIKGmdvb2dsZS90eXBlL2ludGVydmFsLnByb3RvEgtnb29nbGUudHlwZRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byJ8CghJbnRlcnZhbBI5CgpzdGFydF90aW1lGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIJc3RhcnRUaW1lEjUKCGVuZF90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIHZW5kVGltZUJpCg9jb20uZ29vZ2xlLnR5cGVCDUludGVydmFsUHJvdG9QAVo8Z29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy90eXBlL2ludGVydmFsO2ludGVydmFs+AEBogIDR1RQYgZwcm90bzMKjRAKQ3dmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvbWV0cmljX21ldGFkYXRhX2RldGFpbHMucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIaGmdvb2dsZS90eXBlL2ludGVydmFsLnByb3RvGjh3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2V2ZW50X2ZpbHRlci5wcm90bxpAd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF90ZW1wbGF0ZV9maWVsZC5wcm90bxpBd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9tZXRyaWNfZnJlcXVlbmN5X3NwZWMucHJvdG8iiQ0KFU1ldHJpY01ldGFkYXRhRGV0YWlscxI6Cg10aW1lX2ludGVydmFsGAEgASgLMhUuZ29vZ2xlLnR5cGUuSW50ZXJ2YWxSDHRpbWVJbnRlcnZhbBKHAQoWcmVwb3J0aW5nX3VuaXRfc3VtbWFyeRgCIAEoCzJRLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuTWV0cmljTWV0YWRhdGFEZXRhaWxzLlJlcG9ydGluZ1VuaXRTdW1tYXJ5UhRyZXBvcnRpbmdVbml0U3VtbWFyeRJxCg53aW5kb3dpbmdfc3BlYxgDIAEoCzJKLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuTWV0cmljTWV0YWRhdGFEZXRhaWxzLldpbmRvd2luZ1NwZWNSDXdpbmRvd2luZ1NwZWMShwEKFmRpbWVuc2lvbl9zcGVjX3N1bW1hcnkYBCABKAsyUS53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLk1ldHJpY01ldGFkYXRhRGV0YWlscy5EaW1lbnNpb25TcGVjU3VtbWFyeVIUZGltZW5zaW9uU3BlY1N1bW1hcnkawQMKHVJlcG9ydGluZ1VuaXRDb21wb25lbnRTdW1tYXJ5EjEKFWNtbXNfZGF0YV9wcm92aWRlcl9pZBgBIAEoCVISY21tc0RhdGFQcm92aWRlcklkEkQKH2NtbXNfZGF0YV9wcm92aWRlcl9kaXNwbGF5X25hbWUYAiABKAlSG2NtbXNEYXRhUHJvdmlkZXJEaXNwbGF5TmFtZRKgAQoVZXZlbnRfZ3JvdXBfc3VtbWFyaWVzGAMgAygLMmwud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5NZXRyaWNNZXRhZGF0YURldGFpbHMuUmVwb3J0aW5nVW5pdENvbXBvbmVudFN1bW1hcnkuRXZlbnRHcm91cFN1bW1hcnlSE2V2ZW50R3JvdXBTdW1tYXJpZXMagwEKEUV2ZW50R3JvdXBTdW1tYXJ5Ej8KHGNtbXNfbWVhc3VyZW1lbnRfY29uc3VtZXJfaWQYASABKAlSGWNtbXNNZWFzdXJlbWVudENvbnN1bWVySWQSLQoTY21tc19ldmVudF9ncm91cF9pZBgCIAEoCVIQY21tc0V2ZW50R3JvdXBJZBq8AQoUUmVwb3J0aW5nVW5pdFN1bW1hcnkSowEKIHJlcG9ydGluZ191bml0X2NvbXBvbmVudF9zdW1tYXJ5GAEgAygLMloud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5NZXRyaWNNZXRhZGF0YURldGFpbHMuUmVwb3J0aW5nVW5pdENvbXBvbmVudFN1bW1hcnlSHXJlcG9ydGluZ1VuaXRDb21wb25lbnRTdW1tYXJ5GusCCg1XaW5kb3dpbmdTcGVjEmUKEG1ldHJpY19mcmVxdWVuY3kYASABKAsyOi53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLk1ldHJpY0ZyZXF1ZW5jeVNwZWNSD21ldHJpY0ZyZXF1ZW5jeRKRAQoUYWNjdW11bGF0aW9uX29wdGlvbnMYAiABKA4yXi53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLk1ldHJpY01ldGFkYXRhRGV0YWlscy5XaW5kb3dpbmdTcGVjLkFjY3VtdWxhdGlvbk9wdGlvbnNSE2FjY3VtdWxhdGlvbk9wdGlvbnMiXwoTQWNjdW11bG';

START BATCH DDL;

-- Create the initial proto bundle with all types defined in the FileDescriptorSet.
CREATE PROTO BUNDLE (
  `wfa.measurement.internal.reporting.v2.CustomImpressionQualificationFilterSpec`,
  `wfa.measurement.internal.reporting.v2.ImpressionQualificationFilterSpec`,
  `wfa.measurement.internal.reporting.v2.ImpressionQualificationFilterSpec.MediaType`,
  `wfa.measurement.internal.reporting.v2.EventFilter`,
  `wfa.measurement.internal.reporting.v2.EventTemplateField`,
  `wfa.measurement.internal.reporting.v2.EventTemplateField.FieldValue`,
  `wfa.measurement.internal.reporting.v2.ReportingUnitComponentSummaryDetails`,
  `wfa.measurement.internal.reporting.v2.ReportingUnitComponentSummaryDetails.EventGroupSummary`,
  `wfa.measurement.internal.reporting.v2.MetricMetadataDetails`,
  `wfa.measurement.internal.reporting.v2.MetricMetadataDetails.WindowingSpec`,
  `wfa.measurement.internal.reporting.v2.MetricMetadataDetails.DimensionSpecSummary`,
  `wfa.measurement.internal.reporting.v2.MetricFrequencySpec`,
  `google.type.DayOfWeek`,
  `wfa.measurement.internal.reporting.v2.MetricMetadataDetails.WindowingSpec.AccumulationOptions`,
  `wfa.measurement.internal.reporting.v2.BasicMetricSet`,
  `wfa.measurement.internal.reporting.v2.ComponentMetricSet`,
  `wfa.measurement.internal.reporting.v2.DataProviderComponentMetricSetDetails`,
  `wfa.measurement.internal.reporting.v2.MetricSetDetails`,
  `wfa.measurement.internal.reporting.v2.MetricSetDetails.ReportingUnitMetricSet`,
  `wfa.measurement.internal.reporting.v2.BasicReportDetails`,
  `wfa.measurement.internal.reporting.v2.ReportingInterval`,
  `google.type.DateTime`,
  `google.type.Date`,
);

CREATE TABLE ReportingSets (
  ReportingSetId INT64 NOT NULL,
  CmmsMeasurementConsumerId STRING(MAX) NOT NULL,
  ExternalReportingSetId STRING(MAX) NOT NULL
) PRIMARY KEY ReportingSetId);

CREATE TABLE BasicReports (
  BasicReportId INT64 NOT NULL,
  CmmsMeasurementConsumerId STRING(MAX) NOT NULL,
  ExternalBasicReportId STRING(MAX) NOT NULL,
  RequestId STRING(MAX),
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  BasicReportDetails `wfa.measurement.internal.reporting.v2.BasicReportDetails`
    NOT NULL,
  CampaignGroupId STRING(MAX) NOT NULL,

  CONSTRAINT FK_BasicReportsReportingSets FOREIGN KEY CampaignGroupId REFERENCES ReportingSets(ReportingSetId)
) PRIMARY KEY (BasicReportId);

CREATE UNIQUE INDEX BasicReportsByExternalBasicReportId
  ON BasicReports(CmmsMeasurementConsumerId, ExternalBasicReportId);

CREATE INDEX BasicReportsByCreateTime
  ON BasicReports(CmmsMeasurementConsumerId, CreateTime, ExternalBasicReportId);

CREATE TABLE ReportingImpressionQualificationFilter (
  BasicReportId NOT NULL,
  ReportingImpressionQualificationFilter INT64 NOT NULL,

  ExternalImpressionQualificationFilterId STRING(MAX),
  CustomImpressionQualificationFilterSpec `wfa.measurement.internal.reporting.v2.CustomImpressionQualificationFilterSpec`,

  CONSTRAINT FK_ReportingImpressionQualificationFiltersBasicReports FOREIGN KEY BasicReportId REFERENCES BasicReports(BasicReportId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, ReportingImpressionQualificationFilterId);

CREATE TABLE Pages (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,

  Title STRING(MAX),

  CONSTRAINT FK_PagesBasicReports FOREIGN KEY BasicReportId REFERENCES BasicReports(BasicReportId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId);

CREATE TABLE Results (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,

  CONSTRAINT FK_ResultsPages FOREIGN KEY (BasicReportId, PageId) REFERENCES Pages(BasicReportId, PageId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId);

CREATE TABLE MetricMetadata (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,
  MetricMetadataId INT64 NOT NULL,

  ReportingImpressionQualificationFilterId INT64 NOT NULL,
  MetricMetadataDetails `wfa.measurement.internal.reporting.v2.MetricMetadataDetails`
    NOT NULL,

  CONSTRAINT FK_MetricMetadataReportingImpressionQualificationFilters FOREIGN KEY (BasicReportId, ReportingImpressionQualificationFilterId)
    REFERENCES ReportingImpressionQualificationFilters(BasicReportId, ReportingImpressionQualificationFilterId),
  CONSTRAINT FK_MetricMetadataResults FOREIGN KEY (BasicReportId, PageId, ResultId) REFERENCES Results(BasicReportId, PageId, ResultId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId, MetricMetadataId);

CREATE TABLE ReportingUnitSummaries (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,
  MetricMetadataId INT64 NOT NULL,
  ReportingUnitSummaryId INT64 NOT NULL,

  CONSTRAINT FK_ReportingUnitSummariesMetricMetadata FOREIGN KEY (BasicReportId, PageId, ResultId, MetricMetadataId)
    REFERENCES MetricMetadata(BasicReportId, PageId, ResultId, MetricMetadataId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId, MetricMetadataId, ReportingUnitSummaryId);

CREATE TABLE ReportingUnitComponentSummaries (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,
  MetricMetadataId INT64 NOT NULL,
  ReportingUnitSummaryId INT64 NOT NULL,
  ReportingUnitComponentSummaryId INT64 NOT NULL,

  ReportingSetId INT64,
  CmmsDataProviderId STRING(MAX),
  ReportingUnitComponentSummaryDetails `wfa.measurement.internal.reporting.v2.ReportingUnitComponentSummaryDetails`
    NOT NULL,

  CONSTRAINT FK_ReportingUnitComponentSummariesReportingSets FOREIGN KEY ReportingSetId REFERENCES ReportingSets(ReportingSetId),
  CONSTRAINT FK_ReportingUnitComponentSummariesReportingUnitSummaries FOREIGN KEY (BasicReportId, PageId, ResultId, MetricMetadataId)
    REFERENCES ReportingUnitSummaries(BasicReportId, PageId, ResultId, MetricMetadataId, ReportingUnitSummaryId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId, MetricMetadataId, ReportingUnitSummaryId, ReportingUnitComponentSummaryId);

CREATE TABLE MetricSets (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,
  MetricSetId INT64 NOT NULL,

  MetricSetDetails `wfa.measurement.internal.reporting.v2.MetricSetDetails` NOT NULL,

  CONSTRAINT FK_MetricSetsResults FOREIGN KEY (BasicReportId, PageId, ResultId) REFERENCES Results(BasicReportId, PageId, ResultId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId, MetricSetId);

CREATE TABLE ComponentMetricSetMapEntries (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,
  MetricSetId INT64 NOT NULL,
  ComponentMetricSetMapEntryId NOT NULL,

  ReportingSetId INT64,
  CmmsDataProviderId STRING(MAX),
  ComponentMetricSet `wfa.measurement.internal.reporting.v2.ComponentMetricSet` NOT NULL,

  CONSTRAINT FK_ComponentMetricSetMapEntriesReportingSets FOREIGN KEY ReportingSetId REFERENCES ReportingSets(ReportingSetId),
  CONSTRAINT FK_ComponentMetricSetMapEntriesMetricSets FOREIGN KEY (BasicReportId, PageId, ResultId, MetricSetId)
    REFERENCES MetricSets(BasicReportId, PageId, ResultId, MetricSetId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId, MetricSetId, ComponentMetricSetMapEntryId);

CREATE TABLE ComponentIntersectionMetricSets (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,
  MetricSetId INT64 NOT NULL,
  ComponentIntersectionMetricSetId NOT NULL,

  DataProviderComponentIntersectionMetricSetDetails `wfa.measurement.internal.reporting.v2.DataProviderComponentIntersectionMetricSetDetails` NOT NULL,

  CONSTRAINT FK_ComponentIntersectionMetricSetsReportingSets FOREIGN KEY ReportingSetId REFERENCES ReportingSets(ReportingSetId),
  CONSTRAINT FK_ComponentIntersectionMetricSetsMetricSets FOREIGN KEY (BasicReportId, PageId, ResultId, MetricSetId)
    REFERENCES MetricSets(BasicReportId, PageId, ResultId, MetricSetId) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId, MetricSetId, ComponentIntersectionMetricSetId);

CREATE TABLE ComponentIntersectionMetricSetDataProviders (
  BasicReportId NOT NULL,
  PageId INT64 NOT NULL,
  ResultId INT64 NOT NULL,
  MetricSetId INT64 NOT NULL,
  ComponentIntersectionMetricSetId NOT NULL,
  CmmsDataProviderId STRING(MAX) NOT NULL,

  CONSTRAINT FK_ComponentIntersectionMetricSetReportingSetsComponentIntersectionMetricSets
    FOREIGN KEY (BasicReportId, PageId, ResultId, MetricSetId, ComponentIntersectionMetricSetId)
    REFERENCES ComponentIntersectionMetricSets(BasicReportId, PageId, ResultId, MetricSetId, ComponentIntersectionMetricSets) ON DELETE CASCADE
) PRIMARY KEY (BasicReportId, PageId, ResultId, MetricSetId, ComponentIntersectionMetricSetId, ReportingSetId);

RUN BATCH;
