-- liquibase formatted sql

-- Copyright 2025 The Cross-Media Measurement Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- changeset tristanvuong2021:1 dbms:cloudspanner
-- comment: Create initial basic report tables

-- Set protobuf FileDescriptorSet as a base64 string. This gets applied to the next DDL batch.
SET PROTO_DESCRIPTORS = 'CqsDCkB3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2V2ZW50X3RlbXBsYXRlX2ZpZWxkLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyIoUCChJFdmVudFRlbXBsYXRlRmllbGQSEgoEcGF0aBgBIAEoCVIEcGF0aBJaCgV2YWx1ZRgCIAEoCzJELndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuRXZlbnRUZW1wbGF0ZUZpZWxkLkZpZWxkVmFsdWVSBXZhbHVlGn8KCkZpZWxkVmFsdWUSIwoMc3RyaW5nX3ZhbHVlGAEgASgJSABSC3N0cmluZ1ZhbHVlEh8KCmVudW1fdmFsdWUYAiABKAlIAFIJZW51bVZhbHVlEh8KCmJvb2xfdmFsdWUYAyABKAhIAFIJYm9vbFZhbHVlQgoKCHNlbGVjdG9yQjAKLG9yZy53ZmFuZXQubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyUAFiBnByb3RvMwq9Ago4d2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF9maWx0ZXIucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIaQHdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvZXZlbnRfdGVtcGxhdGVfZmllbGQucHJvdG8iXgoLRXZlbnRGaWx0ZXISTwoFdGVybXMYASADKAsyOS53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLkV2ZW50VGVtcGxhdGVGaWVsZFIFdGVybXNCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCqAEClB3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2ltcHJlc3Npb25fcXVhbGlmaWNhdGlvbl9maWx0ZXJfc3BlYy5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mho4d2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF9maWx0ZXIucHJvdG8isAIKIUltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyU3BlYxJxCgptZWRpYV90eXBlGAEgASgOMlIud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5JbXByZXNzaW9uUXVhbGlmaWNhdGlvbkZpbHRlclNwZWMuTWVkaWFUeXBlUgltZWRpYVR5cGUSTAoHZmlsdGVycxgCIAMoCzIyLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuRXZlbnRGaWx0ZXJSB2ZpbHRlcnMiSgoJTWVkaWFUeXBlEhoKFk1FRElBX1RZUEVfVU5TUEVDSUZJRUQQABIJCgVWSURFTxABEgsKB0RJU1BMQVkQAhIJCgVPVEhFUhADQjAKLG9yZy53ZmFuZXQubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyUAFiBnByb3RvMwqABApVd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9yZXBvcnRpbmdfaW1wcmVzc2lvbl9xdWFsaWZpY2F0aW9uX2ZpbHRlci5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhpQd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9pbXByZXNzaW9uX3F1YWxpZmljYXRpb25fZmlsdGVyX3NwZWMucHJvdG8i8wEKJlJlcG9ydGluZ0ltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyElwKK2V4dGVybmFsX2ltcHJlc3Npb25fcXVhbGlmaWNhdGlvbl9maWx0ZXJfaWQYASABKAlSJ2V4dGVybmFsSW1wcmVzc2lvblF1YWxpZmljYXRpb25GaWx0ZXJJZBJrCgxmaWx0ZXJfc3BlY3MYAiADKAsySC53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLkltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyU3BlY1ILZmlsdGVyU3BlY3NCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCtABChZnb29nbGUvdHlwZS9kYXRlLnByb3RvEgtnb29nbGUudHlwZSJCCgREYXRlEhIKBHllYXIYASABKAVSBHllYXISFAoFbW9udGgYAiABKAVSBW1vbnRoEhAKA2RheRgDIAEoBVIDZGF5Ql0KD2NvbS5nb29nbGUudHlwZUIJRGF0ZVByb3RvUAFaNGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9kYXRlO2RhdGX4AQGiAgNHVFBiBnByb3RvMwr7AQoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9uLnByb3RvEg9nb29nbGUucHJvdG9idWYiOgoIRHVyYXRpb24SGAoHc2Vjb25kcxgBIAEoA1IHc2Vjb25kcxIUCgVuYW5vcxgCIAEoBVIFbmFub3NCgwEKE2NvbS5nb29nbGUucHJvdG9idWZCDUR1cmF0aW9uUHJvdG9QAVoxZ29vZ2xlLmdvbGFuZy5vcmcvcHJvdG9idWYvdHlwZXMva25vd24vZHVyYXRpb25wYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCpwEChpnb29nbGUvdHlwZS9kYXRldGltZS5wcm90bxILZ29vZ2xlLnR5cGUaHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90byKnAgoIRGF0ZVRpbWUSEgoEeWVhchgBIAEoBVIEeWVhchIUCgVtb250aBgCIAEoBVIFbW9udGgSEAoDZGF5GAMgASgFUgNkYXkSFAoFaG91cnMYBCABKAVSBWhvdXJzEhgKB21pbnV0ZXMYBSABKAVSB21pbnV0ZXMSGAoHc2Vjb25kcxgGIAEoBVIHc2Vjb25kcxIUCgVuYW5vcxgHIAEoBVIFbmFub3MSOgoKdXRjX29mZnNldBgIIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkgAUgl1dGNPZmZzZXQSNAoJdGltZV96b25lGAkgASgLMhUuZ29vZ2xlLnR5cGUuVGltZVpvbmVIAFIIdGltZVpvbmVCDQoLdGltZV9vZmZzZXQiNAoIVGltZVpvbmUSDgoCaWQYASABKAlSAmlkEhgKB3ZlcnNpb24YAiABKAlSB3ZlcnNpb25CaQoPY29tLmdvb2dsZS50eXBlQg1EYXRlVGltZVByb3RvUAFaPGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9kYXRldGltZTtkYXRldGltZfgBAaICA0dUUGIGcHJvdG8zCtYCCj53ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbnRlcnZhbC5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhoWZ29vZ2xlL3R5cGUvZGF0ZS5wcm90bxoaZ29vZ2xlL3R5cGUvZGF0ZXRpbWUucHJvdG8ifwoRUmVwb3J0aW5nSW50ZXJ2YWwSOAoMcmVwb3J0X3N0YXJ0GAEgASgLMhUuZ29vZ2xlLnR5cGUuRGF0ZVRpbWVSC3JlcG9ydFN0YXJ0EjAKCnJlcG9ydF9lbmQYAiABKAsyES5nb29nbGUudHlwZS5EYXRlUglyZXBvcnRFbmRCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCuoECkB3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL2Jhc2ljX3JlcG9ydF9kZXRhaWxzLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyGlV3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbXByZXNzaW9uX3F1YWxpZmljYXRpb25fZmlsdGVyLnByb3RvGj53ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbnRlcnZhbC5wcm90byKtAgoSQmFzaWNSZXBvcnREZXRhaWxzEhQKBXRpdGxlGAEgASgJUgV0aXRsZRKXAQogaW1wcmVzc2lvbl9xdWFsaWZpY2F0aW9uX2ZpbHRlcnMYAiADKAsyTS53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlcG9ydGluZ0ltcHJlc3Npb25RdWFsaWZpY2F0aW9uRmlsdGVyUh5pbXByZXNzaW9uUXVhbGlmaWNhdGlvbkZpbHRlcnMSZwoScmVwb3J0aW5nX2ludGVydmFsGAMgASgLMjgud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5SZXBvcnRpbmdJbnRlcnZhbFIRcmVwb3J0aW5nSW50ZXJ2YWxCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCqQCChtnb29nbGUvdHlwZS9kYXlvZndlZWsucHJvdG8SC2dvb2dsZS50eXBlKoQBCglEYXlPZldlZWsSGwoXREFZX09GX1dFRUtfVU5TUEVDSUZJRUQQABIKCgZNT05EQVkQARILCgdUVUVTREFZEAISDQoJV0VETkVTREFZEAMSDAoIVEhVUlNEQVkQBBIKCgZGUklEQVkQBRIMCghTQVRVUkRBWRAGEgoKBlNVTkRBWRAHQmkKD2NvbS5nb29nbGUudHlwZUIORGF5T2ZXZWVrUHJvdG9QAVo+Z29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy90eXBlL2RheW9md2VlaztkYXlvZndlZWuiAgNHVFBiBnByb3RvMwquAgpBd2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9tZXRyaWNfZnJlcXVlbmN5X3NwZWMucHJvdG8SJXdmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIaG2dvb2dsZS90eXBlL2RheW9md2Vlay5wcm90byJrChNNZXRyaWNGcmVxdWVuY3lTcGVjEjAKBndlZWtseRgBIAEoDjIWLmdvb2dsZS50eXBlLkRheU9mV2Vla0gAUgZ3ZWVrbHkSFgoFdG90YWwYAiABKAhIAFIFdG90YWxCCgoIc2VsZWN0b3JCMAosb3JnLndmYW5ldC5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjJQAWIGcHJvdG8zCv8BCh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvEg9nb29nbGUucHJvdG9idWYiOwoJVGltZXN0YW1wEhgKB3NlY29uZHMYASABKANSB3NlY29uZHMSFAoFbmFub3MYAiABKAVSBW5hbm9zQoUBChNjb20uZ29vZ2xlLnByb3RvYnVmQg5UaW1lc3RhbXBQcm90b1ABWjJnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9rbm93bi90aW1lc3RhbXBwYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCoghCjh3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3Jlc3VsdF9ncm91cC5wcm90bxIld2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MhofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxo4d2ZhL21lYXN1cmVtZW50L2ludGVybmFsL3JlcG9ydGluZy92Mi9ldmVudF9maWx0ZXIucHJvdG8aQHdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvZXZlbnRfdGVtcGxhdGVfZmllbGQucHJvdG8aQXdmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvbWV0cmljX2ZyZXF1ZW5jeV9zcGVjLnByb3RvGlV3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3JlcG9ydGluZ19pbXByZXNzaW9uX3F1YWxpZmljYXRpb25fZmlsdGVyLnByb3RvIrMdCgtSZXN1bHRHcm91cBIUCgV0aXRsZRgBIAEoCVIFdGl0bGUSUwoHcmVzdWx0cxgCIAMoCzI5LndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXAuUmVzdWx0UgdyZXN1bHRzGtUMCg5NZXRyaWNNZXRhZGF0YRKMAQoWcmVwb3J0aW5nX3VuaXRfc3VtbWFyeRgBIAEoCzJWLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXAuTWV0cmljTWV0YWRhdGEuUmVwb3J0aW5nVW5pdFN1bW1hcnlSFHJlcG9ydGluZ1VuaXRTdW1tYXJ5EmIKIG5vbl9jdW11bGF0aXZlX21ldHJpY19zdGFydF90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIcbm9uQ3VtdWxhdGl2ZU1ldHJpY1N0YXJ0VGltZRJbChxjdW11bGF0aXZlX21ldHJpY19zdGFydF90aW1lGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIZY3VtdWxhdGl2ZU1ldHJpY1N0YXJ0VGltZRJCCg9tZXRyaWNfZW5kX3RpbWUYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUg1tZXRyaWNFbmRUaW1lEm4KFW1ldHJpY19mcmVxdWVuY3lfc3BlYxgFIAEoCzI6LndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuTWV0cmljRnJlcXVlbmN5U3BlY1ITbWV0cmljRnJlcXVlbmN5U3BlYxKMAQoWZGltZW5zaW9uX3NwZWNfc3VtbWFyeRgGIAEoCzJWLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXAuTWV0cmljTWV0YWRhdGEuRGltZW5zaW9uU3BlY1N1bW1hcnlSFGRpbWVuc2lvblNwZWNTdW1tYXJ5EmUKBmZpbHRlchgHIAEoCzJNLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVwb3J0aW5nSW1wcmVzc2lvblF1YWxpZmljYXRpb25GaWx0ZXJSBmZpbHRlchrGAwodUmVwb3J0aW5nVW5pdENvbXBvbmVudFN1bW1hcnkSMQoVY21tc19kYXRhX3Byb3ZpZGVyX2lkGAEgASgJUhJjbW1zRGF0YVByb3ZpZGVySWQSRAofY21tc19kYXRhX3Byb3ZpZGVyX2Rpc3BsYXlfbmFtZRgCIAEoCVIbY21tc0RhdGFQcm92aWRlckRpc3BsYXlOYW1lEqUBChVldmVudF9ncm91cF9zdW1tYXJpZXMYAyADKAsycS53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlc3VsdEdyb3VwLk1ldHJpY01ldGFkYXRhLlJlcG9ydGluZ1VuaXRDb21wb25lbnRTdW1tYXJ5LkV2ZW50R3JvdXBTdW1tYXJ5UhNldmVudEdyb3VwU3VtbWFyaWVzGoMBChFFdmVudEdyb3VwU3VtbWFyeRI/ChxjbW1zX21lYXN1cmVtZW50X2NvbnN1bWVyX2lkGAEgASgJUhljbW1zTWVhc3VyZW1lbnRDb25zdW1lcklkEi0KE2NtbXNfZXZlbnRfZ3JvdXBfaWQYAiABKAlSEGNtbXNFdmVudEdyb3VwSWQawQEKFFJlcG9ydGluZ1VuaXRTdW1tYXJ5EqgBCiByZXBvcnRpbmdfdW5pdF9jb21wb25lbnRfc3VtbWFyeRgBIAMoCzJfLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXAuTWV0cmljTWV0YWRhdGEuUmVwb3J0aW5nVW5pdENvbXBvbmVudFN1bW1hcnlSHXJlcG9ydGluZ1VuaXRDb21wb25lbnRTdW1tYXJ5GrsBChREaW1lbnNpb25TcGVjU3VtbWFyeRJVCghncm91cGluZxgBIAEoCzI5LndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuRXZlbnRUZW1wbGF0ZUZpZWxkUghncm91cGluZxJMCgdmaWx0ZXJzGAIgAygLMjIud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5FdmVudEZpbHRlclIHZmlsdGVycxqZDgoJTWV0cmljU2V0EicKD3BvcHVsYXRpb25fc2l6ZRgBIAEoBVIOcG9wdWxhdGlvblNpemUSegoOcmVwb3J0aW5nX3VuaXQYAiABKAsyUy53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlc3VsdEdyb3VwLk1ldHJpY1NldC5SZXBvcnRpbmdVbml0TWV0cmljU2V0Ug1yZXBvcnRpbmdVbml0EoMBCgpjb21wb25lbnRzGAMgAygLMmMud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5SZXN1bHRHcm91cC5NZXRyaWNTZXQuRGF0YVByb3ZpZGVyQ29tcG9uZW50TWV0cmljU2V0TWFwRW50cnlSCmNvbXBvbmVudHMSoAEKF2NvbXBvbmVudF9pbnRlcnNlY3Rpb25zGAQgAygLMmcud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5SZXN1bHRHcm91cC5NZXRyaWNTZXQuRGF0YVByb3ZpZGVyQ29tcG9uZW50SW50ZXJzZWN0aW9uTWV0cmljU2V0UhZjb21wb25lbnRJbnRlcnNlY3Rpb25zGoECCg5CYXNpY01ldHJpY1NldBIUCgVyZWFjaBgBIAEoBVIFcmVhY2gSIwoNcGVyY2VudF9yZWFjaBgCIAEoAlIMcGVyY2VudFJlYWNoEiAKDGtfcGx1c19yZWFjaBgDIAMoBVIKa1BsdXNSZWFjaBIvChRwZXJjZW50X2tfcGx1c19yZWFjaBgEIAMoAlIRcGVyY2VudEtQbHVzUmVhY2gSKwoRYXZlcmFnZV9mcmVxdWVuY3kYBSABKAJSEGF2ZXJhZ2VGcmVxdWVuY3kSIAoLaW1wcmVzc2lvbnMYBiABKAVSC2ltcHJlc3Npb25zEhIKBGdycHMYByABKAJSBGdycHMatQIKFlJlcG9ydGluZ1VuaXRNZXRyaWNTZXQScgoObm9uX2N1bXVsYXRpdmUYASABKAsySy53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlc3VsdEdyb3VwLk1ldHJpY1NldC5CYXNpY01ldHJpY1NldFINbm9uQ3VtdWxhdGl2ZRJrCgpjdW11bGF0aXZlGAIgASgLMksud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5SZXN1bHRHcm91cC5NZXRyaWNTZXQuQmFzaWNNZXRyaWNTZXRSCmN1bXVsYXRpdmUSOgoZc3RhY2tlZF9pbmNyZW1lbnRhbF9yZWFjaBgDIAMoBVIXc3RhY2tlZEluY3JlbWVudGFsUmVhY2gamAIKEkNvbXBvbmVudE1ldHJpY1NldBJyCg5ub25fY3VtdWxhdGl2ZRgBIAEoCzJLLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXAuTWV0cmljU2V0LkJhc2ljTWV0cmljU2V0Ug1ub25DdW11bGF0aXZlEmsKCmN1bXVsYXRpdmUYAiABKAsySy53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlc3VsdEdyb3VwLk1ldHJpY1NldC5CYXNpY01ldHJpY1NldFIKY3VtdWxhdGl2ZRIhCgx1bmlxdWVfcmVhY2gYAyABKAVSC3VuaXF1ZVJlYWNoGqEBCiZEYXRhUHJvdmlkZXJDb21wb25lbnRNZXRyaWNTZXRNYXBFbnRyeRIQCgNrZXkYASABKAlSA2tleRJlCgV2YWx1ZRgCIAEoCzJPLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXAuTWV0cmljU2V0LkNvbXBvbmVudE1ldHJpY1NldFIFdmFsdWUawgIKKkRhdGFQcm92aWRlckNvbXBvbmVudEludGVyc2VjdGlvbk1ldHJpY1NldBIzChZjbW1zX2RhdGFfcHJvdmlkZXJfaWRzGAEgAygJUhNjbW1zRGF0YVByb3ZpZGVySWRzEnIKDm5vbl9jdW11bGF0aXZlGAIgASgLMksud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5SZXN1bHRHcm91cC5NZXRyaWNTZXQuQmFzaWNNZXRyaWNTZXRSDW5vbkN1bXVsYXRpdmUSawoKY3VtdWxhdGl2ZRgDIAEoCzJLLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXAuTWV0cmljU2V0LkJhc2ljTWV0cmljU2V0UgpjdW11bGF0aXZlGsQBCgZSZXN1bHQSXQoIbWV0YWRhdGEYASABKAsyQS53ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyLlJlc3VsdEdyb3VwLk1ldHJpY01ldGFkYXRhUghtZXRhZGF0YRJbCgptZXRyaWNfc2V0GAIgASgLMjwud2ZhLm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52Mi5SZXN1bHRHcm91cC5NZXRyaWNTZXRSCW1ldHJpY1NldEIwCixvcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MlABYgZwcm90bzMK2QIKR3dmYS9tZWFzdXJlbWVudC9pbnRlcm5hbC9yZXBvcnRpbmcvdjIvYmFzaWNfcmVwb3J0X3Jlc3VsdF9kZXRhaWxzLnByb3RvEiV3ZmEubWVhc3VyZW1lbnQuaW50ZXJuYWwucmVwb3J0aW5nLnYyGjh3ZmEvbWVhc3VyZW1lbnQvaW50ZXJuYWwvcmVwb3J0aW5nL3YyL3Jlc3VsdF9ncm91cC5wcm90byJzChhCYXNpY1JlcG9ydFJlc3VsdERldGFpbHMSVwoNcmVzdWx0X2dyb3VwcxgBIAMoCzIyLndmYS5tZWFzdXJlbWVudC5pbnRlcm5hbC5yZXBvcnRpbmcudjIuUmVzdWx0R3JvdXBSDHJlc3VsdEdyb3Vwc0IwCixvcmcud2ZhbmV0Lm1lYXN1cmVtZW50LmludGVybmFsLnJlcG9ydGluZy52MlABYgZwcm90bzM=';

START BATCH DDL;

-- Create the initial proto bundle with all types defined in the FileDescriptorSet.
CREATE PROTO BUNDLE (
  `wfa.measurement.internal.reporting.v2.EventTemplateField`,
  `wfa.measurement.internal.reporting.v2.EventTemplateField.FieldValue`,
  `wfa.measurement.internal.reporting.v2.EventFilter`,
  `wfa.measurement.internal.reporting.v2.ImpressionQualificationFilterSpec`,
  `wfa.measurement.internal.reporting.v2.ImpressionQualificationFilterSpec.MediaType`,
  `wfa.measurement.internal.reporting.v2.ReportingImpressionQualificationFilter`,
  `google.type.Date`,
  `google.protobuf.Duration`,
  `google.type.DateTime`,
  `google.type.TimeZone`,
  `wfa.measurement.internal.reporting.v2.ReportingInterval`,
  `wfa.measurement.internal.reporting.v2.BasicReportDetails`,
  `google.type.DayOfWeek`,
  `wfa.measurement.internal.reporting.v2.MetricFrequencySpec`,
  `google.protobuf.Timestamp`,
  `wfa.measurement.internal.reporting.v2.ResultGroup`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricMetadata`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricMetadata.ReportingUnitComponentSummary`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricMetadata.ReportingUnitComponentSummary.EventGroupSummary`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricMetadata.ReportingUnitSummary`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricMetadata.DimensionSpecSummary`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricSet`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricSet.BasicMetricSet`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricSet.ReportingUnitMetricSet`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricSet.ComponentMetricSet`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricSet.DataProviderComponentMetricSetMapEntry`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.MetricSet.DataProviderComponentIntersectionMetricSet`,
  `wfa.measurement.internal.reporting.v2.ResultGroup.Result`,
  `wfa.measurement.internal.reporting.v2.BasicReportResultDetails`,
);

CREATE TABLE MeasurementConsumers (
  MeasurementConsumerId INT64 NOT NULL,
  CmmsMeasurementConsumerId STRING(MAX) NOT NULL
) PRIMARY KEY (MeasurementConsumerId);

CREATE UNIQUE INDEX MeasurementConsumersByCmmsMeasurementConsumerId
  ON MeasurementConsumers(CmmsMeasurementConsumerId);

CREATE TABLE BasicReports (
  MeasurementConsumerId INT64 NOT NULL,
  BasicReportId INT64 NOT NULL,
  ExternalBasicReportId STRING(MAX) NOT NULL,
  -- Is represented by an ExternalReportingSetId in the Postgres database.
  ExternalCampaignGroupId STRING(MAX) NOT NULL,
  CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
  BasicReportDetails `wfa.measurement.internal.reporting.v2.BasicReportDetails`
    NOT NULL,
  BasicReportResultDetails `wfa.measurement.internal.reporting.v2.BasicReportResultDetails`
    NOT NULL,
  BasicReportsIndexShardId INT64 NOT NULL AS (
    ABS(MOD(FARM_FINGERPRINT(CAST(BasicReportId AS STRING)), 64))
  ) STORED,

  FOREIGN KEY (MeasurementConsumerId) REFERENCES MeasurementConsumers (MeasurementConsumerId)
) PRIMARY KEY (MeasurementConsumerId, BasicReportId),
INTERLEAVE IN PARENT MeasurementConsumers ON DELETE CASCADE;

CREATE UNIQUE INDEX BasicReportsByExternalBasicReportId
  ON BasicReports(MeasurementConsumerId, ExternalBasicReportId);

CREATE INDEX BasicReportsByCreateTime
  ON BasicReports(BasicReportsIndexShardId, MeasurementConsumerId, CreateTime);

RUN BATCH;
