@startuml

!unquoted procedure resource($type)
  class $type << (R, SandyBrown) >>
!endprocedure
!unquoted procedure collection($name, $type)
  $name "1" *-- "many" $type
  object $name
!endprocedure

skinparam default {
  fontName "Roboto Mono"
  fontSize 12
}

resource(DataProvider) {
  owners
  Get()
}
resource(MeasurementConsumer) {
  owners
  Get()
}
resource(SketchConfig) {
}
resource(CombinedPublicKey) {
  encryption_key
  Get()
}
resource(Measurement) {
  measurement_spec
  data_provider_entries
  state
  result
}
resource(Account) {
  identity
  Update(account)
}

together {
  collection(measurementConsumers, MeasurementConsumer) {
    Create(measurementConsumer)
  }
  collection(dataProviders, DataProvider) {
    Create(data_provider)
  }
  collection(sketchConfigs, SketchConfig) {
    List()
  }
  collection(combinedPublicKeys, CombinedPublicKey) {
    List()
  }
  collection(accounts, Account) {
    Create(account)
  }
}

collection(requisitions, Requisition) {
  List([states])
}
collection(eventGroups, EventGroup) {
  Create(event_group)
  List([measurement_consumers])
}
collection(measurements, Measurement) {
  Create(measurement)
  List([states])
}
collection(apiKeys, ApiKey) {
  Create(api_key)
}

resource(Requisition) {
  measurement
  requisition_spec
  state
  Get()
  Refuse(refusal)
  Fulfill()
}
resource(EventGroup) {
  measurement_consumer
  Get()
}
resource(ApiKey) {
  nickname
  description
  authentication_key
  Delete()
}

DataProvider *-- eventGroups
DataProvider *-- requisitions
EventGroup "many" .> "1" MeasurementConsumer

Requisition "many" .> "many" EventGroup
Requisition "many" .> "1" Measurement

MeasurementConsumer *-- measurements
Measurement "many" ..> "1" CombinedPublicKey
Measurement "many" ..> "0..1" SketchConfig

Account *-- apiKeys
MeasurementConsumer "many" .> "many" Account
DataProvider "many" .> "many" Account
'Account "many" <. "many" MeasurementConsumer
'Account "many" <. "many" DataProvider

@enduml