@startuml

!unquoted procedure resource($type)
  class $type << (R, SandyBrown) >>
!endprocedure
!unquoted procedure collection($name, $type)
  $name "1" *-- "many" $type
  object $name
!endprocedure

skinparam default {
  fontName "Roboto Mono"
  fontSize 12
}

resource(DataProvider) {
}
resource(Advertiser) {
}
resource(SketchConfig) {
}
resource(CombinedPublicKey) {
  encryption_key
  Get()
}

together {
  collection(dataProviders, DataProvider) {
    Create(data_provider)
  }
  collection(advertisers, Advertiser) {
    Create(advertiser)
  }
  collection(sketchConfigs, SketchConfig) {
  }
  collection(combinedPublicKeys, CombinedPublicKey) {
  }
}

collection(metricRequisitions, MetricRequisition) {
  Create(metric_requisition)
  List([states])
}
collection(campaigns, Campaign) {
  Create(campaign)
  List([advertisers])
}

resource(MetricRequisition) {
  collection_interval
  metric_definition
  state
  combined_public_key
  Fulfill()
}
resource(Campaign) {
  advertiser
}
resource(MetricValue) {
  sketch
  Upload()
}

DataProvider *-- campaigns
Campaign "many" ..> "1" Advertiser
Campaign *-- metricRequisitions

MetricRequisition *-- "0..1" MetricValue
MetricRequisition "many" .> " 1" SketchConfig
MetricRequisition "many" .> "1" CombinedPublicKey

Advertiser -[hidden]> DataProvider

@enduml
