load(
    "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing:macros.bzl",
    "spanner_emulator_test",
)
load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "InternalApiServerTest",
    srcs = ["InternalApiServerTest.kt"],
    test_class = "org.wfanet.measurement.securecomputation.deploy.gcloud.spanner.InternalApiServerTest",
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner:internal_api_server",
        "@wfa_common_jvm//imports/java/com/google/common/truth",
        "@wfa_common_jvm//imports/java/org/junit",
        "@wfa_common_jvm//imports/java/picocli",
        "@wfa_common_jvm//imports/kotlin/kotlin/test",
    ],
)

spanner_emulator_test(
    name = "SecurecomputationSchemaTest",
    srcs = ["SecurecomputationSchemaTest.kt"],
    test_class = "org.wfanet.measurement.securecomputation.deploy.gcloud.spanner.SecurecomputationSchemaTest",
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/testing:schemata",
        "@wfa_common_jvm//imports/java/com/google/cloud/spanner",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing",
    ],
)

spanner_emulator_test(
    name = "SpannerWorkItemAttemptsServiceTest",
    srcs = ["SpannerWorkItemAttemptsServiceTest.kt"],
    test_class = "org.wfanet.measurement.securecomputation.deploy.gcloud.spanner.SpannerWorkItemAttemptsServiceTest",
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner:services",
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/testing:schemata",
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/service/internal/testing:work_item_attempts_service_test",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing",
    ],
)

spanner_emulator_test(
    name = "SpannerWorkItemsServiceTest",
    srcs = ["SpannerWorkItemsServiceTest.kt"],
    test_class = "org.wfanet.measurement.securecomputation.deploy.gcloud.spanner.SpannerWorkItemsServiceTest",
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner:services",
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/testing:schemata",
        "//src/main/kotlin/org/wfanet/measurement/securecomputation/service/internal/testing:work_items_service_test",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing",
    ],
)
