/*
 * Copyright 2026 The Cross-Media Measurement Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.wfanet.measurement.edpaggregator.rawimpressions

import com.google.crypto.tink.KmsClient
import com.google.protobuf.ByteString
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.map
import org.wfanet.measurement.edpaggregator.EncryptedStorage
import org.wfanet.measurement.edpaggregator.v1alpha.EncryptedDek
import org.wfanet.measurement.edpaggregator.v1alpha.SubpoolFingerprints
import org.wfanet.measurement.edpaggregator.v1alpha.encryptedDek
import org.wfanet.measurement.edpaggregator.v1alpha.subpoolFingerprints
import org.wfanet.measurement.storage.MesosRecordIoStorageClient
import org.wfanet.measurement.storage.StorageClient

/**
 * Reads and writes the per-subpool `SubpoolFingerprints` maps as **RecordIO** blobs.
 *
 * Lives in `rawimpressions` because both Phase-0 (`SubpoolAssigner`) and Phase-1 (`VidRankBuilder`)
 * use it: Phase-0 writes the per-(shard, subpool) blobs and (last-shard-out) merges them into one
 * per-subpool blob; Phase-1 reads the merged blobs.
 *
 * ## Why RecordIO (and not a single `SubpoolFingerprints` message)
 *
 * A protobuf message — and a Java `ByteString` — is capped at ~2 GB (`Int`-indexed), i.e. ~178M
 * 12-byte fingerprints. A merged per-subpool blob is the **un-sharded** subpool and can exceed
 * that. So a blob is a **stream of `SubpoolFingerprints` records** via
 * [MesosRecordIoStorageClient]: the caller supplies one packed-fingerprints chunk per record
 * ([writeBlob] takes a [Flow]), and reads stream back record-by-record — bounded memory regardless
 * of subpool size.
 *
 * ## Encryption
 *
 * Every blob is envelope-encrypted with a per-writer DEK via
 * [EncryptedStorage.buildEncryptedMesosStorageClient]. The DEK ([EncryptedDek], wrapped under the
 * EDP's KEK) is generated by [generateDek]; the same DEK encrypts every blob a given VM writes. DEK
 * *persistence* is not the store's concern — the SubpoolAssigner stores it on the
 * `PoolAssignmentJob` row (via `MarkPoolAssignmentJobSucceeded`) and the last-shard-out recovers
 * every shard's DEK with `ListPoolAssignmentJobs`.
 *
 * @param storageClient the base (unencrypted) storage client for the subpool-map bucket.
 * @param kmsClient KMS client able to unwrap the EDP's KEK.
 */
class SubpoolFingerprintsStore(
    private val storageClient: StorageClient,
    private val kmsClient: KmsClient,
) {
  /** One shard's encrypted blob for a subpool, used as a merge input. */
  data class SubpoolBlob(val blobKey: String, val encryptedDek: EncryptedDek)

  /** Generates a fresh DEK wrapped under [kekUri], used to encrypt this VM's blobs. */
  fun generateDek(kekUri: String): EncryptedDek {
    val serialized =
        EncryptedStorage.generateSerializedEncryptionKey(kmsClient, kekUri, TINK_KEY_TEMPLATE)
    return encryptedDek {
      this.kekUri = kekUri
      ciphertext = serialized
      protobufFormat = EncryptedDek.ProtobufFormat.BINARY
      typeUrl = TYPE_URL_TINK_KEYSET
    }
  }

  /**
   * Writes [fingerprintChunks] for [poolOffset] to [blobKey], one RecordIO `SubpoolFingerprints`
   * record per emitted chunk (each chunk a multiple of 12 packed bytes), envelope-encrypted with
   * [encryptedDek]. The chunk stream is consumed lazily, so memory stays bounded.
   */
  suspend fun writeBlob(
      blobKey: String,
      encryptedDek: EncryptedDek,
      poolOffset: Long,
      fingerprintChunks: Flow<ByteString>,
  ) {
    encryptedClient(encryptedDek)
        .writeBlob(
            blobKey,
            fingerprintChunks.map { chunk ->
              subpoolFingerprints {
                    this.poolOffset = poolOffset
                    fingerprints = chunk
                  }
                  .toByteString()
            },
        )
  }

  /** Streams the `SubpoolFingerprints` records of [blobKey], decrypting with [encryptedDek]. */
  fun readBlob(blobKey: String, encryptedDek: EncryptedDek): Flow<SubpoolFingerprints> = flow {
    val blob = encryptedClient(encryptedDek).getBlob(blobKey) ?: return@flow
    blob.read().collect { record -> emit(SubpoolFingerprints.parseFrom(record)) }
  }

  /**
   * Streams every record from each [inputs] blob into a single merged blob at [outputKey],
   * re-encrypted with [outputEncryptedDek]. Because shards partition the fingerprint space, the
   * inputs are disjoint and merging is a pure concatenation (no dedup). Missing inputs (a shard
   * with no blob for this subpool) are skipped. Memory stays bounded — records stream straight
   * through.
   */
  suspend fun mergeSubpool(
      inputs: List<SubpoolBlob>,
      outputKey: String,
      outputEncryptedDek: EncryptedDek,
  ) {
    encryptedClient(outputEncryptedDek)
        .writeBlob(
            outputKey,
            flow {
              for (input in inputs) {
                val blob = encryptedClient(input.encryptedDek).getBlob(input.blobKey) ?: continue
                blob.read().collect { record -> emit(record) }
              }
            },
        )
  }

  /** Deletes [blobKey] if present (used to clean up temp per-shard blobs after a merge). */
  suspend fun delete(blobKey: String) {
    storageClient.getBlob(blobKey)?.delete()
  }

  private fun encryptedClient(encryptedDek: EncryptedDek): MesosRecordIoStorageClient =
      EncryptedStorage.buildEncryptedMesosStorageClient(
          storageClient,
          kmsClient = kmsClient,
          kekUri = encryptedDek.kekUri,
          encryptedDek = encryptedDek,
      )

  companion object {
    const val TINK_KEY_TEMPLATE = "AES128_GCM"
    private const val TYPE_URL_TINK_KEYSET = "type.googleapis.com/google.crypto.tink.Keyset"
  }
}
