package(default_visibility = ["//visibility:public"])

filegroup(
    name = "computations_scehema",
    srcs = ["computations.sdl"],
)

filegroup(
    name = "measurement_provider_schema",
    srcs = ["measurement_provider.sdl"],
)
