package(default_visibility = ["//visibility:public"])

filegroup(
    name = "computations_scehema",
    srcs = ["computations.sdl"],
)

filegroup(
    name = "kingdom_schema",
    srcs = ["kingdom.sdl"],
)
