# proto-file: wfa/measurement/integration/k8s/testing/correctness_test_config.proto
# proto-message: CorrectnessTestConfig
kingdom_public_api_target: "{kingdom_public_api_target}"
kingdom_public_api_cert_host: "{kingdom_public_api_cert_host}"
measurement_consumer: "{mc_name}"
api_authentication_key: "{mc_api_key}"
reporting_public_api_target: "{reporting_public_api_target}"
reporting_public_api_cert_host: "{reporting_public_api_cert_host}"
reporting_service_endpoint: "{reporting_service_endpoint}"
reporting_token_audience: "{reporting_token_audience}"
access_public_api_target: "{access_public_api_target}"
access_public_api_cert_host: "{access_public_api_cert_host}"
event_data_providers: "{edp1_name}"
event_data_providers: "{edp2_name}"
event_data_providers: "{edp3_name}"
event_data_providers: "{edp4_name}"
event_data_providers: "{edp5_name}"
event_data_providers: "{edp6_name}"
population_data_provider: "{pdp_name}"
model_provider: "{mp_name}"
model_line: "{model_line_name}"
