# proto-file: src/main/proto/wfa/measurement/integration/k8s/testing/edpa_reporting_integration_test_config.proto
# proto-message: EdpaReportingIntegrationTestConfig
kingdom_public_api_target: "{kingdom_public_api_target}"
kingdom_public_api_cert_host: "{kingdom_public_api_cert_host}"
measurement_consumer: "{mc_name}"
api_authentication_key: "{mc_api_key}"
storage_bucket: "{storage_bucket}"
reporting_service_endpoint: "{reporting_service_endpoint}"
reporting_token_audience: "{reporting_token_audience}"
reporting_public_api_target: "{reporting_public_api_target}"
reporting_public_api_cert_host: "{reporting_public_api_cert_host}"
access_public_api_target: "{access_public_api_target}"
access_public_api_cert_host: "{access_public_api_cert_host}"
model_line: "{model_line}"
edp_names: "{edp_names}"
population_data_provider: "{population_data_provider}"
edp7_kek_uri: "{edp7_kek_uri}"
edpa_meta_kek_uri: "{edpa_meta_kek_uri}"
edpa_meta_aws_role_arn: "{edpa_meta_aws_role_arn}"
edpa_meta_aws_region: "{edpa_meta_aws_region}"
