# proto-file: src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto
# proto-message: EncryptionKeyPairConfig

key_pairs {
  key: "mc_enc_public.tink"
  value: "mc_enc_private.tink"
}
key_pairs {
  key: "edp1_enc_public.tink"
  value: "edp1_enc_private.tink"
}

