#!/usr/bin/env bash
# Copyright 2023 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run api-linter with appropriate dependencies.
#
# Usage: api-lint PATH [OPTION]...
# Params:
#   PATH  Path relative to PROTO_PATH under which to find *.proto files.

set -eu -o pipefail

readonly BAZEL="${BAZEL:-bazel}"
readonly PROTO_PATH='src/main/proto'

build() {
  "$BAZEL" query "kind('^proto_library rule', @com_github_protocolbuffers_protobuf//:all + @com_google_googleapis//google/type:all + @com_google_googleapis//google/api:all)" --output=label |
    xargs "$BAZEL" build
}

get_proto_files() {
  find "$PROTO_PATH" \
    -path "$PROTO_PATH/${path}/*" \
    -name '*.proto' \
    -printf '%P\0'
}

lint() {
  get_proto_files |
    xargs -0 api-linter \
    --set-exit-status \
    --proto-path "$PROTO_PATH" \
    --config "$PROTO_PATH/api-linter.yaml" \
    --descriptor-set-in "${bazel_bin}/external/com_github_protocolbuffers_protobuf/descriptor_proto-descriptor-set.proto.bin" \
    --descriptor-set-in "${bazel_bin}/external/com_google_googleapis/google/type/date_proto-descriptor-set.proto.bin" \
    --descriptor-set-in "${bazel_bin}/external/com_google_googleapis/google/api/resource_proto-descriptor-set.proto.bin" \
    --descriptor-set-in "${bazel_bin}/external/com_google_googleapis/google/api/field_behavior_proto-descriptor-set.proto.bin" \
    --descriptor-set-in "${bazel_bin}/external/com_google_googleapis/google/api/client_proto-descriptor-set.proto.bin" \
    --descriptor-set-in "${bazel_bin}/external/com_google_googleapis/google/api/http_proto-descriptor-set.proto.bin" \
    --descriptor-set-in "${bazel_bin}/external/com_google_googleapis/google/api/annotations_proto-descriptor-set.proto.bin" \
    "$@"
}

main() {
  readonly path="$1"
  shift 1

  declare bazel_bin
  bazel_bin="$("$BAZEL" info bazel-bin)"

  build
  lint "$@"
}

main "$@"
