// Copyright 2026 The Cross-Media Measurement Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package wfa.measurement.config.edpaggregator;

import "google/api/resource.proto";

option java_package = "org.wfanet.measurement.config.edpaggregator";
option java_multiple_files = true;
option java_outer_classname = "ResultsFulfillerConfigProto";

// Static configuration used to construct ResultsFulfiller WorkItem parameters.
message ResultsFulfillerConfig {
  // The CMMS resource name for the EDP.
  string data_provider = 1
      [(google.api.resource_reference).type = "halo.wfanet.org/DataProvider"];

  message StorageParams {
    // Blob URI prefix for labeled-impression BlobDetails.
    string labeled_impressions_blob_details_uri_prefix = 1;

    // GCS project used to read requisition blobs.
    string gcs_project_id = 4;
  }
  StorageParams storage_params = 2;

  message ConsentParams {
    string result_cs_cert_der_resource_path = 1;
    string result_cs_private_key_der_resource_path = 2;
    string private_encryption_key_resource_path = 3;
    string edp_certificate_name = 4
        [(google.api.resource_reference).type = "halo.wfanet.org/Certificate"];
  }
  ConsentParams consent_params = 3;

  message CmmsConnectionParams {
    string client_cert_resource_path = 1;
    string client_private_key_resource_path = 2;
  }
  CmmsConnectionParams cmms_connection = 4;

  message NoiseParams {
    enum NoiseType {
      UNSPECIFIED = 0;
      NONE = 1;
      CONTINUOUS_GAUSSIAN = 2;
      DETERMINISTIC_TRUNCATED_LAPLACE = 3;
    }
    NoiseType noise_type = 1;
  }
  NoiseParams noise_params = 5;

  message KAnonymityParams {
    int32 min_impressions = 1;
    int32 min_users = 2;
    int32 reach_max_frequency_per_user = 3;
  }
  KAnonymityParams k_anonymity_params = 6;

  int32 impression_max_frequency_per_user = 7;
  map<string, string> model_line_map = 8;

  message TrusTeeParams {
    map<string, string> kek_uri_to_key_name = 1;
  }
  TrusTeeParams trustee_params = 9;

  message MultiPartyConfig {
    repeated NoiseParams.NoiseType supported_noise_types = 1;
  }
  MultiPartyConfig multi_party_config = 10;

  enum ImpressionCapMode {
    UNSPECIFIED = 0;
    UNCAPPED = 1;
    USE_MEASUREMENT_SPEC_CAP = 2;
    CUSTOM_CAP = 3;
    DYNAMIC = 4;
  }
  ImpressionCapMode impression_cap_mode = 11;
}
