# proto-file: wfa/measurement/reporting/v2alpha/reporting_set.proto
# proto-message: ReportingSet

# name: "measurementConsumers/VCTqwV_vFXw/reportingSets/pub-A-ID"

display_name: "pub_A_age_18+"

# For age 18-34, 35-54, 55+
filter: "event_template.age==18_34 || event_template.age==35_54 || event_template.age==55+"

type {
  primitive_reporting_set {
    # Pub A
    event_groups: "measurementConsumers/VCTqwV_vFXw/dataProviders/FeQ5FqAQ5_0/eventGroups/YSMZ7X_D5Iw"
  }
}