# proto-file: wfa/measurement/reporting/v2alpha/reporting_set.proto
# proto-message: ReportingSet

# name: "measurementConsumers/VCTqwV_vFXw/reportingSets/pub-C-ID"

display_name: "pub_C_age_18+"

# For age 18-34, 35-54, 55+
filter: "event_template.age==18_34 || event_template.age==35_54 || event_template.age==55+"

type {
  primitive_reporting_set {
    # Pub C
    event_groups: "measurementConsumers/VCTqwV_vFXw/dataProviders/JugGwqAQ5wQ/eventGroups/RKIFv4A95-Q"
  }
}