// Copyright 2026 The Cross-Media Measurement Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package wfa.measurement.internal.edpaggregator;

import "google/protobuf/timestamp.proto";
import "wfa/measurement/internal/edpaggregator/raw_impression_upload_correction_candidate.proto";

option java_package = "org.wfanet.measurement.internal.edpaggregator";
option java_multiple_files = true;
option java_outer_classname = "RawImpressionUploadCorrectionCandidateServiceProto";

service RawImpressionUploadCorrectionCandidateService {
  rpc CreateRawImpressionUploadCorrectionCandidate(
      CreateRawImpressionUploadCorrectionCandidateRequest)
      returns (RawImpressionUploadCorrectionCandidate);
  rpc GetRawImpressionUploadCorrectionCandidate(
      GetRawImpressionUploadCorrectionCandidateRequest)
      returns (RawImpressionUploadCorrectionCandidate);
  rpc ListRawImpressionUploadCorrectionCandidates(
      ListRawImpressionUploadCorrectionCandidatesRequest)
      returns (ListRawImpressionUploadCorrectionCandidatesResponse);
  rpc AdvanceRawImpressionUploadCorrectionCandidate(
      AdvanceRawImpressionUploadCorrectionCandidateRequest)
      returns (RawImpressionUploadCorrectionCandidate);
}

message CreateRawImpressionUploadCorrectionCandidateRequest {
  string data_provider_resource_id = 1;
  string raw_impression_upload_correction_candidate_id = 2;
  RawImpressionUploadCorrectionCandidate
      raw_impression_upload_correction_candidate = 3;
  string request_id = 4;
}

message GetRawImpressionUploadCorrectionCandidateRequest {
  string data_provider_resource_id = 1;
  string raw_impression_upload_correction_candidate_id = 2;
}

message ListRawImpressionUploadCorrectionCandidatesRequest {
  string data_provider_resource_id = 1;
  int32 page_size = 2;
  ListRawImpressionUploadCorrectionCandidatesPageToken page_token = 3;

  message Filter {
    repeated RawImpressionUploadCorrectionCandidate.State state_in = 1;
    repeated RawImpressionUploadCorrectionCandidate.Classification
        classification_in = 2;
  }
  Filter filter = 4;
}

message ListRawImpressionUploadCorrectionCandidatesResponse {
  repeated RawImpressionUploadCorrectionCandidate
      raw_impression_upload_correction_candidates = 1;
  ListRawImpressionUploadCorrectionCandidatesPageToken next_page_token = 2;
}

message ListRawImpressionUploadCorrectionCandidatesPageToken {
  message After {
    google.protobuf.Timestamp create_time = 1;
    string raw_impression_upload_correction_candidate_id = 2;
  }
  After after = 1;
}

message AdvanceRawImpressionUploadCorrectionCandidateRequest {
  enum Action {
    ACTION_UNSPECIFIED = 0;
    ASSIGN_PLAN = 1;
    APPROVE_APPLY_CANDIDATE = 2;
    APPROVE_REMOVE_WITHOUT_REPLACEMENT = 3;
    COMPLETE = 4;
    SUPERSEDE = 5;
    REQUIRE_MANUAL_INTERVENTION = 6;
  }

  string data_provider_resource_id = 1;
  string raw_impression_upload_correction_candidate_id = 2;
  string etag = 3;
  Action action = 4;
  string upload_healing_operation_id = 5;
  string superseding_raw_impression_upload_correction_candidate_id = 6;
  string request_id = 7;
}
