# Copyright 2025 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Deploy cloud functions"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy-cloud-functions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.CLOUD_FUNCTIONS_SERVICE_ACCOUNT }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCLOUD_PROJECT }}

      - name: Get short SHA
        id: short-sha
        run: echo "value=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Trigger Cloud Build for Data Watcher
        env:
          BUCKET_NAME: ${{ vars.CLOUD_BUILD_BUCKET_NAME }}
        run: |
          gcloud builds submit --config=/src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/cloudfunction/cloudbuild.yaml . \
            --substitutions=CLOUD_BUILD_BUCKET_NAME=${BUCKET_NAME}, COMMIT_SHA=${{ steps.short-sha.outputs.value }}

      - name: Set build paths output for Cloud Functions
        id: set-build-paths
        run: |
          echo "build-path-data-watcher=artifacts/data_watcher/${{ steps.short-sha.outputs.value }}/data_watcher_function.jar" >> "$GITHUB_OUTPUT"