# Copyright 2023 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run EDP Aggregator Cloud Test

on:
  push:
    branches:
      - marcopremier/edpa_cloud_test_workflow
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub-managed environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - head

permissions:
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-22.04
#    environment: ${{ inputs.environment }}
    environment: "dev"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bazel
        uses: world-federation-of-advertisers/actions/setup-bazel@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.TF_SERVICE_ACCOUNT }}
          token_format: 'id_token'
          id_token_audience: ${{ vars.REQUISITION_FETCHER_TARGET }}

      - name: Write auth.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          cat << EOF > auth.bazelrc
          build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY
          EOF

      - name: Write ~/.bazelrc
        env:
          KINGDOM_PUBLIC_API_TARGET: ${{ vars.KINGDOM_PUBLIC_API_TARGET }}
          MC_NAME: ${{ vars.MC_NAME }}
          MC_API_KEY: ${{ secrets.MC_API_KEY }}
          AUTH_ID_TOKEN: ${{ steps.auth.outputs.id_token }}
          REQUISITION_FETCHER_TARGET: ${{ vars.REQUISITION_FETCHER_TARGET }}
        run: |
          cat << EOF > ~/.bazelrc
          common --config=ci
          build --define kingdom_public_api_target=$KINGDOM_PUBLIC_API_TARGET
          build --define mc_name=$MC_NAME
          build --define mc_api_key=$MC_API_KEY
#          build --define google_cloud_project=$GCLOUD_PROJECT
          build --define auth_id_token=$AUTH_ID_TOKEN
          build --define requisition_fetcher_target=$REQUISITION_FETCHER_TARGET
          test --test_output=streamed
          test --test_timeout=3600
          test --test_env=GOOGLE_APPLICATION_CREDENTIALS
          test --test_env=GOOGLE_CLOUD_PROJECT
          EOF

      # Reduce chance of disconnection from the Build Event Service.
      - name: Set TCP keepalive
        run: sudo sysctl -w net.ipv4.tcp_keepalive_time=60

      - name: Run tests
        id: run-tests
#        env:
#          AUTH_ID_TOKEN: ${{ steps.auth.outputs.id_token }}
#          REQUISITION_FETCHER_TARGET: ${{ vars.REQUISITION_FETCHER_TARGET }}
        run: |
          bazel test //src/test/kotlin/org/wfanet/measurement/integration/k8s:EdpAggregatorCorrectnessTest

      - name: Upload Bazel testlogs
        continue-on-error: true
        uses: world-federation-of-advertisers/actions/bazel-upload-testlogs@v2
        if: failure() && steps.run-tests.outcome == 'failure'