# Copyright 2023 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Certificates and Keys

on:
  push:
    branches: [ "feature/create_k8s_manifest_kingdom" ]

jobs:
  generate-certs-secrets:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: make directory to store the certs and keys
        run: |
          mkdir test-certs

      - name: Generate certificates and keys
        working-directory: test-certs
        run: |
          openssl genrsa -out ca.key 2048
          openssl req -new -key ca.key -subj "/CN=kubernetes-ca" -out ca.csr
          openssl x509 -req -in ca.csr -signkey ca.key -out ca.crt

          openssl genrsa -out kingdom_tls.key.key 2048
          openssl req -new -key kingdom_tls.key -subj "/CN=kubernetes" -out kingdom_tls.csr
          openssl x509 -req -in kingdom_tls.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out kingdom_tls.crt -days 365

      - name: checking the files in directory
        run: | 
          ls test-certs

