name: Lint

on:
  pull_request:
    branches:
      - main
      - 'releases/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint changed files
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - uses: world-federation-of-advertisers/actions/lint@390a9ea948eef416333f8c257ef6116552a42d23 # v2.6.0
      with:
        license-type: apache
        copyright-holder: The Cross-Media Measurement Authors
