name: Reporting V2 Testing

on:
  push:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-cmms.yml
    secrets: inherit
    with:
      environment: dev
      apply: true

  update-reporting-v2:
    uses: ./.github/workflows/configure-reporting-v2.yml
    needs: [ terraform ]
    with:
      image-tag: e17049db6f5eb6bb9ff9437390806f2dcba28eea
      environment: dev
      apply: true
