name: Reporting V2 Testing

on:
  push:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-cmms.yml
    secrets: inherit
    with:
      environment: dev
      apply: true

  update-reporting-v2:
    uses: ./.github/workflows/configure-reporting-v2.yml
    needs: [ terraform ]
    with:
      image-tag: ea2df80e1a294286ca378cae041d622d5cc17ebd
      environment: dev
      apply: true
