name: Reporting V2 Performance Testing

on:
  push:

jobs:
  update-reporting-v2:
    uses: ./.github/workflows/configure-reporting-v2.yml
    secrets: inherit
    with:
      image-tag: ded8aad3b65490f09d49c578f1a9d57254f55b74
      environment: dev
      apply: true
