# Copyright 2025 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test sign images with rules_oci

on:
  # WIP - on PR for testing the workflow
  pull_request:

jobs:
  push-images:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      packages: write
    env:
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/free-disk-space

      - name: Write auth.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          cat << EOF > auth.bazelrc
          build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY
          EOF

      # WIP - modified, hardcoded github sha for image_tag
      - name: Write ~/.bazelrc
        run: |
          cat << EOF > ~/.bazelrc
          common --config=ci
          build --define container_registry=$CONTAINER_REGISTRY
          build --define image_repo_prefix=$GITHUB_REPOSITORY_OWNER
          build --define image_tag=$GITHUB_SHA
          EOF

      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build images
        run: >
          bazelisk build
          //src/main/docker:push_test_image
          //src/main/docker:sign_test_image

      - name: Push images
        run: |
          bazelisk run //src/main/docker:push_test_image

      - name: Authenticate to Google Cloud for image signing
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.IMAGE_SIGNING_DEV_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.IMAGE_SIGNING_DEV_SA }}
          
      - name: Sign images
        run: |
          bazelisk run //src/main/docker:sign_test_image
