name: Test generate relnotes

on:
  # DO_NOT_SUBMIT: remove pull_request event
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    name: Generate relnotes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan commits
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          STARTING_COMMIT: "f9b1752b3a1c89fb65b7d5150146181a97430be5"
        run: |
          set -euo pipefail
          highlights=()
          breaking_changes=()
          issues_addressed=()
          
          IFS=$'\n'; for pr_title in $(git log --format='%s' ${STARTING_COMMIT} HEAD); do 
            echo "=============="
            echo $pr_title; 
            echo "=============="
            if [[ $pr_title =~ \(#([0-9]+)\)$ ]]; then 
              pr_number="${BASH_REMATCH[1]}"
              echo "Number: ${pr_number}"
              pr_body="$(gh pr view "${pr_number}" --repo "${REPO}" --json body -q .body)"
              echo "Body: ${pr_body}"
              trailers=$(echo "${pr_body}" | git interpret-trailers --trim-empty --parse)
              echo "Trailers:"
              echo "-------------------"

              issue_numbers=()

              for trailer in ${trailers}; do
                if [[ "${trailer}" =~ ^(.*):[[:space:]](.*)$ ]]; then
                  key="${BASH_REMATCH[1]}"
                  value="${BASH_REMATCH[2]}"
                  echo $key
                  echo $value
                  if [[ ${key} == "Issue" ]]; then
                    issue_numbers+=(${value#\#})
                  fi
                fi
              done

              # Generate issues addressed section

              for issue_number in "${issue_numbers[@]}"; do
                echo "${issue_number}"
                gh issue view ${issue_number}
                issue_type=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  "/repos/${REPO}/issues/${issue_number}" | jq -r '(.type // {"name": "_NO_TYPE_"}) | .name')
                # DO_NOT_SUBMIT: replace "_NO_TYPE_" evaluation to the name of the type "Bug"
                echo "-------------------------------------------_HERE--------------------------------------------"
                echo "$issue_type"
                if [[ "${issue_type}" == "_NO_TYPE_" ]]; then
                  issue_title=$(gh issue view "${issue_number}" --json title -q .title)
                  issues_addressed+=("${issue_title}. See #${issue_number}")
                  echo "${issues_addressed[*]}"
                fi
              done
  
              # Generate hightlights and breaking changes sections
              
              reference=""
              if ((${#issue_numbers[@]})); then
                for n in "${issue_numbers[@]}"; do
                  reference+="myIssue#${n} "
                done
                reference="${reference% }"
              else
                reference="myPR#${pr_number}"
              fi

              for trailer in ${trailers}; do
                echo $trailer
                if [[ "${trailer}" =~ ^(.*):[[:space:]](.*)$ ]]; then
                  key="${BASH_REMATCH[1]}"
                  value="${BASH_REMATCH[2]}"
                  case "${key}" in
                    RELNOTES)
                      highlights+=("${value} See ${reference}")
                      ;;
                    BREAKING-CHANGE)
                      breaking_changes+=("${value} See ${reference}")
                      ;;
                    *)
                      :
                      ;;
                  esac
                fi
              done
              echo "-------------------"
            fi 
          done
          echo
          echo
          echo
          render_bullets() {
            local -n _arr=$1   # bash nameref
            if ((${#_arr[@]})); then
              for x in "${_arr[@]}"; do printf -- '- %s\n' "$x"; done
            else
              printf '(none)\n'
            fi
          }

          echo "Highlights:"
          render_bullets highlights
          echo
          echo "Potentially requiring action"
          render_bullets breaking_changes
          echo
          echo "Issues addressed"
          render_bullets issues_addressed
          
