load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "xmm_tracing",
    srcs = [
        "W3CTraceContext.kt",
        "XmmTraceAttributes.kt",
        "XmmTraceLogging.kt",
        "XmmTracing.kt",
    ],
    deps = [
        "//imports/java/io/opentelemetry/api",
        "//imports/java/io/opentelemetry/api:context",
        "//imports/java/io/opentelemetry/extension:kotlin",
        "@wfa_common_jvm//imports/java/io/grpc:api",
        "@wfa_common_jvm//imports/kotlin/kotlinx/coroutines:core",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common",
    ],
)

kt_jvm_library(
    name = "cloud_telemetry",
    srcs = [
        "CloudTelemetry.kt",
        "GoogleCloudTelemetry.kt",
    ],
    deps = [
        "//imports/java/com/google/auth:oauth_http2",
        "//imports/java/com/google/cloud/logging",
        "@wfa_common_jvm//imports/java/com/google/gson",
        "@wfa_common_jvm//imports/kotlin/kotlinx/coroutines:core",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/throttler",
    ],
)

kt_jvm_library(
    name = "report_tracing",
    srcs = [
        "ReportTraceAttributes.kt",
        "ReportTraceLogging.kt",
        "ReportTracing.kt",
    ],
    deps = [
        ":xmm_tracing",
        "//imports/java/io/opentelemetry/api",
        "//imports/java/io/opentelemetry/api:context",
        "//imports/java/io/opentelemetry/extension:kotlin",
        "//src/main/proto/wfa/measurement/api/v2alpha:measurement_spec_kt_jvm_proto",
        "@wfa_common_jvm//imports/kotlin/kotlinx/coroutines:core",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common",
    ],
)
